Repository uninus-opensource/uninus-superapp, pull requests merged in 2023-09, with the labels that each got.

#986 Improvement/change justify text hero banner
  apps/web/pmb/user/public/illustrations/beasiswa-banner.webp
  apps/web/pmb/user/public/illustrations/prodi-banner.webp
  libs/web/modules/src/landing/banner-welcome/section.tsx
  libs/web/modules/src/landing/detail/section.tsx
  libs/web/modules/src/program-studi/module.tsx
  libs/web/modules/src/scholarship/module.tsx
Labels: improvement, FE

#997 Improvement/tata usaha setup tailwind
  apps/web/tata-usaha/app/global.css
  apps/web/tata-usaha/app/layout.tsx
  apps/web/tata-usaha/app/page.tsx
  apps/web/tata-usaha/postcss.config.js
  apps/web/tata-usaha/tailwind.config.js
  package.json
Labels: enhancement, FE

#994 improvement: update zod and swagger for update user
  apps/api/pmb/src/app/app.controller.ts
  libs/api/services/src/swagger/user-swagger/create-user/index.ts
  libs/entities/src/schemas/user-schemas/create-user/index.ts
  libs/entities/src/schemas/user-schemas/update-user/index.ts
Labels: improvement, BE

#998 improvement: update endpoint select microservice
  apps/api/pmb/src/general/general.controller.ts
  apps/api/pmb/src/general/general.service.ts
  libs/api/controllers/src/select/index.ts
  libs/entities/src/types/select-field.ts
Labels: improvement, BE

#1002 improvement: submit biodata form & bugfix: issues from QA
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/schema.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/store.ts
Labels: bug, improvement, FE

#1003 Feature : Set up Tailwind in Admin Keuangan page
  apps/web/keuangan/app/global.css
  apps/web/keuangan/app/layout.tsx
  apps/web/keuangan/app/page.tsx
  apps/web/keuangan/postcss.config.js
  apps/web/keuangan/public/illustrations/bg-auth-keuangan.webp
  apps/web/keuangan/public/illustrations/dark-hybrid-university.webp
  apps/web/keuangan/public/illustrations/dark-neo-uninus.webp
  apps/web/keuangan/public/illustrations/dummy-avatar.webp
  apps/web/keuangan/tailwind.config.js
  libs/web/modules/src/auth/login/module.tsx
  package.json
Labels: enhancement, FE

#1006 feature: setup app manajemen pegawai
  apps/web/pegawai/app/global.css
  apps/web/pegawai/app/layout.tsx
  apps/web/pegawai/app/page.tsx
  apps/web/pegawai/postcss.config.js
  apps/web/pegawai/tailwind.config.js
  package.json
Labels: enhancement, FE

#1010 Improvement : responsive landing page and setup nextauth to siakad
  apps/web/evaluasi/app/layout.tsx
  apps/web/evaluasi/app/page.tsx
  apps/web/pmb/admin/app/dashboard/data-akun/page.tsx
  apps/web/pmb/admin/app/dashboard/data-pendaftar/page.tsx
  apps/web/pmb/admin/app/dashboard/template.tsx
  apps/web/siakad/app/api/auth/[...nextauth]/route.ts
  apps/web/siakad/app/api/hello/route.ts
  apps/web/siakad/app/page.tsx
  apps/web/siakad/nextauth.d.ts
  libs/web/components/src/organisms/card/index.tsx
  libs/web/components/src/organisms/tab/index.tsx
  libs/web/modules/src/dashboard/admin/data-akun/index.tsx
  libs/web/modules/src/dashboard/admin/index.ts
  libs/web/modules/src/dashboard/index.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/module.tsx
  libs/web/modules/src/landing/banner-welcome/section.tsx
  libs/web/modules/src/landing/benefit/section.tsx
  libs/web/modules/src/landing/detail/section.tsx
  libs/web/modules/src/landing/program-study/section.tsx
  libs/web/modules/src/landing/selection/section.tsx
  package.json
Labels: enhancement, FE

#1015 feature:setup-tailwind-responsive-nilai-utbk
  apps/web/tracer-alumni/app/api/auth/[...nextauth]/route.ts
  apps/web/tracer-alumni/app/api/hello/route.ts
  apps/web/tracer-alumni/app/global.css
  apps/web/tracer-alumni/app/layout.tsx
  apps/web/tracer-alumni/app/page.tsx
  apps/web/tracer-alumni/nextauth.d.ts
  apps/web/tracer-alumni/postcss.config.js
  apps/web/tracer-alumni/public/illustrations/bg-auth-keuangan.webp
  apps/web/tracer-alumni/public/illustrations/dark-hybrid-university.webp
  apps/web/tracer-alumni/public/illustrations/dark-neo-uninus.webp
  apps/web/tracer-alumni/public/illustrations/dummy-avatar.webp
  apps/web/tracer-alumni/tailwind.config.js
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  package.json
Labels: enhancement, improvement, FE

#1023 Improvement/total registrans with filter
  apps/api/pmb/src/general/general.controller.ts
  apps/api/pmb/src/general/general.service.ts
  libs/api/controllers/src/select/index.ts
  libs/entities/src/types/select-field.ts
Labels: improvement, BE

#1026 Improvement/tata usaha login page
  apps/web/tata-usaha/app/api/auth/[...nextauth]/route.ts
  apps/web/tata-usaha/app/layout.tsx
  apps/web/tata-usaha/app/page.tsx
  apps/web/tata-usaha/nextauth.d.ts
  apps/web/tata-usaha/public/illustrations/bg-auth-tata-usaha.webp
  apps/web/tata-usaha/public/illustrations/dark-hybrid-university.webp
  apps/web/tata-usaha/public/illustrations/dark-neo-uninus.webp
  apps/web/tata-usaha/public/illustrations/dummy-avatar.webp
  apps/web/tata-usaha/tailwind.config.js
  libs/web/modules/src/auth/login/module.tsx
Labels: improvement, FE

#1031 Feature : Slicing login admin pmb dan evaluasi
  apps/web/evaluasi/app/layout.tsx
  apps/web/evaluasi/app/page.tsx
  apps/web/evaluasi/nextauth.d.ts
  apps/web/evaluasi/public/favicon.ico
  apps/web/evaluasi/public/illustrations/bg-auth-evaluasi.webp
  apps/web/evaluasi/public/illustrations/dark-hybrid-university.webp
  apps/web/evaluasi/public/illustrations/dark-neo-uninus.webp
  apps/web/evaluasi/public/illustrations/dummy-avatar.webp
  apps/web/evaluasi/public/logo.ico
  apps/web/pmb/admin/app/page.tsx
  apps/web/pmb/admin/public/favicon.ico
  apps/web/pmb/admin/public/illustrations/bg-auth-admin.webp
  apps/web/pmb/admin/public/illustrations/dark-hybrid-university.webp
  apps/web/pmb/admin/public/illustrations/dark-neo-uninus.webp
  apps/web/pmb/admin/public/logo.svg
  apps/web/pmb/user/app/page.tsx
  apps/web/pmb/user/public/favicon.ico
  apps/web/pmb/user/public/logo.ico
  apps/web/siakad/public/illustrations/bg-auth-keuangan.webp
  apps/web/siakad/public/illustrations/dark-hybrid-university.webp
  apps/web/siakad/public/illustrations/dark-neo-uninus.webp
  apps/web/siakad/public/illustrations/dummy-avatar.webp
  libs/web/modules/src/auth/login/module.tsx
Labels: improvement, FE

#1028 Improve SEO pmb
  apps/web/pmb/admin/app/dashboard/data-akun/page.tsx
  apps/web/pmb/admin/app/dashboard/data-pendaftar/page.tsx
  apps/web/pmb/admin/app/dashboard/page.tsx
  apps/web/pmb/admin/app/page.tsx
  apps/web/pmb/user/app/beasiswa/detail/beasiswa-mitra/page.tsx
  apps/web/pmb/user/app/beasiswa/detail/beasiswa-peduli/page.tsx
  apps/web/pmb/user/app/beasiswa/detail/beasiswa-prestasi/page.tsx
  apps/web/pmb/user/app/beasiswa/detail/beasiswa-unggul/page.tsx
  apps/web/pmb/user/app/beasiswa/page.tsx
  apps/web/pmb/user/app/biaya-kuliah/page.tsx
  apps/web/pmb/user/app/dashboard/dokumen/page.tsx
  apps/web/pmb/user/app/dashboard/page.tsx
  apps/web/pmb/user/app/dashboard/pendaftaran/page.tsx
  apps/web/pmb/user/app/dashboard/registrasi/beasiswa/page.tsx
  apps/web/pmb/user/app/dashboard/registrasi/biodata/page.tsx
  apps/web/pmb/user/app/dashboard/registrasi/pembayaran/detail/page.tsx
  apps/web/pmb/user/app/dashboard/registrasi/pembayaran/status/page.tsx
  apps/web/pmb/user/app/dashboard/selection/endtest/page.tsx
  apps/web/pmb/user/app/dashboard/selection/intruction/page.tsx
  apps/web/pmb/user/app/dashboard/selection/page.tsx
  apps/web/pmb/user/app/page.tsx
  apps/web/pmb/user/app/program-studi/page.tsx
  libs/web/components/src/atoms/button/index.tsx
  libs/web/components/src/atoms/reveal/index.tsx
  libs/web/components/src/molecules/footer/index.spec.tsx
  libs/web/components/src/molecules/footer/index.tsx
  libs/web/components/src/organisms/hero-banner/index.tsx
  libs/web/components/src/organisms/modal/index.spec.tsx
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/modules/src/landing/banner-welcome/section.tsx
  libs/web/modules/src/landing/benefit/section.tsx
  libs/web/modules/src/landing/modal-floatingbutton/section.tsx
Labels: improvement, FE

#1032 improvement: select option sesuai design figma
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
Labels: improvement, FE

#1034 feature: slicing auth manajemen pegawai
  apps/web/pegawai/app/api/auth/[...nextauth]/route.ts
  apps/web/pegawai/app/page.tsx
  apps/web/pegawai/nextauth.d.ts
  apps/web/pegawai/public/illustrations/bg-auth-pegawai.webp
  apps/web/pegawai/public/illustrations/dark-hybrid-university.webp
  apps/web/pegawai/public/illustrations/dark-neo-uninus.webp
  apps/web/pegawai/public/illustrations/dummy-avatar.webp
  apps/web/pegawai/tailwind.config.js
  libs/web/modules/src/auth/login/module.tsx
Labels: enhancement, FE

#1037 feature: endpoint interest education programs
  apps/api/pmb/src/general/general.controller.ts
  apps/api/pmb/src/general/general.service.ts
  libs/api/controllers/src/select/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/entities/src/types/select-field.ts
Labels: enhancement, BE

#1041 improvement: custom registration number with format
  apps/api/auth/src/app/app.service.ts
Labels: improvement, BE

#1048 feature: login auth manajemen pegawai
  apps/web/pegawai/app/dashboard/page.tsx
  apps/web/pegawai/app/dashboard/template.tsx
  apps/web/pegawai/app/layout.tsx
  apps/web/pegawai/middleware.ts
  apps/web/pegawai/next.config.js
  apps/web/pegawai/public/illustrations/dummy-avatar copy.webp
  apps/web/pegawai/public/illustrations/logOut.webp
  apps/web/pmb/user/cypress/e2e/app.cy.ts
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/auth/logout/hook.ts
Labels: enhancement, FE

#1051 improvement: pmb reset password recoil
  apps/web/pegawai/app/dashboard/template.tsx
  libs/web/modules/src/auth/forgot/module.tsx
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/auth/register/module.tsx
  libs/web/modules/src/auth/reset/module.tsx
  libs/web/modules/src/auth/verifikasi-berhasil/module.tsx
  libs/web/modules/src/auth/verifikasi-forget/module.tsx
  libs/web/modules/src/auth/verifikasi-otp/module.tsx
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: improvement, FE

#1052 delete loading pmb landing
  apps/web/pmb/user/app/loading.tsx
Labels: FE

#1054 improvement:auth-tracer-alumni
  apps/web/tracer-alumni/app/dashboard/page.tsx
  apps/web/tracer-alumni/app/dashboard/template.tsx
  apps/web/tracer-alumni/app/layout.tsx
  apps/web/tracer-alumni/middleware.ts
  apps/web/tracer-alumni/next.config.js
  apps/web/tracer-alumni/public/illustrations/bg-auth-tracer.webp
  apps/web/tracer-alumni/public/illustrations/logOut.webp
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/schema.ts
Labels: improvement, FE

#1055 bugfix: bug endpoint resend otp
  apps/api/pmb/src/app/app.controller.ts
  apps/api/pmb/src/app/app.service.ts
Labels: bug, BE

#1057 improvement: update response login
  apps/api/auth/src/app/app.service.ts
  libs/api/controllers/src/auth/index.ts
Labels: improvement, BE

#1068 improvement:rata-rata-utbk
  libs/web/modules/src/dashboard/user/registrasi/biodata/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/type.ts
Labels: improvement, FE

#1076 Bugfix/register response
  apps/api/auth/src/app/app.controller.ts
  apps/api/auth/src/app/app.service.ts
  libs/api/controllers/src/auth/index.ts
  libs/api/controllers/src/user/index.ts
  libs/api/filter/src/rpcexception/rpcToHttp.filter.ts
  libs/api/services/src/auth/index.ts
  libs/api/services/src/swagger/auth-swagger/forgot-password/index.ts
  libs/api/services/src/swagger/auth-swagger/resend-otp/index.ts
  libs/api/services/src/swagger/auth-swagger/reset-password/index.ts
  libs/api/services/src/swagger/auth-swagger/verify/index.ts
  libs/entities/src/constants/index.ts
  libs/entities/src/constants/profile.ts
  libs/entities/src/constants/student.ts
  libs/entities/src/enum/index.ts
  libs/entities/src/enum/job.ts
  libs/entities/src/index.ts
  libs/entities/src/templates/email.ts
  libs/entities/src/templates/index.ts
  libs/entities/src/types/auth/email-user/index.ts
  libs/entities/src/types/auth/forgot-password/index.ts
  libs/entities/src/types/auth/index.ts
  libs/entities/src/types/auth/jwt/index.ts
  libs/entities/src/types/auth/login/index.ts
  libs/entities/src/types/auth/logout/index.ts
  libs/entities/src/types/auth/otp/index.ts
  libs/entities/src/types/auth/register/index.ts
  libs/entities/src/types/auth/token/index.ts
  libs/entities/src/types/filter.ts
  libs/entities/src/types/forgot-password.ts
  libs/entities/src/types/index.ts
  libs/entities/src/types/resend-otp.ts
  libs/entities/src/types/rt-payload.ts
  libs/entities/src/types/verify-otp-password.ts
  libs/entities/src/types/verify-otp.ts
Labels: bug, improvement, BE

#1082 bugfix: types select option & styling data nilai section biodata
  apps/web/pmb/user/app/global.css
  apps/web/pmb/user/app/page.tsx
  apps/web/pmb/user/public/icon.ico
  libs/entities/src/types/select-field.ts
  libs/web/components/src/molecules/inputs/upload-field/index.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
Labels: bug, FE

#1092 Feature/news testimonial section
  apps/web/pmb/user/public/illustrations/news1.webp
  apps/web/pmb/user/public/illustrations/news2.webp
  apps/web/pmb/user/public/illustrations/news3.webp
  apps/web/pmb/user/public/illustrations/news4.webp
  apps/web/pmb/user/public/illustrations/news5.webp
  apps/web/pmb/user/public/illustrations/testi1.webp
  apps/web/pmb/user/public/illustrations/testi2.webp
  libs/web/components/src/organisms/card-image/index.tsx
  libs/web/components/src/organisms/card-image/type.ts
  libs/web/components/src/organisms/index.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/landing/module.tsx
  libs/web/modules/src/landing/news/index.ts
  libs/web/modules/src/landing/news/section.tsx
  libs/web/modules/src/landing/news/type.ts
  libs/web/modules/src/landing/testimonial/index.ts
  libs/web/modules/src/landing/testimonial/section.tsx
  libs/web/modules/src/landing/testimonial/style.css
  libs/web/modules/src/landing/testimonial/type.ts
Labels: FE

#1099 feature:endpoint registration status and interest department
  apps/api/general/src/app/app.controller.ts
  apps/api/general/src/app/app.service.ts
  libs/api/controllers/src/general/index.ts
  libs/entities/src/enum/index.ts
  libs/entities/src/enum/select-field.ts
  libs/entities/src/types/general/index.ts
Labels: enhancement, improvement, BE

#1100 Improvement : Add Skeleton Admin pmb page & setup Tailwind Admin Keua…
  apps/web/evaluasi/.env.example
  apps/web/evaluasi/app/dashboard/page.tsx
  apps/web/evaluasi/app/layout.tsx
  apps/web/evaluasi/app/page.tsx
  apps/web/pmb/admin/app/dashboard/data-akun/loading.tsx
  apps/web/pmb/admin/app/dashboard/loading.tsx
  apps/web/pmb/admin/next.config.js
  apps/web/sisfo/keuangan/app/api/auth/[...nextauth]/route.ts
  apps/web/sisfo/keuangan/app/dashboard/page.tsx
  apps/web/sisfo/keuangan/app/global.css
  apps/web/sisfo/keuangan/app/layout.tsx
  apps/web/sisfo/keuangan/app/page.tsx
  apps/web/sisfo/keuangan/nextauth.d.ts
  apps/web/sisfo/keuangan/postcss.config.js
  apps/web/sisfo/keuangan/public/favicon.ico
  apps/web/sisfo/keuangan/public/icon.ico
  apps/web/sisfo/keuangan/public/illustrations/bg-auth.webp
  apps/web/sisfo/keuangan/public/illustrations/dark-hybrid-university.webp
  apps/web/sisfo/keuangan/public/illustrations/dark-neo-uninus.webp
  apps/web/sisfo/keuangan/public/illustrations/dummy-avatar.webp
  apps/web/sisfo/keuangan/tailwind.config.js
  libs/web/components/src/atoms/loadings/index.ts
  libs/web/components/src/atoms/loadings/spinner/index.spec.tsx
  libs/web/components/src/atoms/loadings/table-loading/index.spec.tsx
  libs/web/components/src/atoms/loadings/table-loading/index.tsx
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/dashboard/admin/data-akun/table.tsx
  libs/web/modules/src/dashboard/admin/data-bayar/table.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/table.tsx
  package.json
Labels: improvement, FE

#1101 update bg module auth
  apps/web/evaluasi/public/illustrations/backgroundAuthLg.svg
  apps/web/evaluasi/public/illustrations/backgroundAuthMd.svg
  apps/web/pegawai/public/illustrations/backgroundAuthLg.svg
  apps/web/pegawai/public/illustrations/backgroundAuthMd.svg
  apps/web/siakad/public/illustrations/backgroundAuthLg.svg
  apps/web/siakad/public/illustrations/backgroundAuthMd.svg
  apps/web/tata-usaha/public/illustrations/backgroundAuthLg.svg
  apps/web/tata-usaha/public/illustrations/backgroundAuthMd.svg
  apps/web/tracer-alumni/public/illustrations/backgroundAuthLg.svg
  apps/web/tracer-alumni/public/illustrations/backgroundAuthMd.svg
  libs/web/modules/src/auth/login/module.tsx
Labels: improvement, FE

#1104 improvement: remove null object value from student
  apps/api/auth/src/app/app.service.ts
  apps/api/student/src/app/app.service.ts
  libs/entities/src/types/student/index.ts
Labels: improvement, BE

#1106 Bufix/pmb style landing
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/modules/src/landing/benefit/section.tsx
  libs/web/modules/src/landing/detail/section.tsx
  libs/web/modules/src/landing/selection/section.tsx
  libs/web/modules/src/landing/testimonial/section.tsx
Labels: bug, FE

#1107 Improvement : table data account and add modal to add and edit
  apps/web/pmb/admin/public/illustrations/backgroundAuthLg.svg
  apps/web/pmb/admin/public/illustrations/backgroundAuthMd.svg
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/dashboard/admin/data-akun/table.tsx
Labels: improvement

#1108 Bugfix/pmb landing
  apps/web/pmb/user/public/illustrations/testi3.webp
  apps/web/pmb/user/public/illustrations/testi4.webp
  libs/web/components/src/molecules/inputs/search/index.spec.tsx
  libs/web/components/src/molecules/inputs/search/index.tsx
  libs/web/components/src/molecules/inputs/search/types.ts
  libs/web/components/src/organisms/card-image/index.tsx
  libs/web/modules/src/landing/news/section.tsx
  libs/web/modules/src/landing/testimonial/section.tsx
  libs/web/modules/src/program-studi/module.tsx
  libs/web/modules/src/tuition-fee/module.tsx
Labels: bug, FE

#1116 Bugfix/berita testimonial landing pmb
  libs/web/modules/src/landing/news/section.tsx
  libs/web/modules/src/landing/news/type.ts
  libs/web/modules/src/landing/testimonial/section.tsx
Labels: bug, FE

#1122 bugfix: fix fail to generate otp
  apps/api/auth/src/app/app.service.ts
  libs/entities/src/types/auth/register/index.ts
Labels: BE

#1124 Feature/integrasi get registrans data pmb admin
  apps/web/pmb/admin/app/dashboard/template.tsx
  libs/web/modules/src/dashboard/admin/api.ts
  libs/web/modules/src/dashboard/admin/hook.ts
  libs/web/modules/src/dashboard/admin/index.ts
  libs/web/modules/src/dashboard/admin/module/card-section.tsx
  libs/web/modules/src/dashboard/admin/module/type.ts
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: enhancement, FE

#1125 feature: integrasi upload berkas
  apps/web/pegawai/app/dashboard/page.tsx
  apps/web/pegawai/next.config.js
  apps/web/pmb/user/next.config.js
  libs/entities/src/types/student/index.ts
  libs/web/components/src/molecules/inputs/upload-field/index.tsx
  libs/web/components/src/molecules/inputs/upload-field/types.ts
  libs/web/modules/src/dashboard/index.ts
  libs/web/modules/src/dashboard/pegawai/data-pegawai/index.tsx
  libs/web/modules/src/dashboard/pegawai/data-pegawai/store.ts
  libs/web/modules/src/dashboard/pegawai/data-pegawai/table.tsx
  libs/web/modules/src/dashboard/pegawai/data-pegawai/types.ts
  libs/web/modules/src/dashboard/pegawai/index.ts
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/dokumen/type.ts
  libs/web/modules/src/dashboard/user/pendaftaran/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/schema.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/type.ts
Labels: enhancement, FE

#1132 improvement:responsive-form-user
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
Labels: improvement, FE

#1133 Feature/add service employee
  apps/api/employee/.env.example
  apps/api/employee/.eslintrc.json
  apps/api/employee/jest.config.ts
  apps/api/employee/project.json
  apps/api/employee/src/app/app.controller.ts
  apps/api/employee/src/app/app.module.ts
  apps/api/employee/src/app/app.service.ts
  apps/api/employee/src/assets/.gitkeep
  apps/api/employee/src/main.ts
  apps/api/employee/tsconfig.app.json
  apps/api/employee/tsconfig.json
  apps/api/employee/tsconfig.spec.json
  apps/api/employee/webpack.config.js
  libs/api/controllers/src/employee/index.ts
  libs/api/controllers/src/index.ts
  libs/api/master/src/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/api/modules/src/employee/index.ts
  libs/api/modules/src/index.ts
  libs/entities/src/types/employee/dashboard/index.ts
  libs/entities/src/types/employee/index.ts
  libs/entities/src/types/employee/pagination/index.ts
  libs/entities/src/types/index.ts
  package.json
Labels: BE

#1131 bugfix: fix bug otp
  libs/api/guard/src/auth/index.ts
  libs/api/guard/src/auth/permission.guard.ts
  libs/entities/src/enum/apps-origin.ts
  libs/entities/src/enum/index.ts
  package.json
Labels: bug, enhancement, BE

#1144 feature: slicing data pegawai page dashboard
  apps/api/auth/src/app/app.controller.ts
  apps/api/auth/src/app/app.service.ts
  apps/api/file/src/app/app.controller.spec.ts
  apps/api/student/src/app/app.service.ts
  apps/web/evaluasi/app/page.tsx
  apps/web/pegawai/app/dashboard/template.tsx
  apps/web/pegawai/tailwind.config.js
  apps/web/pmb/user/app/testcomp/page.tsx
  apps/web/tracer-alumni/app/dashboard/page.tsx
  libs/api/controllers/src/user/index.ts
  libs/web/components/src/molecules/footer/index.spec.tsx
  libs/web/components/src/molecules/inputs/dragable/types.ts
  libs/web/components/src/molecules/inputs/search/index.spec.tsx
  libs/web/components/src/molecules/inputs/search/index.tsx
  libs/web/components/src/organisms/hero-banner/index.spec.tsx
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/auth/verifikasi-forget/module.tsx
  libs/web/modules/src/auth/verifikasi-otp/module.tsx
  libs/web/modules/src/dashboard/pegawai/data-pegawai/store.ts
  libs/web/modules/src/dashboard/pegawai/data-pegawai/table.tsx
  libs/web/modules/src/dashboard/pegawai/data-pegawai/types.ts
  libs/web/modules/src/dashboard/user/pendaftaran/api.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/module.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/module.tsx
Labels: enhancement, FE

#1146 improvement: new siakad auth
  apps/web/siakad/app/global.css
  apps/web/siakad/public/illustrations/IllustrationAuth.svg
  apps/web/siakad/public/illustrations/background-auth.webp
  apps/web/siakad/public/illustrations/backgroundAuthLg.svg
  apps/web/siakad/public/illustrations/backgroundAuthMd.svg
  apps/web/siakad/public/illustrations/bg-auth-keuangan.webp
  apps/web/siakad/public/illustrations/bg-auth-siakad.webp
  apps/web/siakad/tailwind.config.js
  bun.lockb
  libs/web/modules/src/auth/login/module.tsx
Labels: improvement, FE

#1148 feature: integrasi berkas khusus
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/type.ts
  libs/web/services/src/recoil-store/type.ts
Labels: enhancement, FE

#1156 feature: integrasi minat program pmb admin
  apps/web/pmb/admin/app/dashboard/template.tsx
  bun.lockb
  libs/web/modules/src/dashboard/admin/api.ts
  libs/web/modules/src/dashboard/admin/hook.ts
  libs/web/modules/src/dashboard/admin/module/chart-doughnut.tsx
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: enhancement, FE

#1157 improvement:conditional-rendering-beasiswa
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: improvement, FE

#1158 improvement: otomatis mengubah avatar di sidebar setelah upload foto
  libs/web/components/src/molecules/inputs/upload-field/index.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: enhancement, FE

#1159 feature:pagination registrans
  apps/api/general/src/app/app.controller.ts
  apps/api/general/src/app/app.service.ts
  libs/api/controllers/src/general/index.ts
Labels: improvement, BE

#1175 improvement:change pagination
  apps/api/employee/src/app/app.service.ts
  apps/api/general/src/app/app.controller.ts
  apps/api/general/src/app/app.service.ts
  apps/api/user/src/app/app.controller.ts
  apps/api/user/src/app/app.service.ts
  libs/api/controllers/src/employee/index.ts
  libs/api/controllers/src/general/index.ts
  libs/api/controllers/src/user/index.ts
  libs/api/utilities/src/index.ts
  libs/api/utilities/src/meta/index.ts
  libs/api/utilities/src/meta/paginator.ts
  libs/api/utilities/src/meta/prefix.ts
  libs/entities/src/enum/general.ts
  libs/entities/src/enum/index.ts
  libs/entities/src/types/employee/pagination/index.ts
  libs/entities/src/types/general/index.ts
  libs/entities/src/types/pagination/index.ts
  libs/entities/src/types/user/index.ts
Labels: improvement, BE

#1171 improvement: desain landing pmb
  apps/web/pmb/user/public/illustrations/gerbang-crop.webp
  libs/api/validator/src/zod/zod-validation-pipe.ts
  libs/web/components/src/organisms/modal/index.tsx
  libs/web/components/src/organisms/modal/type.ts
  libs/web/modules/src/landing/banner-welcome/section.tsx
  libs/web/modules/src/landing/modal-floatingbutton/section.tsx
  package.json
  yarn.lock
Labels: improvement, FE

#1174 Improvement :Feature Delete and Read data on Admin/Dashboard/Table Da…
  apps/web/evaluasi/public/illustrations/backgroundAuthLg.svg
  apps/web/evaluasi/public/illustrations/backgroundAuthMd.svg
  apps/web/evaluasi/public/illustrations/shapeBG.svg
  apps/web/pmb/admin/public/illustrations/backgroundAuthLg.svg
  apps/web/pmb/admin/public/illustrations/backgroundAuthMd.svg
  apps/web/pmb/admin/public/illustrations/shapeBG.svg
  libs/entities/src/types/student/index.ts
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/dashboard/admin/data-akun/api.ts
  libs/web/modules/src/dashboard/admin/data-akun/hook.ts
  libs/web/modules/src/dashboard/admin/data-akun/store.ts
  libs/web/modules/src/dashboard/admin/data-akun/table.tsx
  libs/web/modules/src/dashboard/admin/data-akun/types.ts
Labels: improvement, FE

#1193 Feature/slicing edit data pendaftar
  apps/web/pmb/admin/app/dashboard/data-pendaftar/edit-data-pendaftar/page.tsx
  apps/web/pmb/admin/tailwind.config.js
  libs/web/components/src/atoms/button/index.tsx
  libs/web/components/src/atoms/button/interface.ts
  libs/web/modules/src/dashboard/admin/api.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/index.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/module.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-orangtua/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/nilai-raport/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/type.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/module.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/table.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/types.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
Labels: enhancement, FE

#1217 bugfix:fix message pattern
  apps/api/general/src/app/app.service.ts
  bun.lockb
  libs/api/controllers/src/student/index.ts
Labels: bug, BE

#1213 Feature/slicing master data
  apps/web/pmb/admin/app/dashboard/data-master/page.tsx
  apps/web/pmb/admin/app/dashboard/template.tsx
  apps/web/pmb/admin/tailwind.config.js
  libs/web/components/src/atoms/button/index.tsx
  libs/web/components/src/atoms/button/interface.ts
  libs/web/components/src/organisms/modal/index.tsx
  libs/web/components/src/organisms/modal/type.ts
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/dashboard/admin/data-master/index.tsx
  libs/web/modules/src/dashboard/admin/data-master/store.ts
  libs/web/modules/src/dashboard/admin/data-master/table.tsx
  libs/web/modules/src/dashboard/admin/data-master/type.ts
  libs/web/modules/src/dashboard/admin/index.ts
Labels: enhancement, FE

#1216 improvement: update response endpoint get all employee and endpoint dashboard total employee
  apps/api/employee/src/app/app.service.ts
  bun.lockb
  libs/api/controllers/src/employee/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/entities/src/types/employee/dashboard/index.ts
Labels: BE

#1223 improvement: chart filter pmb admin
  libs/web/modules/src/dashboard/admin/module/chart-bar.tsx
  libs/web/modules/src/dashboard/admin/module/chart-doughnut.tsx
  libs/web/modules/src/dashboard/admin/module/chart-line.tsx
Labels: improvement, FE

#1232 feature: integrasi data pendafatar
  apps/web/pmb/admin/app/dashboard/data-pendaftar/edit-data-pendaftar/[id]/page.tsx
  apps/web/pmb/admin/app/dashboard/template.tsx
  apps/web/pmb/admin/app/page.tsx
  apps/web/pmb/admin/middleware.ts
  apps/web/pmb/admin/public/illustrations/logOut.webp
  apps/web/pmb/admin/tailwind.config.js
  libs/web/components/src/atoms/button/index.spec.tsx
  libs/web/components/src/atoms/button/interface.ts
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/dashboard/admin/api.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/api.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/hook.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/module.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-diri/schema.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/store.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/table.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/types.ts
  libs/web/modules/src/dashboard/admin/hook.ts
  libs/web/modules/src/dashboard/admin/type.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/index.ts
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: enhancement, FE

#1233 bugfix: beberapa bugs yang ada di issues
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/store.ts
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/type.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/module.tsx
Labels: bug, FE

#1237 feature: access role dashboard
  apps/web/pmb/admin/app/dashboard/template.tsx
  libs/web/modules/src/dashboard/admin/data-akun/api.ts
  libs/web/modules/src/dashboard/admin/data-akun/hook.ts
  libs/web/modules/src/dashboard/admin/data-akun/index.tsx
  libs/web/modules/src/dashboard/admin/data-akun/table.tsx
  libs/web/modules/src/dashboard/admin/data-bayar/index.tsx
  libs/web/modules/src/dashboard/admin/data-master/index.tsx
  libs/web/modules/src/dashboard/admin/module/chart-bar.tsx
  libs/web/modules/src/dashboard/admin/module/chart-doughnut.tsx
  libs/web/modules/src/dashboard/admin/module/chart-line.tsx
Labels: enhancement, FE

#1242 improvement: check permission role
  apps/api/auth/src/app/app.service.ts
  libs/api/controllers/src/auth/index.ts
  libs/api/controllers/src/employee/index.ts
  libs/api/controllers/src/student/index.ts
  libs/api/controllers/src/user/index.ts
  libs/api/guard/src/auth/permission.guard.ts
  libs/api/models/src/prisma/schema.prisma
  libs/api/modules/src/auth/index.ts
  libs/api/modules/src/employee/index.ts
  libs/api/modules/src/file/index.ts
  libs/api/modules/src/general/index.ts
  libs/api/modules/src/payment/index.ts
  libs/api/modules/src/student/index.ts
  libs/api/modules/src/user/index.ts
  libs/api/services/src/auth/index.ts
  libs/entities/src/schemas/student-schemas/update-student/index.ts
  libs/entities/src/schemas/user-schemas/update-user/index.ts
  libs/entities/src/types/auth/login/index.ts
  libs/entities/src/types/user/index.ts
Labels: improvement, BE

#1244 Feature/endpoint master data
  apps/api/general/src/app/app.controller.ts
  apps/api/general/src/app/app.service.ts
  libs/api/controllers/src/general/index.ts
  libs/api/dto/src/general-dto/index.ts
  libs/api/dto/src/index.ts
  libs/entities/src/types/general/index.ts
Labels: enhancement, BE

#1243 Improvement/add bearer swagger
  libs/api/controllers/src/student/index.ts
  libs/api/controllers/src/user/index.ts
  libs/api/guard/src/auth/permission.guard.ts
  libs/entities/src/schemas/student-schemas/update-student/index.ts
Labels: improvement, BE

#1245 feature: akses ke edit page
  apps/web/pmb/admin/app/dashboard/template.tsx
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/modules/src/auth/login/api.ts
  libs/web/modules/src/dashboard/admin/data-akun/index.tsx
  libs/web/modules/src/dashboard/admin/data-bayar/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/api.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/hook.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/hooks.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/module.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-diri/schema.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-orangtua/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-orangtua/schema.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-pendidikan/schema.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/nilai-raport/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/type.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/store.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/table.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/types.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
Labels: enhancement, FE

#1254 bugfix/redrect access role
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/module.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/table.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
Labels: bug, FE

#1257 bugfix: error cannot read undefined _f
  apps/web/pmb/user/app/dashboard/template.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: enhancement, FE

#1259 Feature : Edit Data Akun On Dashboard Admin
  apps/web/pmb/admin/app/dashboard/page.tsx
  libs/entities/src/types/student/index.ts
  libs/web/components/src/organisms/modal/index.tsx
  libs/web/components/src/organisms/modal/type.ts
  libs/web/modules/src/auth/login/api.ts
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/dashboard/admin/data-akun/api.ts
  libs/web/modules/src/dashboard/admin/data-akun/hook.ts
  libs/web/modules/src/dashboard/admin/data-akun/table.tsx
  libs/web/modules/src/dashboard/admin/data-akun/types.ts
Labels: enhancement, improvement, FE

#1260 Improvement/dummy data doughnut chart
  libs/web/modules/src/dashboard/admin/module/chart-doughnut.tsx
Labels: improvement, FE

#1258 Feature/get master data
  apps/web/pmb/admin/app/dashboard/template.tsx
  libs/web/modules/src/dashboard/admin/api.ts
  libs/web/modules/src/dashboard/admin/data-bayar/table.tsx
  libs/web/modules/src/dashboard/admin/data-bayar/types.ts
  libs/web/modules/src/dashboard/admin/data-master/store.ts
  libs/web/modules/src/dashboard/admin/data-master/table.tsx
  libs/web/modules/src/dashboard/admin/data-master/type.ts
  libs/web/modules/src/dashboard/admin/hook.ts
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: enhancement, FE

#1262 feature: add endpoint get employee categories
  apps/api/general/src/app/app.controller.ts
  apps/api/general/src/app/app.service.ts
  libs/api/controllers/src/general/index.ts
  libs/entities/src/types/general/index.ts
Labels: enhancement, BE

#1264 BugFix : role data akun
  libs/web/modules/src/dashboard/admin/data-akun/api.ts
  libs/web/modules/src/dashboard/admin/data-akun/hook.ts
  libs/web/modules/src/dashboard/admin/data-akun/table.tsx
  libs/web/modules/src/dashboard/admin/data-akun/types.ts
Labels: bug, FE
