Repository uninus-opensource/uninus-superapp, pull requests merged in 2023-12, with the labels that each got.

#1610 Improvement: clean finance and user service
  apps/api/email/jest.config.ts
  apps/api/email/project.json
  apps/api/email/tsconfig.app.json
  apps/api/email/tsconfig.spec.json
  apps/api/employee/src/app/app.controller.ts
  apps/api/employee/src/app/app.service.ts
  apps/api/finance/src/app/app.controller.ts
  apps/api/finance/src/app/app.service.ts
  apps/api/general/src/app/app.controller.ts
  apps/api/general/src/app/app.service.ts
  apps/api/user/src/app/app.controller.ts
  apps/api/user/src/app/app.service.ts
  apps/web/psu/nextauth.d.ts
  libs/api/controllers/src/employee/index.ts
  libs/api/controllers/src/finance/index.ts
  libs/api/controllers/src/general/index.ts
  libs/api/controllers/src/user/index.ts
  libs/api/dto/src/finance/index.ts
  libs/api/dto/src/general/index.ts
  libs/api/dto/src/index.ts
  libs/api/dto/src/payment-dto/index.ts
  libs/api/dto/src/user-dto/index.ts
  libs/api/dto/src/user-dto/update-user/index.ts
  libs/api/dto/src/user/index.ts
  libs/api/modules/src/employee/index.ts
  libs/api/modules/src/finance/index.ts
  libs/api/modules/src/user/index.ts
  libs/api/services/src/employee/index.ts
  libs/api/services/src/finance/index.ts
  libs/api/services/src/index.ts
  libs/api/services/src/user/index.ts
  libs/entities/src/schemas/finance/header.schema.ts
  libs/entities/src/schemas/finance/index.ts
  libs/entities/src/schemas/finance/payment.schema.ts
  libs/entities/src/schemas/index.ts
  libs/entities/src/schemas/payment-schemas/index.ts
  libs/entities/src/schemas/user-schemas/index.ts
  libs/entities/src/schemas/user-schemas/nopeserta-user/index.ts
  libs/entities/src/schemas/user-schemas/update-user/index.ts
  libs/entities/src/schemas/user/index.ts
  libs/entities/src/types/employee/pagination/index.ts
  libs/entities/src/types/filter/index.ts
  libs/entities/src/types/finance/finance.type.ts
  libs/entities/src/types/finance/index.ts
  libs/entities/src/types/finance/payment.type.ts
  libs/entities/src/types/general/location.type.ts
  libs/entities/src/types/user/email-user/index.ts
  libs/entities/src/types/user/index.ts
  libs/entities/src/types/user/user.type.ts
  package.json
  yarn.lock
Labels: improvement, BE

#1612 Improvement: clean general employee
  apps/api/email/src/app/app.service.ts
  apps/api/employee/src/app/app.service.ts
  apps/api/general/src/app/app.controller.ts
  apps/api/general/src/app/app.module.ts
  apps/api/general/src/app/app.service.ts
  apps/api/general/src/app/college/app.controller.ts
  apps/api/general/src/app/college/app.module.ts
  apps/api/general/src/app/college/app.service.ts
  apps/api/general/src/app/college/index.ts
  apps/api/general/src/app/master/app.module.ts
  apps/api/general/src/app/master/index.ts
  apps/api/general/src/app/personal/app.controller.ts
  apps/api/general/src/app/personal/app.module.ts
  apps/api/general/src/app/personal/app.service.ts
  apps/api/general/src/app/personal/index.ts
  apps/api/general/src/app/pmb/app.controller.ts
  apps/api/general/src/app/pmb/app.module.ts
  apps/api/general/src/app/pmb/app.service.ts
  apps/api/general/src/app/pmb/index.ts
  apps/api/general/src/main.ts
  apps/api/student/src/app/app.service.ts
  apps/api/user/src/app/app.controller.ts
  apps/api/user/src/app/app.service.ts
  libs/api/controllers/src/employee/index.ts
  libs/api/controllers/src/general/college.controller.ts
  libs/api/controllers/src/general/index.ts
  libs/api/controllers/src/general/personal.controller.ts
  libs/api/controllers/src/general/pmb.controller.ts
  libs/api/controllers/src/user/index.ts
  libs/api/dto/src/employee/index.ts
  libs/api/dto/src/general/college.dto.ts
  libs/api/dto/src/general/index.ts
  libs/api/dto/src/general/personal.dto.ts
  libs/api/dto/src/general/pmb.dto.ts
  libs/api/dto/src/index.ts
  libs/api/models/src/prisma/seed.ts
  libs/api/modules/src/general/index.ts
  libs/api/services/src/general/college.service.ts
  libs/api/services/src/general/index.ts
  libs/api/services/src/general/personal.service.ts
  libs/api/services/src/general/pmb.service.ts
  libs/api/services/src/index.ts
  libs/api/services/src/user/index.ts
  libs/entities/src/types/employee/employee.type.ts
  libs/entities/src/types/employee/index.ts
  libs/entities/src/types/employee/lecturer.type.ts
  libs/entities/src/types/employee/pagination/index.ts
  libs/entities/src/types/employee/tendik.type.ts
  libs/entities/src/types/general/college.type.ts
  libs/entities/src/types/general/index.ts
  libs/entities/src/types/general/personal.type.ts
  libs/entities/src/types/general/pmb.type.ts
  libs/entities/src/types/student/student.type.ts
  libs/entities/src/types/user/user.type.ts
Labels: improvement, BE

#1613 feature: slicing data pegawai modal data pendidikan & surat keterangan
  libs/web/components/src/molecules/inputs/index.ts
  libs/web/components/src/molecules/inputs/upload-field-V2/index.tsx
  libs/web/components/src/molecules/inputs/upload-field-V2/types.ts
  libs/web/components/src/molecules/inputs/upload-field/types.ts
  libs/web/modules/src/auth/forgot/api.ts
  libs/web/modules/src/auth/login/api.ts
  libs/web/modules/src/auth/logout/api.ts
  libs/web/modules/src/auth/reset/api.ts
  libs/web/modules/src/auth/verifikasi-forget/api.ts
  libs/web/modules/src/auth/verifikasi-otp/api.ts
  libs/web/modules/src/dashboard/pegawai/data-dosen/detail-dosen-content/data-diri/index.tsx
  libs/web/modules/src/dashboard/pegawai/data-dosen/detail-dosen-content/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/pegawai/data-dosen/detail-dosen-content/surat-keterangan/index.tsx
  libs/web/modules/src/dashboard/pegawai/data-dosen/detail-dosen-content/surat-keterangan/types.ts
  libs/web/modules/src/dashboard/pegawai/data-dosen/detail-dosen.tsx
  libs/web/modules/src/dashboard/pegawai/data-dosen/table.tsx
  libs/web/modules/src/dashboard/pegawai/homepage/cards.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/api.ts
Labels: enhancement, FE

#1620 improve: integrasi kartu pendaftaran pdf
  libs/web/modules/src/dashboard/user/registrasi/biodata/api.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/util.ts
  libs/web/services/src/degree-program/api.ts
  libs/web/services/src/degree-program/hooks.ts
  libs/web/services/src/degree-program/index.ts
  libs/web/services/src/department/api.ts
  libs/web/services/src/department/hooks.ts
  libs/web/services/src/department/index.ts
  libs/web/services/src/index.ts
  libs/web/services/src/registration-path/api.ts
  libs/web/services/src/registration-path/hooks.ts
  libs/web/services/src/registration-path/index.ts
  libs/web/services/src/scholarship/api.ts
  libs/web/services/src/scholarship/hooks.ts
  libs/web/services/src/scholarship/index.ts
  libs/web/services/src/selection-path/api.ts
  libs/web/services/src/selection-path/hooks.ts
  libs/web/services/src/selection-path/index.ts
Labels: improvement, FE

#1627 feature: notification
  apps/api/user/src/app/app.controller.ts
  apps/api/user/src/app/app.service.ts
  libs/api/controllers/src/user/index.ts
  libs/api/dto/src/user/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/api/services/src/user/index.ts
  libs/entities/src/types/user/index.ts
  libs/entities/src/types/user/notification.type.ts
  libs/entities/src/types/user/user.type.ts
Labels: enhancement, BE

#1626 feature: add endpoint get employee type, lecturer type, academic staf…
  apps/api/employee/src/app/app.controller.ts
  apps/api/employee/src/app/app.service.ts
  libs/api/controllers/src/employee/index.ts
  libs/api/dto/src/employee/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/api/services/src/employee/index.ts
  libs/entities/src/types/employee/employee.type.ts
  libs/entities/src/types/employee/lecturer.type.ts
  libs/entities/src/types/employee/tendik.type.ts
Labels: enhancement, BE
