Repository uninus-opensource/uninus-superapp, pull requests merged in 2023-07, with the labels that each got.

#119 bugfix: fix styling error for components
  apps/pmb/app/page.tsx
  apps/pmb/app/tuition-fee/page.tsx
  libs/components/src/atoms/button/index.tsx
  libs/components/src/molecules/footer/index.tsx
  libs/components/src/organisms/navbar/index.tsx
Labels: bug, global

#121 feature: forgot-password
  apps/pmb/app/login/forgot-password/page.tsx
  apps/pmb/app/login/page.tsx
Labels: enhancement

#125 feature: kirim verifikasi otp
  libs/controllers/src/auth/index.ts
  libs/entities/src/dto/auth-dto/index.ts
  libs/entities/src/dto/auth-dto/otp-dto.ts
  libs/modules/src/auth/index.ts
  libs/services/src/auth/index.ts
  package.json
  yarn.lock
Labels: enhancement

#127 Bugfix/otp page
  apps/pmb/app/login/otp/page.tsx
  apps/pmb/app/login/otp/type.ts
  libs/components/src/atoms/reveal/index.tsx
  libs/components/src/molecules/inputs/text/index.tsx
  libs/components/src/molecules/inputs/text/types.ts
  package.json
  yarn.lock
Labels: bug, enhancement

#128 bugfix: ubah lupa password -> lupa kata sandi
  apps/pmb/app/login/forgot-password/page.tsx
Labels: bug

#126 bugfix: Fix all bug about Auth
  libs/controllers/src/auth/index.ts
  libs/controllers/src/student/index.ts
  libs/controllers/src/user/index.ts
  libs/controllers/tsconfig.lib.json
  libs/entities/src/types/jwt.payload.ts
  libs/entities/src/types/login.ts
  libs/entities/src/types/register.ts
  libs/entities/tsconfig.lib.json
  libs/modules-fe/tsconfig.lib.json
  libs/modules/src/auth/index.ts
  libs/services/src/auth/index.ts
Labels: bug, enhancement

#133 Feature : create dragable component
  apps/pmb/app/page.tsx
  apps/pmb/app/tuition-fee/page.tsx
  libs/components/src/molecules/inputs/dragable/index.tsx
  libs/components/src/molecules/inputs/dragable/types.ts
  libs/components/src/molecules/inputs/index.ts
  libs/components/src/organisms/navbar/index.tsx
  package.json
  yarn.lock
Labels: global

#132 feature: add global utility custom color
  apps/pmb/tailwind.config.js
Labels: global

#135 improvement: pasang font montserrat
  apps/pmb/app/layout.tsx
  apps/pmb/app/page.tsx
Labels: enhancement

#139 Feature : Menambah Page Landing Page. Bug Fix : fix bug di komponen N…
  apps/pmb/app/about/page.tsx
  apps/pmb/app/page.tsx
  apps/pmb/app/testcomp/page.tsx
  apps/pmb/public/people1.png
  libs/components/src/atoms/reveal/index.tsx
  libs/components/src/atoms/reveal/type.ts
  libs/components/src/organisms/hero-banner/index.tsx
  libs/components/src/organisms/hero-banner/type.ts
  libs/components/src/organisms/index.ts
  libs/components/src/organisms/navbar/index.tsx
Labels: bug, enhancement, global

#149 Improvement/button variants
  apps/pmb/app/page.tsx
  apps/pmb/app/testcomp/page.tsx
  apps/pmb/tailwind.config.js
  libs/components/src/atoms/button/enums.ts
  libs/components/src/atoms/button/index.tsx
  libs/components/src/atoms/reveal/index.tsx
  libs/entities/src/dto/student-dto/update-student.dto.ts
  libs/entities/src/strategies/rt.strategy.ts
  package.json
  yarn.lock
Labels: bug, enhancement, global

#162 Improvement/global component/navbar
  apps/pmb/app/about/page.tsx
  apps/pmb/app/page.tsx
  apps/pmb/app/testcomp/page.tsx
  apps/pmb/tailwind.config.js
  libs/components/src/atoms/button/enums.ts
  libs/components/src/atoms/button/index.tsx
  libs/components/src/atoms/button/interface.ts
  libs/components/src/atoms/index.ts
  libs/components/src/molecules/sidebar/index.tsx
  libs/components/src/organisms/hero-banner/index.tsx
  libs/components/src/organisms/modal/index.tsx
  libs/components/src/organisms/navbar/index.tsx
Labels: bug, improvement

#169 improvement: slicing landing page
  apps/pmb/app/about/page.tsx
  apps/pmb/app/illustrations/DJI_0609-scaled 2.png
  apps/pmb/app/illustrations/foto-mahasiswa-bareng-2.jpg
  apps/pmb/app/illustrations/foto-mahasiswa-bareng.png
  apps/pmb/app/illustrations/gedung.png
  apps/pmb/app/illustrations/talent1.png
  apps/pmb/app/page.tsx
  apps/pmb/app/testcomp/page.tsx
  apps/pmb/app/type.ts
  apps/pmb/tailwind.config.js
  libs/components/src/atoms/button/index.tsx
  libs/components/src/atoms/illustrations/ellipse/index.tsx
  libs/components/src/atoms/illustrations/halfellipsegreen/index.tsx
  libs/components/src/atoms/illustrations/halfellipseyellow/index.tsx
  libs/components/src/atoms/illustrations/index.ts
  libs/components/src/atoms/illustrations/rectangle/index.tsx
  libs/components/src/atoms/illustrations/rectangle/type.ts
  libs/components/src/atoms/index.ts
  libs/components/src/organisms/card/index.tsx
  libs/components/src/organisms/card/type.ts
  libs/components/src/organisms/hero-banner/index.tsx
  libs/components/src/organisms/hero-banner/type.ts
  libs/components/src/organisms/index.ts
  libs/components/src/organisms/tab/index.tsx
  libs/components/src/organisms/tab/type.ts
Labels: improvement

#170 improvement: slicing landing page tab pindah otomatis
  libs/components/src/organisms/tab/index.tsx
Labels: improvement

#157 feature: accordions
  libs/components/src/organisms/accordion/index.tsx
  libs/components/src/organisms/accordion/type.ts
  libs/components/src/organisms/index.ts
Labels: enhancement, global

#172 Feature : Slicing Halaman Beasiswa
  apps/pmb/app/beasiswa/beasiswamitra/page.tsx
  apps/pmb/app/beasiswa/beasiswaprestasi/page.tsx
  apps/pmb/app/beasiswa/beasiswaunggul/page.tsx
  apps/pmb/app/beasiswa/page.tsx
  apps/pmb/app/illustrations/beasiswa2.svg
  apps/pmb/app/illustrations/beasiswa3.svg
  apps/pmb/app/illustrations/beasiswaunggul.svg
  apps/pmb/public/beasiswa2.svg
  apps/pmb/public/beasiswa3.svg
  apps/pmb/public/beasiswaunggul.svg
  apps/pmb/public/foto-mahasiswa-bareng-2.jpg
  libs/components/src/atoms/button/index.tsx
  libs/components/src/organisms/hero-banner/index.tsx
  libs/components/src/organisms/navbar/index.tsx
Labels: enhancement, global

#178 bugfix: landing page issues
  apps/pmb/app/page.tsx
  apps/pmb/tailwind.config.js
  libs/components/src/organisms/card/index.tsx
  libs/components/src/organisms/hero-banner/index.tsx
  libs/components/src/organisms/hero-banner/type.ts
Labels: bug

#188 improvement: add cloudinary student service
  libs/controllers/src/auth/index.ts
  libs/controllers/src/student/index.ts
  libs/controllers/src/user/index.ts
  libs/entities/src/dto/auth-dto/forgot-password-dto.ts
  libs/entities/src/dto/auth-dto/index.ts
  libs/entities/src/dto/auth-dto/login-dto.ts
  libs/entities/src/dto/auth-dto/logout-dto.ts
  libs/entities/src/dto/auth-dto/register-dto.ts
  libs/entities/src/dto/auth-dto/verify-dto.ts
  libs/entities/src/dto/index.ts
  libs/entities/src/dto/profile-dto/create-profile.dto.ts
  libs/entities/src/dto/profile-dto/index.ts
  libs/entities/src/dto/profile-dto/update-profiledto.ts
  libs/entities/src/dto/student-dto/create-student.dto.ts
  libs/entities/src/dto/student-dto/update-student.dto.ts
  libs/entities/src/strategies/at.strategy.ts
  libs/entities/src/strategies/rt.strategy.ts
  libs/entities/src/types/index.ts
  libs/entities/src/types/jwt.payload.ts
  libs/entities/src/types/login.ts
  libs/entities/src/types/token.ts
  libs/models/src/prisma/migrations/20230703000644_add_isverified/migration.sql
  libs/models/src/prisma/migrations/20230706231934_init_db/migration.sql
  libs/models/src/prisma/schema.prisma
  libs/modules/src/auth/index.ts
  libs/modules/src/email/index.ts
  libs/modules/src/pmb/index.ts
  libs/modules/src/student/index.ts
  libs/modules/src/user/index.ts
  libs/services/src/auth/index.ts
  libs/services/src/cloudinary/index.ts
  libs/services/src/student/index.ts
  libs/services/src/user/index.ts
Labels: enhancement

#193 Improvement:template-otp
  libs/entities/src/index.ts
  libs/entities/src/templates/email-message.ts
  libs/services/src/auth/index.ts
  libs/services/src/email/index.ts
Labels: improvement

#199 improvement: slicing biaya kuliah page
  apps/pmb/app/page.tsx
  apps/pmb/app/tuition-fee/page.tsx
  apps/pmb/app/tuition-fee/store.ts
  libs/components/src/organisms/hero-banner/index.tsx
  libs/components/src/organisms/hero-banner/type.ts
  libs/components/src/organisms/tab/index.tsx
Labels: improvement

#200 Improvement/navbar
  apps/pmb/app/tuition-fee/page.tsx
  apps/pmb/tailwind.config.js
  libs/components/src/molecules/sidebar/index.tsx
  libs/components/src/organisms/hero-banner/index.tsx
  libs/components/src/organisms/navbar/index.tsx
Labels: improvement

#203 improvement: add cms
  apps/cms/.editorconfig
  apps/cms/.env.example
  apps/cms/.gitignore
  apps/cms/README.md
  apps/cms/config/admin.ts
  apps/cms/config/api.ts
  apps/cms/config/database.ts
  apps/cms/config/middlewares.ts
  apps/cms/config/server.ts
  apps/cms/database/migrations/.gitkeep
  apps/cms/favicon.png
  apps/cms/package.json
  apps/cms/project.json
  apps/cms/public/robots.txt
  apps/cms/public/uploads/.gitkeep
  apps/cms/src/admin/app.example.tsx
  apps/cms/src/admin/tsconfig.json
  apps/cms/src/admin/webpack.config.example.js
  apps/cms/src/api/.gitkeep
  apps/cms/src/extensions/.gitkeep
  apps/cms/src/index.ts
  apps/cms/tsconfig.json
  apps/cms/yarn.lock
  package.json
  yarn.lock
Labels: enhancement

#205 Improvement/landing page 2
  apps/pmb/app/beasiswa/beasiswamitra/page.tsx
  apps/pmb/app/beasiswa/beasiswaprestasi/page.tsx
  apps/pmb/app/beasiswa/beasiswaunggul/page.tsx
  apps/pmb/app/beasiswa/page.tsx
  apps/pmb/app/illustrations/beasiswa2.svg
  apps/pmb/app/illustrations/beasiswa3.svg
  apps/pmb/app/illustrations/beasiswaunggul.svg
  apps/pmb/app/illustrations/foto-mahasiswa-bareng-2.jpg
  apps/pmb/app/illustrations/talent1.png
  apps/pmb/app/page.tsx
  apps/pmb/app/tuition-fee/page.tsx
  apps/pmb/public/illustrations/beasiswa2.svg
  apps/pmb/public/illustrations/beasiswa3.svg
  apps/pmb/public/illustrations/beasiswaunggul.svg
  apps/pmb/public/illustrations/foto-mahasiswa-bareng-2.jpg
  apps/pmb/public/illustrations/foto-mahasiswa-bareng.png
  apps/pmb/public/illustrations/gedung.png
  apps/pmb/public/illustrations/gerbang-uninus.png
  apps/pmb/public/illustrations/talent11.png
  apps/pmb/public/people1.png
  apps/pmb/public/uninus-logo.png
  libs/components/src/atoms/illustrations/halfellipsegreen/index.tsx
  libs/components/src/atoms/illustrations/halfellipseyellow/index.tsx
  libs/components/src/organisms/hero-banner/index.tsx
  libs/components/src/organisms/tab/index.tsx
  yarn.lock
Labels: improvement

#207 Improvement : responsive hero banner
  apps/pmb/app/beasiswa/page.tsx
  apps/pmb/app/page.tsx
  libs/components/src/organisms/hero-banner/index.tsx
  libs/components/src/organisms/tab/index.tsx
  yarn.lock
Labels: improvement

#210 improvement: slicing login page from ui ux
  apps/pmb/app/login/page.tsx
  apps/pmb/public/illustrations/hybrid-university.png
  apps/pmb/public/illustrations/neo-uninus-2.png
  apps/pmb/public/illustrations/nu-white.png
  apps/pmb/public/illustrations/talent-focus.png
  apps/pmb/tailwind.config.js
  libs/components/src/molecules/inputs/checkbox/index.tsx
  libs/components/src/molecules/inputs/text/index.tsx
  package.json
  yarn.lock
Labels: improvement

#209 feature: initial dashboard folder
  apps/pmb/app/about/page.tsx
  apps/pmb/app/beasiswa/page.tsx
  apps/pmb/app/dashboard/biodata/page.tsx
  apps/pmb/app/dashboard/page.tsx
  apps/pmb/app/dashboard/pendaftaran/page.tsx
  libs/components/src/atoms/reveal/index.tsx
  libs/components/src/atoms/reveal/type.ts
  libs/components/src/organisms/hero-banner/index.tsx
Labels: enhancement

#217 fix: layout
  apps/pmb/app/auth/layout.tsx
  apps/pmb/app/auth/login/page.tsx
  apps/pmb/app/auth/register/page.tsx
  apps/pmb/app/beasiswa/beasiswamitra/page.tsx
  apps/pmb/app/beasiswa/beasiswaprestasi/page.tsx
  apps/pmb/app/beasiswa/beasiswaunggul/page.tsx
  apps/pmb/app/beasiswa/page.tsx
  apps/pmb/app/dashboard/page.tsx
  apps/pmb/app/dashboard/pendaftaran/page.tsx
  apps/pmb/app/global.css
  apps/pmb/app/layout.tsx
  apps/pmb/app/login/forgot-password/page.tsx
  apps/pmb/app/login/otp/page.tsx
  apps/pmb/app/login/otp/type.ts
  apps/pmb/app/login/page.tsx
  apps/pmb/app/page.tsx
  apps/pmb/app/register/page.tsx
  apps/pmb/app/tuition-fee/page.tsx
  apps/pmb/app/tuition-fee/types.ts
  apps/pmb/public/illustrations/hybrid.svg
  apps/pmb/public/illustrations/kampus-merdeka.svg
  apps/pmb/public/illustrations/neo-uninus.svg
  libs/components/src/atoms/button/index.tsx
  libs/components/src/molecules/inputs/dragable/index.tsx
  libs/components/src/molecules/inputs/index.ts
  libs/components/src/molecules/inputs/text/index.tsx
  libs/components/src/molecules/inputs/upload-field/index.tsx
  libs/components/src/molecules/inputs/upload-field/types.ts
  libs/components/src/organisms/accordion/index.tsx
  libs/components/src/organisms/hero-banner/index.tsx
  libs/components/src/organisms/navbar/index.tsx
  libs/components/src/organisms/tab/index.tsx
  libs/entities/src/types/register.ts
  libs/modules-fe/src/auth/index.ts
  libs/modules-fe/src/auth/login/api.ts
  libs/modules-fe/src/auth/login/index.ts
  libs/modules-fe/src/auth/login/module.tsx
  libs/modules-fe/src/auth/login/next-auth.ts
  libs/modules-fe/src/auth/login/nextauth.d.ts
  libs/modules-fe/src/auth/login/schema.ts
  libs/modules-fe/src/auth/register/api.ts
  libs/modules-fe/src/auth/register/hook.ts
  libs/modules-fe/src/auth/register/index.ts
  libs/modules-fe/src/auth/register/module.tsx
  libs/modules-fe/src/auth/register/schema.ts
  libs/modules-fe/src/index.ts
  libs/modules-fe/src/layouts/dashboard.tsx
  libs/modules-fe/src/layouts/index.ts
  libs/modules-fe/src/layouts/main.tsx
  libs/modules-fe/src/login/index.ts
  libs/modules-fe/src/register/index.ts
  libs/modules-fe/src/tuition-fee/index.ts
  libs/modules-fe/src/tuition-fee/module.tsx
  libs/modules-fe/src/tuition-fee/store.ts
  libs/modules-fe/src/tuition-fee/types.ts
  package.json
  yarn.lock
Labels: bug

#219 Feature/dashboard page biodata
  apps/pmb/app/dashboard/biodata/page.tsx
  apps/pmb/app/dashboard/biodata/type.ts
  apps/pmb/public/illustrations/foto-cewe.png
  apps/pmb/tailwind.config.js
  libs/components/src/molecules/inputs/checkbox/index.tsx
  libs/components/src/molecules/inputs/radio/enum.ts
  libs/components/src/molecules/inputs/radio/index.tsx
  libs/components/src/molecules/inputs/radio/type.ts
  libs/components/src/molecules/inputs/select/index.tsx
  libs/components/src/molecules/inputs/select/types.ts
  libs/components/src/molecules/inputs/text/index.tsx
  libs/components/src/molecules/inputs/text/types.ts
Labels: enhancement

#220 Improvement/add avatar default
  libs/entities/src/dto/student-dto/create-student.dto.ts
  libs/entities/src/types/login.ts
  libs/services/src/auth/index.ts
  libs/services/src/student/index.ts
  libs/utilities/tsconfig.lib.json
Labels: enhancement

#223 feature : slicing dashboard home
  apps/pmb/app/dashboard/page.tsx
  apps/pmb/public/illustrations/tata_cara.png
  libs/modules-fe/src/layouts/dashboard.tsx
Labels: enhancement

#224 Improvement/update api docs for student
  libs/controllers/src/student/index.ts
  libs/entities/src/dto/student-dto/create-student.dto.ts
  libs/entities/src/dto/student-dto/update-student.dto.ts
  libs/entities/tsconfig.lib.json
  libs/services/src/student/index.ts
Labels: enhancement

#226 Feature : Add global Component dashboard Sidebar
  libs/components/src/atoms/illustrations/dummy/dummy-avatar.jpg
  libs/components/src/organisms/index.ts
  libs/components/src/organisms/sidebar/index.tsx
  libs/components/src/organisms/sidebar/type.ts
  libs/modules-fe/src/layouts/dashboard.tsx
Labels: enhancement, global

#227 improvement: add hook-form to select field
  apps/pmb/app/dashboard/biodata/page.tsx
  apps/pmb/app/dashboard/pendaftaran/page.tsx
  apps/pmb/app/testcomp/page.tsx
  libs/components/src/molecules/inputs/select/index.tsx
  libs/components/src/molecules/inputs/select/types.ts
Labels: improvement

#229 improvement: edit email templete
  libs/entities/src/templates/email-message.ts
Labels: enhancement

#222 improvement: slicing forgot,otp, dan reset page
  apps/pmb/app/auth/forgot-password/page.tsx
  apps/pmb/app/auth/otp/page.tsx
  apps/pmb/app/auth/reset-password/page.tsx
  libs/components/src/atoms/illustrations/kampusmerdeka/kampus-merdeka-white.png
  libs/components/src/atoms/illustrations/nuwhite/nu-white.png
  libs/components/src/atoms/illustrations/talentfocus/talent-focus.png
  libs/modules-fe/src/auth/forgot/index.ts
  libs/modules-fe/src/auth/forgot/module.tsx
  libs/modules-fe/src/auth/index.ts
  libs/modules-fe/src/auth/otp/index.ts
  libs/modules-fe/src/auth/otp/module.tsx
  libs/modules-fe/src/auth/otp/type.ts
  libs/modules-fe/src/auth/reset/index.ts
  libs/modules-fe/src/auth/reset/module.tsx
  yarn.lock
Labels: improvement

#232 Update Sidebar
  libs/components/src/organisms/sidebar/index.tsx
  libs/modules-fe/src/dashboard/module.tsx
  libs/modules-fe/src/layouts/dashboard.tsx
Labels: global, improvement

#235 bugfix: fix failed upload image
  libs/services/src/student/index.ts
Labels: bug

#241 feature: integrasi dashboard
  apps/pmb/app/testcomp/page.tsx
  libs/components/src/molecules/inputs/select/index.tsx
  libs/components/src/molecules/inputs/upload-field/index.tsx
  libs/components/src/molecules/inputs/upload-field/types.ts
  libs/components/src/organisms/sidebar/index.tsx
  libs/entities/src/types/biodata.ts
  libs/entities/src/types/index.ts
  libs/entities/tsconfig.lib.json
  libs/modules-fe/src/dashboard/biodata/api.ts
  libs/modules-fe/src/dashboard/biodata/hook.ts
  libs/modules-fe/src/dashboard/biodata/module.tsx
  libs/modules-fe/src/dashboard/biodata/type.ts
  libs/modules-fe/src/dashboard/module.tsx
Labels: enhancement

#244 Feature : integrasi otp verifikasi email
  apps/pmb/app/auth/verif-email/page.tsx
  libs/components/src/molecules/inputs/text/index.tsx
  libs/components/src/molecules/inputs/text/types.ts
  libs/modules-fe/src/auth/index.ts
  libs/modules-fe/src/auth/register/module.tsx
  libs/modules-fe/src/auth/verif-email/api.ts
  libs/modules-fe/src/auth/verif-email/hook.ts
  libs/modules-fe/src/auth/verif-email/index.ts
  libs/modules-fe/src/auth/verif-email/module.tsx
  libs/modules-fe/src/auth/verif-email/type.ts
  package.json
  yarn.lock
Labels: enhancement

#262 fix : fixing issue position text and variant on landing and scholarship
  libs/modules-fe/src/landing/module.tsx
  libs/modules-fe/src/scholarship/mitra/module.tsx
Labels: bug

#264 improvement: setup tailwind siakad
  apps/siakad/app/global.css
  apps/siakad/app/layout.tsx
  apps/siakad/app/page.tsx
  apps/siakad/postcss.config.js
  apps/siakad/tailwind.config.js
  package.json
Labels: enhancement, improvement

#265 improvement: responsive login/register
  .vscode/settings.json
  apps/pmb/app/auth/layout.tsx
  libs/modules-fe/src/auth/login/module.tsx
  libs/modules-fe/src/auth/register/module.tsx
Labels: improvement

#266 bugfix: auth layout
  apps/pmb/app/auth/otp/page.tsx
  libs/modules-fe/src/auth/forgot/module.tsx
  libs/modules-fe/src/auth/index.ts
  libs/modules-fe/src/auth/login/module.tsx
  libs/modules-fe/src/auth/otp/index.ts
  libs/modules-fe/src/auth/otp/module.tsx
  libs/modules-fe/src/auth/otp/type.ts
  libs/modules-fe/src/auth/reset/module.tsx
  libs/modules-fe/src/auth/verif-email/module.tsx
Labels: bug

#267 bugfix : rollback version prettier
  package.json
Labels: bug, dependencies

#268 Improvement : Setup tailwind di semua folder App
  apps/akreditasi/app/global.css
  apps/akreditasi/postcss.config.js
  apps/akreditasi/tailwind.config.js
  apps/evaluasi/app/global.css
  apps/evaluasi/postcss.config.js
  apps/evaluasi/tailwind.config.js
  apps/keuangan/app/global.css
  apps/keuangan/postcss.config.js
  apps/keuangan/tailwind.config.js
  apps/lms/app/global.css
  apps/lms/postcss.config.js
  apps/lms/tailwind.config.js
  apps/neo-feeder/app/global.css
  apps/neo-feeder/postcss.config.js
  apps/neo-feeder/tailwind.config.js
  apps/pegawai/app/global.css
  apps/pegawai/postcss.config.js
  apps/pegawai/tailwind.config.js
  apps/smart-dashboard/app/global.css
  apps/smart-dashboard/postcss.config.js
  apps/smart-dashboard/tailwind.config.js
  apps/tata-usaha/app/global.css
  apps/tata-usaha/postcss.config.js
  apps/tata-usaha/tailwind.config.js
  apps/tracer/app/global.css
  apps/tracer/postcss.config.js
  apps/tracer/tailwind.config.js
Labels: enhancement, improvement

#270 bugfix: responsive biaya kuliah page & hero banner
  apps/pmb/public/illustrations/foto-mahasiswa-bareng-reactangle.png
  libs/components/src/organisms/hero-banner/index.tsx
  libs/components/src/organisms/tab/index.tsx
  libs/modules-fe/src/landing/module.tsx
  libs/modules-fe/src/tuition-fee/module.tsx
Labels: bug, improvement

#271 Improvement : layout Box Otp menjadi responsive
  apps/pmb/app/auth/layout.tsx
  libs/modules-fe/src/auth/verif-email/module.tsx
Labels: improvement

#277 Bugfix/responsive biayakuliah page
  libs/components/src/atoms/loadings/spinner/index.tsx
  libs/modules-fe/src/tuition-fee/module.tsx
Labels: bug, enhancement, improvement

#279 initial setup web psu
  apps/psu/.eslintrc.json
  apps/psu/app/api/hello/route.ts
  apps/psu/app/global.css
  apps/psu/app/layout.tsx
  apps/psu/app/page.tsx
  apps/psu/index.d.ts
  apps/psu/jest.config.ts
  apps/psu/next-env.d.ts
  apps/psu/next.config.js
  apps/psu/postcss.config.js
  apps/psu/project.json
  apps/psu/public/.gitkeep
  apps/psu/public/favicon.ico
  apps/psu/tailwind.config.js
  apps/psu/tsconfig.json
  apps/psu/tsconfig.spec.json
Labels: documentation, dependencies

#278 improvement: integrasi benerin hook forgot password
  libs/modules-fe/src/auth/forgot/api.ts
  libs/modules-fe/src/auth/forgot/hook.ts
  libs/modules-fe/src/auth/forgot/index.ts
  libs/modules-fe/src/auth/forgot/module.tsx
  libs/modules-fe/src/auth/forgot/schema.ts
  libs/modules-fe/src/auth/forgot/type.ts
Labels: improvement

#291 improvement: integrasi reset password plus zod
  libs/modules-fe/src/auth/reset/api.ts
  libs/modules-fe/src/auth/reset/hook.ts
  libs/modules-fe/src/auth/reset/index.ts
  libs/modules-fe/src/auth/reset/module.tsx
  libs/modules-fe/src/auth/reset/schema.ts
  libs/modules-fe/src/auth/reset/type.ts
Labels: improvement

#292 Bugfix/loading handler pmb & runtime error removeChild
  apps/pmb/.env.example
  apps/pmb/app/auth/layout.tsx
  apps/pmb/tailwind.config.js
  libs/components/src/atoms/button/index.tsx
  libs/components/src/molecules/footer/index.tsx
  libs/components/src/molecules/sidebar/index.tsx
  libs/components/src/organisms/card/index.tsx
  libs/components/src/organisms/hero-banner/index.tsx
  libs/components/src/organisms/navbar/index.tsx
  libs/components/src/organisms/sidebar/index.tsx
  libs/components/src/organisms/tab/index.tsx
  libs/modules-fe/src/landing/module.tsx
  libs/modules-fe/src/layouts/main.tsx
  libs/modules-fe/src/scholarship/mitra/module.tsx
  libs/modules-fe/src/scholarship/module.tsx
  libs/modules-fe/src/scholarship/prestasi/module.tsx
  libs/modules-fe/src/scholarship/unggul/module.tsx
  libs/modules-fe/src/tuition-fee/module.tsx
Labels: bug, improvement

#323 Bugfix/responsive landing & selectfield
  apps/pmb/app/testcomp/page.tsx
  libs/components/src/molecules/inputs/select/index.tsx
  libs/components/src/molecules/inputs/select/types.ts
  libs/components/src/molecules/sidebar/index.tsx
  libs/components/src/organisms/hero-banner/index.tsx
  libs/modules-fe/src/landing/module.tsx
Labels: bug

#325 improvement: sidebar
  libs/components/src/atoms/button/index.tsx
  libs/components/src/atoms/button/interface.ts
  libs/components/src/organisms/sidebar/index.tsx
Labels: improvement

#324 improvement: resend otp and fix student endpoint
  apps/api/src/main.ts
  libs/controllers/src/auth/index.ts
  libs/entities/src/dto/auth-dto/index.ts
  libs/entities/src/dto/auth-dto/login-dto.ts
  libs/entities/src/dto/auth-dto/register-dto.ts
  libs/entities/src/dto/auth-dto/resend-otp-dto.ts
  libs/entities/src/dto/student-dto/create-student.dto.ts
  libs/entities/src/dto/student-dto/update-student.dto.ts
  libs/entities/src/enum/index.ts
  libs/entities/src/enum/student.ts
  libs/entities/src/templates/email-message.ts
  libs/entities/src/types/index.ts
  libs/entities/src/types/student.ts
  libs/models/src/prisma/migrations/20230715190417_add_otp/migration.sql
  libs/models/src/prisma/schema.prisma
  libs/services/src/auth/index.ts
  libs/services/src/student/index.ts
  libs/utilities/src/otp/index.ts
Labels: bug, enhancement

#330 Feature : Add feature logout
  libs/components/src/organisms/sidebar/index.tsx
  libs/components/src/organisms/sidebar/type.ts
  libs/modules-fe/src/auth/index.ts
  libs/modules-fe/src/auth/logout/api.ts
  libs/modules-fe/src/auth/logout/hook.ts
  libs/modules-fe/src/auth/logout/index.ts
  libs/modules-fe/src/auth/logout/types.ts
  libs/modules-fe/src/layouts/dashboard.tsx
Labels: enhancement

#332 fixing : issue ux writer
  apps/akreditasi/tailwind.config.js
  libs/components/src/organisms/sidebar/index.tsx
  libs/components/src/organisms/tab/index.tsx
  libs/modules-fe/src/dashboard/module.tsx
  libs/modules-fe/src/dashboard/pendaftaran/module.tsx
  libs/modules-fe/src/landing/module.tsx
  libs/modules-fe/src/layouts/dashboard.tsx
  libs/modules-fe/src/scholarship/mitra/module.tsx
  libs/modules-fe/src/scholarship/module.tsx
  libs/modules-fe/src/scholarship/prestasi/module.tsx
Labels: bug, improvement

#334 Improvement : add timer and request new otp
  apps/pmb/app/auth/verifikasi-otp/page.tsx
  libs/modules-fe/src/auth/index.ts
  libs/modules-fe/src/auth/register/module.tsx
  libs/modules-fe/src/auth/verif-email/api.ts
  libs/modules-fe/src/auth/verif-email/hook.ts
  libs/modules-fe/src/auth/verifikasi-otp/api.ts
  libs/modules-fe/src/auth/verifikasi-otp/hook.ts
  libs/modules-fe/src/auth/verifikasi-otp/index.ts
  libs/modules-fe/src/auth/verifikasi-otp/module.tsx
  libs/modules-fe/src/auth/verifikasi-otp/type.ts
Labels: improvement

#335 improvement: initial accordions setup dashboard
  apps/pmb/app/testcomp/page.tsx
  libs/components/src/organisms/accordion/index.tsx
  libs/components/src/organisms/accordion/type.ts
  libs/modules-fe/src/dashboard/biodata/module.tsx
  libs/modules-fe/src/dashboard/biodata/type.ts
Labels: improvement

#347 Fix : Layout Dashboard and Sidebar
  apps/pmb/tailwind.config.js
  libs/components/src/organisms/sidebar/index.tsx
  libs/modules-fe/src/dashboard/module.tsx
  libs/modules-fe/src/dashboard/pendaftaran/module.tsx
  libs/modules-fe/src/layouts/dashboard.tsx
Labels: bug, improvement

#336 improvement: get data student dashboard
  apps/pmb/app/auth/layout.tsx
  apps/pmb/app/loading.tsx
  libs/components/src/atoms/button/index.tsx
  libs/components/src/atoms/loadings/spinner/index.tsx
  libs/components/src/atoms/loadings/spinner/type.ts
  libs/components/src/molecules/inputs/radio/index.tsx
  libs/components/src/molecules/inputs/radio/type.ts
  libs/components/src/molecules/inputs/select/types.ts
  libs/entities/src/index.ts
  libs/entities/src/interfaces/biodata.ts
  libs/entities/src/interfaces/index.ts
  libs/entities/src/types/biodata.ts
  libs/modules-fe/src/auth/login/module.tsx
  libs/modules-fe/src/dashboard/biodata/api.ts
  libs/modules-fe/src/dashboard/biodata/hook.ts
  libs/modules-fe/src/dashboard/biodata/module.tsx
  libs/modules-fe/src/dashboard/biodata/store.ts
  libs/modules-fe/src/dashboard/pendaftaran/module.tsx
Labels: bug, improvement

#348 Fix : Upload File and Implement to avatar biodata
  apps/pmb/app/testcomp/page.tsx
  libs/components/src/molecules/inputs/radio/index.tsx
  libs/components/src/molecules/inputs/radio/types.ts
  libs/components/src/molecules/inputs/upload-field/index.tsx
  libs/components/src/molecules/inputs/upload-field/types.ts
  libs/components/src/organisms/sidebar/index.tsx
  libs/modules-fe/src/dashboard/biodata/module.tsx
Labels: bug, improvement

#360 improvement: slicing home page dashboard
  apps/pmb/public/illustrations/dashboard-home.png
  apps/pmb/tailwind.config.js
  libs/components/src/organisms/sidebar/index.tsx
  libs/modules-fe/src/dashboard/module.tsx
  libs/modules-fe/src/layouts/dashboard.tsx
Labels: improvement

#365 improvement: layout pendaftaran, improve integrasi forgot, fix accordion
  apps/pmb/app/auth/layout.tsx
  apps/pmb/app/testcomp/page.tsx
  libs/components/src/organisms/accordion/index.tsx
  libs/components/src/organisms/modal/index.tsx
  libs/modules-fe/src/auth/forgot/hook.ts
  libs/modules-fe/src/auth/forgot/module.tsx
  libs/modules-fe/src/dashboard/biodata/module.tsx
Labels: bug, improvement

#367 bugfix : handle error verify otp
  libs/services/src/auth/index.ts
  libs/services/src/user/index.ts
  libs/utilities/src/otp/index.ts
Labels: bug

#369 Fix : Radio button tidak aktif
  libs/components/src/molecules/inputs/radio/index.tsx
  libs/entities/src/types/biodata.ts
  libs/modules-fe/src/dashboard/biodata/module.tsx
Labels: bug

#375 improvement: responsive dashboard and bugfix styling
  libs/components/src/molecules/inputs/upload-field/index.tsx
  libs/components/src/molecules/inputs/upload-field/types.ts
  libs/components/src/organisms/sidebar/index.tsx
  libs/entities/src/types/biodata.ts
  libs/modules-fe/src/dashboard/biodata/module.tsx
  libs/modules-fe/src/layouts/dashboard.tsx
  libs/modules-fe/src/tuition-fee/module.tsx
Labels: bug, improvement

#386 feature: modal-onLogout
  apps/pmb/app/testcomp/page.tsx
  libs/components/src/atoms/button/index.tsx
  libs/components/src/atoms/button/interface.ts
  libs/components/src/atoms/illustrations/logOut/logOut.png
  libs/components/src/organisms/modal/index.tsx
  libs/components/src/organisms/modal/interface.ts
  libs/components/src/organisms/sidebar/index.tsx
Labels: enhancement

#388 Fix : UX writting di halaman dashboard/pendaftaran, footer,dan beasiswa
  libs/components/src/molecules/footer/index.tsx
  libs/components/src/organisms/navbar/index.tsx
  libs/components/src/organisms/sidebar/index.tsx
  libs/modules-fe/src/auth/login/module.tsx
  libs/modules-fe/src/auth/register/module.tsx
  libs/modules-fe/src/dashboard/module.tsx
  libs/modules-fe/src/dashboard/pendaftaran/module.tsx
  libs/modules-fe/src/scholarship/mitra/module.tsx
  libs/modules-fe/src/scholarship/prestasi/module.tsx
Labels: improvement

#392 improvement: validasi nik dan email register
  libs/modules-fe/src/auth/forgot/module.tsx
  libs/modules-fe/src/auth/register/module.tsx
Labels: improvement

#391 Improvement : impove structur folder landing and create responsive carousel card for section benefit
  apps/pmb/app/loading.tsx
  libs/components/src/organisms/card/index.tsx
  libs/modules-fe/src/landing/banner-wellcome/index.ts
  libs/modules-fe/src/landing/banner-wellcome/section.tsx
  libs/modules-fe/src/landing/benefit/index.ts
  libs/modules-fe/src/landing/benefit/section.tsx
  libs/modules-fe/src/landing/benefit/type.ts
  libs/modules-fe/src/landing/detail/index.ts
  libs/modules-fe/src/landing/detail/section.tsx
  libs/modules-fe/src/landing/hero/index.ts
  libs/modules-fe/src/landing/hero/section.tsx
  libs/modules-fe/src/landing/index.ts
  libs/modules-fe/src/landing/module.tsx
  libs/modules-fe/src/landing/program-study/index.ts
  libs/modules-fe/src/landing/program-study/section.tsx
  libs/modules-fe/src/landing/program-study/type.ts
  libs/modules-fe/src/landing/selection/index.ts
  libs/modules-fe/src/landing/selection/section.tsx
  package.json
  yarn.lock
Labels: improvement

#393 Improvement/modal on logout
  libs/components/src/atoms/button/index.tsx
  libs/components/src/atoms/button/interface.ts
  libs/components/src/organisms/modal/index.tsx
  libs/components/src/organisms/modal/interface.ts
  libs/components/src/organisms/sidebar/index.tsx
Labels: improvement

#394 Improvement/modal on logout
  libs/components/src/organisms/modal/index.tsx
  libs/components/src/organisms/sidebar/index.tsx
Labels: improvement

#390 improvement & bugfix: add lazy loading & dashboard
  apps/pmb/app/loading.tsx
  apps/pmb/tailwind.config.js
  libs/components/src/atoms/loadings/index.ts
  libs/components/src/atoms/loadings/lazyloading/index.tsx
  libs/components/src/organisms/card/index.tsx
  libs/components/src/organisms/card/type.ts
  libs/components/src/organisms/hero-banner/index.tsx
  libs/components/src/organisms/sidebar/index.tsx
  libs/entities/src/types/biodata.ts
  libs/modules-fe/src/dashboard/biodata/api.ts
  libs/modules-fe/src/dashboard/biodata/hooks.ts
  libs/modules-fe/src/dashboard/biodata/module.tsx
  libs/modules-fe/src/dashboard/biodata/store.ts
  libs/modules-fe/src/dashboard/biodata/type.ts
  libs/modules-fe/src/landing/banner-welcome/index.ts
  libs/modules-fe/src/landing/banner-welcome/section.tsx
  libs/modules-fe/src/landing/benefit/section.tsx
  libs/modules-fe/src/landing/module.tsx
  libs/modules-fe/src/landing/program-study/section.tsx
  libs/modules-fe/src/layouts/dashboard.tsx
  libs/modules-fe/src/layouts/dashboardcontent.tsx
  libs/modules-fe/src/scholarship/mitra/module.tsx
  libs/modules-fe/src/scholarship/module.tsx
  libs/modules-fe/src/scholarship/prestasi/module.tsx
  libs/modules-fe/src/scholarship/unggul/module.tsx
  libs/modules-fe/src/tuition-fee/module.tsx
  package.json
  yarn.lock
Labels: bug, improvement

#402 bugfix: no telp di footer udh di update sama improve navbar
  libs/components/src/molecules/footer/index.tsx
  libs/components/src/organisms/navbar/index.tsx
Labels: bug

#421 Improvement/sidebar button menu mobile validasi email reset
  libs/components/src/organisms/sidebar/index.tsx
  libs/modules-fe/src/auth/reset/module.tsx
  libs/modules-fe/src/auth/reset/schema.ts
Labels: improvement

#423 feature: add tailwindCSS to PMB admin & set script pmb-admin
  apps/pmb-admin/app/global.css
  apps/pmb-admin/app/layout.tsx
  apps/pmb-admin/app/page.tsx
  apps/pmb-admin/postcss.config.js
  apps/pmb-admin/tailwind.config.js
  package.json
Labels: enhancement

#426 Feature : Component Select Field Controller
  apps/pmb/app/testcomp/page.tsx
  libs/components/src/molecules/inputs/index.ts
  libs/components/src/molecules/inputs/select-contoller/index.tsx
  libs/components/src/molecules/inputs/select-contoller/intersectionObserverUtils.ts
  libs/components/src/molecules/inputs/select-contoller/types.ts
  package.json
  yarn.lock
Labels: improvement

#425 feature: add secure page to dashboard
  apps/pmb/app/auth/layout.tsx
  libs/modules-fe/src/dashboard/module.tsx
  libs/modules-fe/src/layouts/dashboard.tsx
  libs/modules-fe/src/layouts/main.tsx
Labels: enhancement

#428 Fix : Responsive auth layout
  apps/pmb/app/auth/layout.tsx
  libs/components/src/molecules/inputs/text/index.tsx
  libs/entities/src/types/register.ts
  libs/modules-fe/src/auth/login/module.tsx
  libs/modules-fe/src/auth/register/module.tsx
  libs/modules-fe/src/auth/register/schema.ts
Labels: bug

#430 bugfix:halaman-datadiri
  libs/components/src/organisms/sidebar/index.tsx
Labels: bug

#424 feature: add endpoint verify otp password
  libs/controllers/src/auth/index.ts
  libs/services/src/auth/index.ts
Labels: enhancement

#429 Fix/format image/webp
  apps/pmb/app/auth/layout.tsx
  apps/pmb/public/illustrations/User.png
  apps/pmb/public/illustrations/User.webp
  apps/pmb/public/illustrations/beasiswa2.svg
  apps/pmb/public/illustrations/beasiswa2.webp
  apps/pmb/public/illustrations/beasiswa3.svg
  apps/pmb/public/illustrations/beasiswa3.webp
  apps/pmb/public/illustrations/beasiswaunggul.svg
  apps/pmb/public/illustrations/beasiswaunggul.webp
  apps/pmb/public/illustrations/dashboard-home.png
  apps/pmb/public/illustrations/dashboard-home.webp
  apps/pmb/public/illustrations/dummy-avatar.jpg
  apps/pmb/public/illustrations/dummy-avatar.webp
  apps/pmb/public/illustrations/foto-cewe.png
  apps/pmb/public/illustrations/foto-cewe.webp
  apps/pmb/public/illustrations/foto-mahasiswa-bareng-2.jpg
  apps/pmb/public/illustrations/foto-mahasiswa-bareng-2.webp
  apps/pmb/public/illustrations/foto-mahasiswa-bareng-reactangle.png
  apps/pmb/public/illustrations/foto-mahasiswa-bareng-reactangle.webp
  apps/pmb/public/illustrations/foto-mahasiswa-bareng.png
  apps/pmb/public/illustrations/foto-mahasiswa-bareng.webp
  apps/pmb/public/illustrations/gedung.png
  apps/pmb/public/illustrations/gedung.webp
  apps/pmb/public/illustrations/gerbang-uninus.png
  apps/pmb/public/illustrations/gerbang-uninus.webp
  apps/pmb/public/illustrations/hybrid-university.png
  apps/pmb/public/illustrations/hybrid-university.webp
  apps/pmb/public/illustrations/neo-uninus-2.png
  apps/pmb/public/illustrations/neo-uninus-2.webp
  apps/pmb/public/illustrations/nu-white.png
  apps/pmb/public/illustrations/nu-white.webp
  apps/pmb/public/illustrations/talent-focus.png
  apps/pmb/public/illustrations/talent-focus.webp
  apps/pmb/public/illustrations/talent11.png
  apps/pmb/public/illustrations/talent11.webp
  apps/pmb/public/illustrations/tata_cara.png
  apps/pmb/public/illustrations/tata_cara.webp
  libs/components/src/atoms/illustrations/dummy/dummy-avatar.jpg
  libs/components/src/atoms/illustrations/talentfocus/talent-focus.png
  libs/components/src/organisms/sidebar/index.tsx
  libs/modules-fe/src/dashboard/biodata/module.tsx
  libs/modules-fe/src/dashboard/module.tsx
  libs/modules-fe/src/landing/banner-welcome/section.tsx
  libs/modules-fe/src/landing/detail/section.tsx
  libs/modules-fe/src/landing/hero/section.tsx
  libs/modules-fe/src/landing/selection/section.tsx
  libs/modules-fe/src/scholarship/mitra/module.tsx
  libs/modules-fe/src/scholarship/module.tsx
  libs/modules-fe/src/scholarship/prestasi/module.tsx
  libs/modules-fe/src/scholarship/unggul/module.tsx
  libs/modules-fe/src/tuition-fee/module.tsx
Labels: bug, improvement

#437 improvement: update schema pmb, auth service and student service
  libs/entities/src/dto/auth-dto/register-dto.ts
  libs/entities/src/dto/student-dto/create-student.dto.ts
  libs/entities/src/types/login.ts
  libs/entities/src/types/register.ts
  libs/entities/src/types/req-user.ts
  libs/models/src/prisma/migrations/20230724034915_/migration.sql
  libs/models/src/prisma/migrations/20230724045341_/migration.sql
  libs/models/src/prisma/migrations/20230724083816_/migration.sql
  libs/models/src/prisma/migrations/20230724084306_/migration.sql
  libs/models/src/prisma/migrations/20230724091109_/migration.sql
  libs/models/src/prisma/migrations/20230724131051_/migration.sql
  libs/models/src/prisma/schema.prisma
  libs/services/src/auth/index.ts
  libs/services/src/user/index.ts
Labels: improvement

#435 Improvement : slicing pembayaran registrasi page pendaftaran
  libs/components/src/molecules/inputs/dragable/index.tsx
  libs/components/src/molecules/inputs/dragable/types.ts
  libs/components/src/organisms/sidebar/index.tsx
  libs/modules-fe/src/dashboard/pendaftaran/module.tsx
Labels: improvement

#436 feature : add metadata
  apps/pmb/app/auth/forgot-password/page.tsx
  apps/pmb/app/auth/login/page.tsx
  apps/pmb/app/auth/register/page.tsx
  apps/pmb/app/auth/reset-password/page.tsx
  apps/pmb/app/auth/verifikasi-otp/page.tsx
  apps/pmb/app/beasiswa/beasiswamitra/page.tsx
  apps/pmb/app/beasiswa/beasiswaprestasi/page.tsx
  apps/pmb/app/beasiswa/beasiswaunggul/page.tsx
  apps/pmb/app/beasiswa/page.tsx
  apps/pmb/app/biaya-kuliah/page.tsx
  apps/pmb/app/dashboard/biodata/page.tsx
  apps/pmb/app/dashboard/page.tsx
  apps/pmb/app/dashboard/pendaftaran/page.tsx
  apps/pmb/app/page.tsx
Labels: enhancement, improvement

#439 improvement: Update validation using Zod
  apps/api/src/main.ts
  libs/controllers/src/auth/index.ts
  libs/controllers/src/student/index.ts
  libs/controllers/src/user/index.ts
  libs/entities/src/dto/auth-dto/forgot-password-dto.ts
  libs/entities/src/dto/auth-dto/login-dto.ts
  libs/entities/src/dto/auth-dto/logout-dto.ts
  libs/entities/src/dto/auth-dto/register-dto.ts
  libs/entities/src/dto/auth-dto/req-user.dto.ts
  libs/entities/src/dto/auth-dto/resend-otp-dto.ts
  libs/entities/src/dto/auth-dto/reset-password-dto.ts
  libs/entities/src/dto/auth-dto/verify-dto.ts
  libs/entities/src/dto/student-dto/create-student.dto.ts
  libs/entities/src/dto/student-dto/update-student.dto.ts
  libs/entities/src/dto/user-dto/create-user.dto.ts
  libs/entities/src/dto/user-dto/update-user.dto.ts
  libs/entities/src/index.ts
  libs/entities/src/zod/index.ts
  libs/entities/src/zod/zod-validation-pipe.ts
  package.json
  yarn.lock
Labels: enhancement, improvement

#438 feature : slicing document upload field dashboard pmb
  apps/pmb/app/dashboard/dokumen/page.tsx
  libs/components/src/molecules/inputs/upload-field/index.tsx
  libs/components/src/molecules/inputs/upload-field/types.ts
  libs/components/src/organisms/sidebar/index.tsx
  libs/modules-fe/src/dashboard/biodata/module.tsx
  libs/modules-fe/src/dashboard/dokumen/index.ts
  libs/modules-fe/src/dashboard/dokumen/module.tsx
  libs/modules-fe/src/dashboard/index.ts
Labels: enhancement

#445 Bugfix/fix zod error
  libs/entities/src/dto/auth-dto/register-dto.ts
  libs/entities/src/dto/student-dto/create-student.dto.ts
  libs/entities/src/dto/student-dto/update-student.dto.ts
Labels: bug, enhancement

#447 Improvement/improve biodata
  libs/entities/src/types/biodata.ts
  libs/modules-fe/src/dashboard/biodata/module.tsx
  libs/modules-fe/src/dashboard/biodata/store.ts
  libs/modules-fe/src/dashboard/biodata/type.ts
Labels: improvement

#453 improvement: add location schema
  libs/models/src/prisma/migrations/20230715190417_add_otp/migration.sql
  libs/models/src/prisma/migrations/20230724034915_/migration.sql
  libs/models/src/prisma/migrations/20230724045341_/migration.sql
  libs/models/src/prisma/migrations/20230724083816_/migration.sql
  libs/models/src/prisma/migrations/20230724084306_/migration.sql
  libs/models/src/prisma/migrations/20230724091109_/migration.sql
  libs/models/src/prisma/migrations/20230724131051_/migration.sql
  libs/models/src/prisma/migrations/20230725044541_updateschema/migration.sql
  libs/models/src/prisma/migrations/20230725130458_initial_db/migration.sql
  libs/models/src/prisma/schema.prisma
Labels: enhancement

#462 improve : Handle error ketika password atau email salah
  libs/modules-fe/src/auth/login/module.tsx
  package.json
  yarn.lock
Labels: improvement

#468 bugfix: redirect detail uninus
  libs/modules-fe/src/landing/detail/section.tsx
  libs/modules-fe/src/tuition-fee/module.tsx
Labels: bug

#460 improvement: rename dto to schema and enhancement zod validation
  libs/controllers/src/auth/index.ts
  libs/controllers/src/student/index.ts
  libs/controllers/src/user/index.ts
  libs/controllers/tsconfig.lib.json
  libs/entities/src/dto/auth-dto/index.ts
  libs/entities/src/dto/index.ts
  libs/entities/src/dto/student-dto/index.ts
  libs/entities/src/dto/user-dto/index.ts
  libs/entities/src/index.ts
  libs/entities/src/schemas/auth-schemas/forgotPassword-schema.ts
  libs/entities/src/schemas/auth-schemas/index.ts
  libs/entities/src/schemas/auth-schemas/login-schema.ts
  libs/entities/src/schemas/auth-schemas/logout-schema.ts
  libs/entities/src/schemas/auth-schemas/register-schema.ts
  libs/entities/src/schemas/auth-schemas/req-user-schema.ts
  libs/entities/src/schemas/auth-schemas/resend-otp-schema.ts
  libs/entities/src/schemas/auth-schemas/reset-password-schema.ts
  libs/entities/src/schemas/auth-schemas/verify-schema.ts
  libs/entities/src/schemas/index.ts
  libs/entities/src/schemas/student-schemas/create-student.schema.ts
  libs/entities/src/schemas/student-schemas/index.ts
  libs/entities/src/schemas/student-schemas/update-student.schema.ts
  libs/entities/src/schemas/user-schemas/create-user-schema.ts
  libs/entities/src/schemas/user-schemas/index.ts
  libs/entities/src/schemas/user-schemas/update-user-schema.ts
Labels: enhancement, improvement

#471 improvement:responsive-datadiri
  libs/entities/src/types/biodata.ts
  libs/modules-fe/src/dashboard/biodata/module.tsx
  libs/modules-fe/src/dashboard/biodata/store.ts
Labels: improvement

#472 Feature : add page verify password
  apps/pmb-admin/app/layout.tsx
  apps/pmb/app/auth/verifikasi-forget/page.tsx
  libs/modules-fe/src/auth/forgot/module.tsx
  libs/modules-fe/src/auth/index.ts
  libs/modules-fe/src/auth/verifikasi-forget/api.ts
  libs/modules-fe/src/auth/verifikasi-forget/hook.ts
  libs/modules-fe/src/auth/verifikasi-forget/index.ts
  libs/modules-fe/src/auth/verifikasi-forget/module.tsx
  libs/modules-fe/src/auth/verifikasi-forget/type.ts
Labels: improvement

#474 bugfix: strict admin dashboard & wording biaya kuliah
  apps/pmb-admin-e2e/.eslintrc.json
  apps/pmb-admin-e2e/cypress.config.ts
  apps/pmb-admin-e2e/project.json
  apps/pmb-admin-e2e/src/e2e/app.cy.ts
  apps/pmb-admin-e2e/src/fixtures/example.json
  apps/pmb-admin-e2e/src/support/app.po.ts
  apps/pmb-admin-e2e/src/support/commands.ts
  apps/pmb-admin-e2e/src/support/e2e.ts
  apps/pmb-admin-e2e/tsconfig.json
  libs/modules-fe/src/layouts/auth.tsx
  libs/modules-fe/src/layouts/dashboardAdmin.tsx
  libs/modules-fe/src/layouts/main.tsx
  libs/modules-fe/src/tuition-fee/module.tsx
Labels: bug, improvement, FE

#470 feature: add crud endpoint for location
  libs/controllers/src/index.ts
  libs/controllers/src/location/index.ts
  libs/entities/src/schemas/student-schemas/update-student.schema.ts
  libs/master-api/src/index.ts
  libs/models/src/prisma/migrations/20230727030650_/migration.sql
  libs/models/src/prisma/schema.prisma
  libs/modules/src/index.ts
  libs/modules/src/location/index.ts
  libs/services/src/auth/index.ts
  libs/services/src/index.ts
  libs/services/src/location/index.ts
Labels: enhancement

#473 Improvement/added exp response and exp validation
  libs/entities/src/types/login.ts
  libs/services/src/auth/index.ts
Labels: enhancement, improvement

#476 Improvement/refoldering zod and swagger
  libs/controllers/src/auth/index.ts
  libs/controllers/src/student/index.ts
  libs/controllers/src/user/index.ts
  libs/entities/src/schemas/auth-schemas/forgot-password/index.ts
  libs/entities/src/schemas/auth-schemas/login/index.ts
  libs/entities/src/schemas/auth-schemas/logout/index.ts
  libs/entities/src/schemas/auth-schemas/register/index.ts
  libs/entities/src/schemas/auth-schemas/req-user/index.ts
  libs/entities/src/schemas/auth-schemas/resend-otp/index.ts
  libs/entities/src/schemas/auth-schemas/reset-password/index.ts
  libs/entities/src/schemas/auth-schemas/verify/index.ts
  libs/entities/src/schemas/student-schemas/create-student/index.ts
  libs/entities/src/schemas/student-schemas/update-student/index.ts
  libs/entities/src/schemas/user-schemas/create-user/index.ts
  libs/entities/src/schemas/user-schemas/update-user/index.ts
  libs/services/src/index.ts
  libs/services/src/swagger/auth-swagger/forgot-password/index.swagger.ts
  libs/services/src/swagger/auth-swagger/forgot-password/index.ts
  libs/services/src/swagger/auth-swagger/index.ts
  libs/services/src/swagger/auth-swagger/login/index.swagger.ts
  libs/services/src/swagger/auth-swagger/login/index.ts
  libs/services/src/swagger/auth-swagger/logout/index.swagger.ts
  libs/services/src/swagger/auth-swagger/logout/index.ts
  libs/services/src/swagger/auth-swagger/register/index.swagger.ts
  libs/services/src/swagger/auth-swagger/register/index.ts
  libs/services/src/swagger/auth-swagger/req-user/index.swagger.ts
  libs/services/src/swagger/auth-swagger/req-user/index.ts
  libs/services/src/swagger/auth-swagger/resend-otp/index.swagger.ts
  libs/services/src/swagger/auth-swagger/resend-otp/index.ts
  libs/services/src/swagger/auth-swagger/reset-password/index.swagger.ts
  libs/services/src/swagger/auth-swagger/reset-password/index.ts
  libs/services/src/swagger/auth-swagger/verify/index.swagger.ts
  libs/services/src/swagger/auth-swagger/verify/index.ts
  libs/services/src/swagger/index.ts
  libs/services/src/swagger/student-swagger/create-student/index.swagger.ts
  libs/services/src/swagger/student-swagger/create-student/index.ts
  libs/services/src/swagger/student-swagger/index.ts
  libs/services/src/swagger/student-swagger/update-student/index.swagger.ts
  libs/services/src/swagger/student-swagger/update-student/index.ts
  libs/services/src/swagger/user-swagger/create-user/index.swagger.ts
  libs/services/src/swagger/user-swagger/create-user/index.ts
  libs/services/src/swagger/user-swagger/index.ts
  libs/services/src/swagger/user-swagger/update-user/index.swagger.ts
  libs/services/src/swagger/user-swagger/update-user/index.ts
Labels: bug, enhancement

#477 Improvement : add feature search on tuition fee page
  libs/components/src/molecules/inputs/search/ic-search.tsx
  libs/components/src/molecules/inputs/search/index.tsx
  libs/components/src/molecules/inputs/search/types.ts
  libs/modules-fe/src/tuition-fee/module.tsx
  package.json
  yarn.lock
Labels: bug, improvement, UAT, FE

#478 Improvement/responsive datadiri
  libs/entities/src/types/biodata.ts
  libs/modules-fe/src/dashboard/biodata/module.tsx
  libs/modules-fe/src/dashboard/biodata/store.ts
Labels: improvement

#484 improvement: rename file zod and swagger
  libs/entities/src/schemas/auth-schemas/forgot-password/index.schema.ts
  libs/entities/src/schemas/auth-schemas/forgot-password/index.ts
  libs/entities/src/schemas/auth-schemas/login/index.schema.ts
  libs/entities/src/schemas/auth-schemas/login/index.ts
  libs/entities/src/schemas/auth-schemas/logout/index.schema.ts
  libs/entities/src/schemas/auth-schemas/logout/index.ts
  libs/entities/src/schemas/auth-schemas/register/index.schema.ts
  libs/entities/src/schemas/auth-schemas/register/index.ts
  libs/entities/src/schemas/auth-schemas/req-user/index.schema.ts
  libs/entities/src/schemas/auth-schemas/req-user/index.ts
  libs/entities/src/schemas/auth-schemas/resend-otp/index.schema.ts
  libs/entities/src/schemas/auth-schemas/resend-otp/index.ts
  libs/entities/src/schemas/auth-schemas/reset-password/index.schema.ts
  libs/entities/src/schemas/auth-schemas/reset-password/index.ts
  libs/entities/src/schemas/auth-schemas/verify/index.schema.ts
  libs/entities/src/schemas/auth-schemas/verify/index.ts
  libs/entities/src/schemas/student-schemas/create-student/index.schema.ts
  libs/entities/src/schemas/student-schemas/create-student/index.ts
  libs/entities/src/schemas/student-schemas/update-student/index.schema.ts
  libs/entities/src/schemas/student-schemas/update-student/index.ts
  libs/entities/src/schemas/user-schemas/create-user/index.schema.ts
  libs/entities/src/schemas/user-schemas/create-user/index.ts
  libs/entities/src/schemas/user-schemas/update-user/index.schema.ts
  libs/entities/src/schemas/user-schemas/update-user/index.ts
  libs/services/src/swagger/auth-swagger/forgot-password/index.swagger.ts
  libs/services/src/swagger/auth-swagger/forgot-password/index.ts
  libs/services/src/swagger/auth-swagger/login/index.swagger.ts
  libs/services/src/swagger/auth-swagger/login/index.ts
  libs/services/src/swagger/auth-swagger/logout/index.swagger.ts
  libs/services/src/swagger/auth-swagger/logout/index.ts
  libs/services/src/swagger/auth-swagger/register/index.swagger.ts
  libs/services/src/swagger/auth-swagger/register/index.ts
  libs/services/src/swagger/auth-swagger/req-user/index.swagger.ts
  libs/services/src/swagger/auth-swagger/req-user/index.ts
  libs/services/src/swagger/auth-swagger/resend-otp/index.swagger.ts
  libs/services/src/swagger/auth-swagger/resend-otp/index.ts
  libs/services/src/swagger/auth-swagger/reset-password/index.swagger.ts
  libs/services/src/swagger/auth-swagger/reset-password/index.ts
  libs/services/src/swagger/auth-swagger/verify/index.swagger.ts
  libs/services/src/swagger/auth-swagger/verify/index.ts
  libs/services/src/swagger/student-swagger/create-student/index.swagger.ts
  libs/services/src/swagger/student-swagger/create-student/index.ts
  libs/services/src/swagger/student-swagger/update-student/index.swagger.ts
  libs/services/src/swagger/student-swagger/update-student/index.ts
  libs/services/src/swagger/user-swagger/create-user/index.swagger.ts
  libs/services/src/swagger/user-swagger/create-user/index.ts
  libs/services/src/swagger/user-swagger/update-user/index.swagger.ts
  libs/services/src/swagger/user-swagger/update-user/index.ts
Labels: enhancement, BE

#485 Improvement/responsive datadiri
  libs/modules-fe/src/auth/login/module.tsx
  libs/modules-fe/src/dashboard/biodata/module.tsx
Labels: improvement

#489 improve : design pmb user
  libs/components/src/organisms/sidebar/index.tsx
  libs/modules-fe/src/dashboard/biodata/module.tsx
  libs/modules-fe/src/dashboard/dokumen/module.tsx
  libs/modules-fe/src/dashboard/pendaftaran/module.tsx
  libs/modules-fe/src/layouts/dashboard.tsx
Labels: improvement

#493 bugfix: fix missing properties zod student
  libs/controllers/src/student/index.ts
  libs/entities/src/schemas/student-schemas/create-student/index.ts
  libs/entities/src/schemas/student-schemas/index.ts
  libs/entities/src/schemas/student-schemas/update-student/index.ts
  libs/models/src/prisma/schema.prisma
  libs/services/src/student/index.ts
  libs/services/src/swagger/student-swagger/create-student/index.ts
  libs/services/src/swagger/student-swagger/update-student/index.ts
  libs/utilities/src/exclude-schema/index.ts
  libs/utilities/src/index.ts
Labels: bug, BE

#499 feature: add refresh token rotation
  libs/components/src/molecules/inputs/text/index.tsx
  libs/modules-fe/src/auth/login/next-auth.ts
Labels: enhancement, FE

#503 improvement: move refresh token to body field
  libs/api/strategies/src/auth/rt.strategy.ts
Labels: enhancement, BE

#502 Improvement: get student by id
  apps/pmb/.env.example
  libs/api/controllers/src/student/index.ts
Labels: enhancement, BE

#500 bugfix: styling sidebar dashboard desktop
  libs/api/models/src/prisma/migrations/20230729085218_students/migration.sql
  libs/web/components/src/organisms/sidebar/index.tsx
Labels: bug, FE

#506 Improvement/types student service
  libs/api/controllers/src/auth/index.ts
  libs/api/controllers/src/student/index.ts
  libs/api/services/src/auth/index.ts
  libs/api/services/src/student/index.ts
  libs/api/services/src/swagger/auth-swagger/logout/index.ts
  libs/entities/src/enum/student.ts
  libs/entities/src/types/forgot-password.ts
  libs/entities/src/types/index.ts
  libs/entities/src/types/logout.ts
  libs/entities/src/types/resend-otp.ts
  libs/entities/src/types/reset-password.ts
  libs/entities/src/types/student.ts
  libs/entities/src/types/verify-otp-password.ts
  libs/entities/src/types/verify-otp.ts
Labels: enhancement, BE

#507 Feature : Add skeleton di Landing Page, Beasiswapage, Biaya Kuliah Page
  apps/pmb/app/beasiswa/loading.tsx
  apps/pmb/app/biaya-kuliah/loading.tsx
  apps/pmb/app/loading.tsx
Labels: enhancement, improvement, FE

#525 Feature/slider hero section
  apps/pmb/app/dashboard/loading.tsx
  apps/pmb/nextauth.d.ts
  apps/pmb/public/illustrations/slider-1.webp
  apps/pmb/public/illustrations/slider-2.webp
  apps/pmb/public/illustrations/slider-3.webp
  libs/web/components/src/nextauth.d.ts
  libs/web/components/src/organisms/hero-banner/index.tsx
  libs/web/components/src/organisms/hero-banner/type.ts
  libs/web/modules/src/auth/register/module.tsx
  libs/web/modules/src/landing/hero/section.tsx
  libs/web/modules/src/nextauth.d.ts
  libs/web/services/src/nextauth.d.ts
Labels: enhancement, FE

#524 bugfix: refresh token rotation
  libs/web/modules/src/auth/login/api.ts
  libs/web/modules/src/auth/login/next-auth.ts
Labels: bug, FE

#526 Improvement: update types
  libs/api/controllers/src/location/index.ts
  libs/api/controllers/src/student/index.ts
  libs/api/services/src/cloudinary/index.ts
  libs/api/services/src/location/index.ts
  libs/api/services/src/student/index.ts
  libs/entities/src/types/file.ts
  libs/entities/src/types/index.ts
  libs/entities/src/types/location.ts
  libs/entities/src/types/student.ts
Labels: bug, BE

#527 Improvement/add enum job
  libs/entities/src/enum/index.ts
  libs/entities/src/enum/job.ts
Labels: BE

#529 improvement: zod schema
  libs/api/controllers/src/auth/index.ts
  libs/api/controllers/src/student/index.ts
  libs/api/controllers/src/user/index.ts
  libs/api/services/src/auth/index.ts
  libs/entities/src/schemas/auth-schemas/forgot-password/index.ts
  libs/entities/src/schemas/auth-schemas/login/index.ts
  libs/entities/src/schemas/auth-schemas/logout/index.ts
  libs/entities/src/schemas/auth-schemas/register/index.ts
  libs/entities/src/schemas/auth-schemas/req-user/index.ts
  libs/entities/src/schemas/auth-schemas/resend-otp/index.ts
  libs/entities/src/schemas/auth-schemas/reset-password/index.ts
  libs/entities/src/schemas/auth-schemas/verify/index.ts
  libs/entities/src/schemas/student-schemas/update-student/index.ts
  libs/entities/src/schemas/user-schemas/create-user/index.ts
  libs/entities/src/schemas/user-schemas/update-user/index.ts
  libs/web/modules/src/auth/forgot/module.tsx
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/auth/login/next-auth.ts
  libs/web/modules/src/auth/register/module.tsx
Labels: improvement, FE, BE

#531 improvement: update schema, add enum and update type
  libs/api/models/src/prisma/schema.prisma
  libs/api/services/src/swagger/student-swagger/update-student/index.ts
  libs/entities/src/types/student.ts
Labels: BE

#534 improvement: formatting phone number register from UI UX
  libs/web/components/src/molecules/inputs/text/index.tsx
  libs/web/components/src/molecules/inputs/text/types.ts
  libs/web/modules/src/auth/register/module.tsx
Labels: improvement, FE

#539 Improvement/separate get location
  libs/api/controllers/src/location/index.ts
  libs/api/services/src/location/index.ts
  libs/entities/src/types/location.ts
Labels: enhancement, improvement, BE
