Repository uninus-opensource/uninus-superapp, pull requests merged in 2023-10, with the labels that each got.

#1266 feature: add endpoint get lecturer by id
  apps/api/employee/src/app/app.controller.ts
  apps/api/employee/src/app/app.service.ts
  libs/api/controllers/src/employee/index.ts
  libs/api/models/src/prisma/schema.prisma
Labels: BE

#1287 Improvement/registration path
  apps/api/finance/.eslintrc.json
  apps/api/finance/jest.config.ts
  apps/api/finance/project.json
  apps/api/finance/src/app/app.controller.ts
  apps/api/finance/src/app/app.module.ts
  apps/api/finance/src/app/app.service.ts
  apps/api/finance/src/assets/.gitkeep
  apps/api/finance/src/main.ts
  apps/api/finance/tsconfig.app.json
  apps/api/finance/tsconfig.json
  apps/api/finance/tsconfig.spec.json
  apps/api/finance/webpack.config.js
  apps/api/general/src/app/app.controller.ts
  apps/api/general/src/app/app.service.ts
  libs/api/controllers/src/general/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/entities/src/types/general/index.ts
Labels: improvement, BE

#1292 feature:slicing-page-pembayaran
  apps/web/pmb/user/app/dashboard/pembayaran/page.tsx
  apps/web/pmb/user/app/dashboard/template.tsx
  libs/web/components/src/molecules/inputs/radio/index.tsx
  libs/web/modules/src/dashboard/user/index.ts
  libs/web/modules/src/dashboard/user/pembayaran/index.ts
  libs/web/modules/src/dashboard/user/pembayaran/module.tsx
  libs/web/modules/src/dashboard/user/pembayaran/store.ts
  libs/web/modules/src/dashboard/user/pembayaran/type.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
Labels: enhancement, FE

#1298 Improvement/jurusan detail pembayaran
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
Labels: improvement, FE

#1299 Improvement : design dashboard user
  apps/web/pmb/user/public/illustrations/warning.svg
  bun.lockb
  libs/web/modules/src/dashboard/user/module.tsx
Labels: improvement, FE

#1303 improvement: endpoint create user
  apps/api/user/src/app/app.controller.ts
  apps/api/user/src/app/app.service.ts
  libs/api/controllers/src/user/index.ts
  libs/api/dto/src/user-dto/create-user/index.ts
  libs/entities/src/types/user/index.ts
Labels: improvement, BE

#1310 improvement: dashboard flow payment
  apps/web/pmb/user/app/dashboard/template.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
Labels: improvement, FE

#1314 improvement: upload field & edit data pendaftar bagian formulir
  apps/web/pmb/user/app/dashboard/template.tsx
  libs/web/components/src/molecules/inputs/upload-field/index.tsx
  libs/web/components/src/molecules/inputs/upload-field/types.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/module.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-formulir/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-formulir/schema.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-formulir/store.ts
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
Labels: improvement, FE

#1325 improvement: improve endpoint delete scholarship
  apps/api/general/src/app/app.service.ts
Labels: improvement, BE

#1326 Bugfix/conditional role
  apps/api/user/src/app/app.service.ts
Labels: bug, BE

#1327 Feature : Add Create user
  libs/web/components/src/organisms/modal/index.tsx
  libs/web/modules/src/dashboard/admin/data-akun/api.ts
  libs/web/modules/src/dashboard/admin/data-akun/hook.ts
  libs/web/modules/src/dashboard/admin/data-akun/table.tsx
  libs/web/modules/src/dashboard/admin/data-akun/types.ts
Labels: enhancement, FE

#1334 feature: add endpoint get academic staff by id
  apps/api/employee/src/app/app.controller.ts
  apps/api/employee/src/app/app.service.ts
  libs/api/controllers/src/employee/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/entities/src/types/employee/index.ts
  libs/entities/src/types/employee/lecturer/index.ts
  libs/entities/src/types/employee/tendik/index.ts
Labels: BE

#1335 Feature/crud master data
  libs/entities/src/types/general/index.ts
  libs/web/modules/src/dashboard/admin/api.ts
  libs/web/modules/src/dashboard/admin/data-master/api.ts
  libs/web/modules/src/dashboard/admin/data-master/hook.ts
  libs/web/modules/src/dashboard/admin/data-master/store.ts
  libs/web/modules/src/dashboard/admin/data-master/table.tsx
  libs/web/modules/src/dashboard/admin/data-master/type.ts
  libs/web/modules/src/dashboard/admin/hook.ts
Labels: FE

#1336 improvement: perubahan flow payment
  libs/web/components/src/atoms/index.ts
  libs/web/components/src/atoms/redirect-link/index.spec.tsx
  libs/web/components/src/atoms/redirect-link/index.tsx
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/modules/src/dashboard/user/selection/endtest/module.tsx
  libs/web/modules/src/dashboard/user/selection/module.tsx
  nx.json
Labels: improvement, FE

#1347 improvemet: jalur pendaftaran pmb user
  libs/web/modules/src/dashboard/user/pendaftaran/api.ts
  libs/web/modules/src/dashboard/user/pendaftaran/hooks.ts
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/schema.ts
  libs/web/modules/src/dashboard/user/pendaftaran/store.ts
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
Labels: improvement, FE

#1348 Improvement/position to string
  apps/api/student/src/app/app.service.ts
  libs/api/dto/src/student-dto/update-student/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/entities/src/types/student/index.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-orangtua/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-orangtua/schema.ts
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/schema.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/store.ts
  libs/web/modules/src/dashboard/user/selection/endtest/module.tsx
  libs/web/modules/src/dashboard/user/selection/module.tsx
Labels: improvement, FE, BE

#1355 Bugfix/update student
  apps/api/general/src/app/app.service.ts
  apps/api/student/src/app/app.service.ts
  libs/api/dto/src/student-dto/update-student/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/entities/src/schemas/student-schemas/update-student/index.ts
  libs/entities/src/types/student/index.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-formulir/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-formulir/schema.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-formulir/store.ts
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/schema.ts
  libs/web/modules/src/dashboard/user/pendaftaran/store.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
Labels: bug, FE, BE

#1357 bugfix: failed when update documents
  apps/api/student/src/app/app.service.ts
  libs/api/models/src/prisma/schema.prisma
  libs/entities/src/types/student/index.ts
Labels: bug, BE

#1364 feature: integrasi validasi berkas data pendaftar
  apps/web/pmb/admin/tailwind.config.js
  libs/entities/src/types/student/index.ts
  libs/web/components/src/molecules/inputs/checkbox/index.tsx
  libs/web/components/src/molecules/inputs/checkbox/type.ts
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/module.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/validasi/module.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/validasi/section/berkas-khusus/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/validasi/section/berkas-umum/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/validasi/section/rapor-snbt/index.tsx
  libs/web/modules/src/dashboard/admin/module/card-section.tsx
  libs/web/modules/src/dashboard/admin/module/chart-line.tsx
Labels: enhancement, FE

#1371 feature: menambahkan api contract untuk bendahara penerimaan
  bendahara.penerimaan.api.contract.json
Labels: enhancement

#1366 improvement: question test
  apps/api/general/src/app/app.controller.ts
  apps/api/general/src/app/app.service.ts
  apps/api/student/src/app/app.service.ts
  libs/api/controllers/src/general/index.ts
  libs/api/dto/src/general-dto/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/entities/src/types/general/index.ts
  libs/entities/src/types/student/index.ts
Labels: improvement, BE

#1370 improvement: responsif beberapa dashboard admin
  libs/web/modules/src/dashboard/admin/data-akun/table.tsx
  libs/web/modules/src/dashboard/admin/data-master/table.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/module.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-formulir/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-orangtua/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/nilai-raport/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/table.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/validasi/section/berkas-khusus/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/validasi/section/berkas-umum/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/validasi/section/rapor-snbt/index.tsx
  libs/web/modules/src/dashboard/admin/module/card-section.tsx
Labels: improvement, FE

#1367 improvement: responsive dashboard user
  apps/web/pmb/user/tailwind.config.js
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/modules/src/dashboard/user/module.tsx
  libs/web/modules/src/dashboard/user/pembayaran/module.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
  libs/web/modules/src/dashboard/user/selection/endtest/module.tsx
  libs/web/modules/src/dashboard/user/selection/intruction/module.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/module.tsx
Labels: improvement, FE

#1379 improvement:update response for card admin
  apps/api/general/src/app/app.service.ts
  apps/api/student/src/app/app.service.ts
  libs/entities/src/types/general/index.ts
  libs/web/modules/src/dashboard/admin/module/card-section.tsx
Labels: improvement, BE

#1386 improvement:change-alert-master-data
  apps/web/pmb/admin/tailwind.config.js
  libs/web/components/src/atoms/button/index.tsx
  libs/web/components/src/atoms/button/interface.ts
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/components/src/organisms/modal/index.tsx
  libs/web/components/src/organisms/modal/type.ts
  libs/web/modules/src/dashboard/admin/data-master/table.tsx
Labels: improvement, FE

#1387 improvement: add guardian lecturer student
  libs/api/dto/src/student-dto/update-student/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/api/models/src/prisma/seed.ts
  package.json
Labels: improvement, BE

#1388 feature: add finance service
  apps/api/finance/src/app/app.controller.ts
  apps/api/finance/src/app/app.service.ts
  libs/api/controllers/src/finance/index.ts
  libs/api/controllers/src/index.ts
  libs/api/master/src/index.ts
  libs/api/modules/src/finance/index.ts
  libs/api/modules/src/index.ts
Labels: BE

#1392 improvement: perubahan flow beasiswa pmb user & integrasi
  apps/web/pmb/user/app/dashboard/registrasi/beasiswa/page.tsx
  apps/web/pmb/user/app/dashboard/registrasi/beasiswa/upload-berkas/page.tsx
  libs/web/components/src/molecules/inputs/radio/index.spec.tsx
  libs/web/components/src/molecules/inputs/radio/index.tsx
  libs/web/components/src/molecules/inputs/radio/types.ts
  libs/web/modules/src/dashboard/admin/data-bayar/table.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-orangtua/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/edit-data-pendaftar/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/pembayaran/module.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/index.ts
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/upload-berkas/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/store.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
Labels: improvement, FE

#1397 improvement: kondisional rendering jalur pendafataran dan bug formulir pmb user
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/dokumen/type.ts
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
Labels: improvement, FE

#1400 Feature/api contract bendahara penerimaan
  bendahara.penerimaan.api.contract.json
  libs/api/contracts/finance/bendahara.penerimaan.api.contract.json
Labels: BE

#1406 bugfix: styling dashboard pmb user
  libs/web/components/src/atoms/redirect-link/index.tsx
  libs/web/components/src/molecules/inputs/upload-field/index.tsx
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/upload-berkas/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/module.tsx
Labels: bug, FE

#1411 Fix : style pmb admin from qa
  apps/web/evaluasi/app/dashboard/page.tsx
  libs/web/modules/src/dashboard/admin/data-akun/table.tsx
  libs/web/modules/src/dashboard/admin/data-master/table.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/table.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/types.ts
  libs/web/modules/src/landing/testimonial/section.tsx
Labels: bug, FE

#1417 improvement:filtering total registrans
  apps/api/general/src/app/app.service.ts
  libs/entities/src/types/general/index.ts
Labels: improvement, BE

#1418 feature: integrasi test seleksi
  apps/web/pmb/user/app/auth/template.tsx
  apps/web/pmb/user/app/dashboard/template.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/selection/endtest/module.tsx
  libs/web/modules/src/dashboard/user/selection/intruction/module.tsx
  libs/web/modules/src/dashboard/user/selection/module.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/api.ts
  libs/web/modules/src/dashboard/user/selection/quiz/hook.ts
  libs/web/modules/src/dashboard/user/selection/quiz/module.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/store.ts
  libs/web/modules/src/dashboard/user/selection/quiz/type.ts
Labels: enhancement, FE

#1419 improvement: suffle answer question
  apps/api/general/src/app/app.service.ts
  libs/api/controllers/src/general/index.ts
  libs/entities/src/types/general/index.ts
Labels: improvement, BE

#1421 Feature/integrasi line chart pmb admin
  apps/web/tata-usaha/app/dashboard/loading.tsx
  apps/web/tata-usaha/app/dashboard/template.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/components/src/organisms/sidebar/type.ts
  libs/web/modules/src/dashboard/admin/api.ts
  libs/web/modules/src/dashboard/admin/hook.ts
  libs/web/modules/src/dashboard/admin/module/card-section.tsx
  libs/web/modules/src/dashboard/admin/module/chart-line.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/pdf/index.tsx
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: enhancement, FE

#1422 Improvement/change scenario questions
  apps/api/general/src/app/app.service.ts
  libs/api/dto/src/general-dto/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/entities/src/types/general/index.ts
  libs/entities/src/types/student/index.ts
  libs/web/modules/src/dashboard/admin/kelola-pertanyaan/table.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/module.tsx
Labels: improvement, BE

#1424 Improvement/change validation radio button
  libs/web/modules/src/dashboard/admin/data-pendaftar/validasi/section/berkas-khusus/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/validasi/section/berkas-umum/index.tsx
  libs/web/modules/src/dashboard/admin/data-pendaftar/validasi/section/rapor-snbt/index.tsx
Labels: improvement, FE

#1425 improvement: add new education student
  apps/api/student/src/app/app.service.ts
  libs/api/models/src/prisma/schema.prisma
  libs/entities/src/types/student/index.ts
Labels: improvement, BE

#1427 bugfix: test seleksi
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/dashboard/user/selection/endtest/module.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/module.tsx
Labels: bug, FE

#1434 bugfix build
  apps/web/pmb/admin/app/dashboard/template.tsx
  libs/web/modules/src/dashboard/admin/api.ts
  libs/web/modules/src/dashboard/admin/hook.ts
  libs/web/modules/src/dashboard/admin/module/chart-line.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/pdf/index.tsx
Labels: bug, FE

#1433 improvement: get payment obligations student
  apps/api/student/src/app/app.controller.ts
  apps/api/student/src/app/app.service.ts
  libs/api/controllers/src/student/index.ts
  libs/api/utilities/src/convert-number/index.ts
  libs/api/utilities/src/index.ts
  libs/entities/src/types/student/index.ts
Labels: improvement, BE

#1438 bugfix: tes seleksi & flow beasiswa
  libs/web/components/src/atoms/reveal/index.tsx
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/upload-berkas/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/selection/endtest/module.tsx
  libs/web/modules/src/dashboard/user/selection/intruction/module.tsx
  libs/web/modules/src/dashboard/user/selection/module.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/module.tsx
Labels: bug, FE

#1439 improvement: kondisi text field jabatan
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
Labels: improvement, FE

#1442 improvement: send email graduation student
  apps/api/student/src/app/app.service.ts
  libs/api/controllers/src/student/index.ts
  libs/api/dto/src/student-dto/update-student/index.ts
  libs/entities/src/templates/email-selection.ts
  libs/entities/src/templates/email.ts
  libs/entities/src/templates/index.ts
Labels: improvement, BE

#1440 Feature/integrasi doughnut line chart
  apps/web/pmb/admin/app/dashboard/template.tsx
  libs/web/modules/src/dashboard/admin/api.ts
  libs/web/modules/src/dashboard/admin/hook.ts
  libs/web/modules/src/dashboard/admin/module/card-section.tsx
  libs/web/modules/src/dashboard/admin/module/chart-bar.tsx
  libs/web/modules/src/dashboard/admin/module/chart-doughnut.tsx
  libs/web/modules/src/dashboard/admin/module/chart-line.tsx
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: enhancement, FE

#1443 bugfix: triger registration status
  apps/api/student/src/app/app.service.ts
Labels: bug, BE

#1463 feature: sidebar siakad
  apps/web/siakad/app/dashboard/template.tsx
  apps/web/siakad/middleware.ts
  apps/web/siakad/tailwind.config.js
  libs/web/components/src/atoms/icons/index.ts
  libs/web/components/src/atoms/icons/nusaverse/index.tsx
  libs/web/components/src/organisms/index.ts
  libs/web/components/src/organisms/sidebar-v2/index.tsx
  libs/web/components/src/organisms/sidebar-v2/types.ts
Labels: enhancement, FE

#1464 improvement: slicing dashboard tata usaha
  apps/web/tata-usaha/app/dashboard/page.tsx
  apps/web/tata-usaha/app/layout.tsx
  apps/web/tata-usaha/tailwind.config.js
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/dashboard/index.ts
  libs/web/modules/src/dashboard/tata-usaha/index.ts
  libs/web/modules/src/dashboard/tata-usaha/module.tsx
  libs/web/modules/src/dashboard/tata-usaha/store.ts
Labels: improvement, FE

#1472 Improvement/integration payment
  apps/api/finance/.env-example
  apps/api/finance/src/app/app.controller.ts
  apps/api/finance/src/app/app.module.ts
  apps/api/finance/src/app/app.service.ts
  libs/api/controllers/src/finance/index.ts
  libs/api/dto/src/finance-dto/index.ts
  libs/api/dto/src/index.ts
  libs/api/master/src/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/api/utilities/src/index.ts
  libs/api/utilities/src/signature/index.ts
  libs/api/utilities/src/split-fullname/index.ts
  libs/entities/src/types/finance/index.ts
  libs/entities/src/types/index.ts
  libs/entities/src/types/payment/index.ts
  package.json
  yarn.lock
Labels: improvement, BE

#1475 Feature/api contract bendahara penerimaan
  apps/api/finance/src/app/app.controller.ts
  apps/api/finance/src/app/app.service.ts
  libs/api/contracts/finance/bendahara.penerimaan.api.contract.json
  libs/api/controllers/src/finance/index.ts
  libs/entities/src/enum/finance.ts
  libs/entities/src/enum/index.ts
  libs/entities/src/types/finance/index.ts
Labels: BE

#1476 feature: navbar siakad & improvement: sidebar siakad
  apps/web/siakad/app/dashboard/page.tsx
  apps/web/siakad/app/dashboard/template.tsx
  apps/web/siakad/public/illustrations/NusaVerse-White.svg
  apps/web/siakad/public/illustrations/NusaVerse.svg
  libs/web/components/src/atoms/icons/nusaverse/index.tsx
  libs/web/components/src/organisms/index.ts
  libs/web/components/src/organisms/navbar-siakad/index.tsx
  libs/web/components/src/organisms/sidebar-v2/index.tsx
  libs/web/components/src/organisms/sidebar-v2/types.ts
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: enhancement, improvement, FE
