Repository uninus-opensource/uninus-superapp, pull requests merged in 2023-08, with the labels that each got.

#547 Improvement/update validasi phone number register
  libs/entities/src/schemas/auth-schemas/register/index.ts
  libs/web/modules/src/auth/register/module.tsx
Labels: bug, improvement, FE, BE

#552 Fix bug : Placeeholder di field orang tua/ wali dan memberi tanda pad…
  apps/pmb/app/dashboard/loading.tsx
  libs/web/components/src/molecules/inputs/radio/index.tsx
  libs/web/components/src/molecules/inputs/select/index.tsx
  libs/web/components/src/molecules/inputs/text/index.tsx
  libs/web/modules/src/dashboard/user/biodata/module.tsx
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
Labels: bug, improvement

#553 Fix Bug : Select option status dan pendidikan orangtua
  libs/entities/src/types/biodata.ts
  libs/web/modules/src/dashboard/user/biodata/module.tsx
  libs/web/modules/src/dashboard/user/biodata/store.ts
Labels: bug, FE

#560 Feature/skeleteon login,fix layout auth
  apps/pmb/app/auth/layout.tsx
  apps/pmb/app/auth/loading.tsx
  apps/pmb/app/auth/login/loading.tsx
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/auth/register/module.tsx
Labels: enhancement, improvement

#557 Mochamad Rafli | add redis service as cache to compose
  docker-compose.yml
Labels: improvement, BE

#559 feature: add endpoint for select field
  libs/api/controllers/src/index.ts
  libs/api/controllers/src/location/index.ts
  libs/api/controllers/src/select/index.ts
  libs/api/master/src/index.ts
  libs/api/models/src/prisma/migrations/20230731123503_/migration.sql
  libs/api/models/src/prisma/migrations/20230801033507_/migration.sql
  libs/api/models/src/prisma/migrations/20230801061637_/migration.sql
  libs/api/models/src/prisma/migrations/20230801065202_/migration.sql
  libs/api/models/src/prisma/migrations/20230801080839_/migration.sql
  libs/api/models/src/prisma/migrations/20230801084640_/migration.sql
  libs/api/models/src/prisma/migrations/20230801135844_/migration.sql
  libs/api/models/src/prisma/migrations/20230801144401_/migration.sql
  libs/api/models/src/prisma/migrations/20230802040618_/migration.sql
  libs/api/models/src/prisma/migrations/20230802044903_/migration.sql
  libs/api/models/src/prisma/schema.prisma
  libs/api/modules/src/index.ts
  libs/api/modules/src/location/index.ts
  libs/api/modules/src/select/index.ts
  libs/api/services/src/index.ts
  libs/api/services/src/location/index.ts
  libs/api/services/src/select/index.ts
  libs/entities/src/types/index.ts
  libs/entities/src/types/location.ts
  libs/entities/src/types/select-field.ts
Labels: enhancement, BE

#572 bugfix: auth-layout
  libs/web/components/src/molecules/inputs/text/index.tsx
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/auth/register/module.tsx
  libs/web/modules/src/scholarship/module.tsx
Labels: bug, FE

#574 bugfix : swagger optional query endpoint select
  libs/api/controllers/src/select/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/api/services/src/select/index.ts
Labels: bug, BE

#573 improvement: slider hero landing
  libs/web/components/src/organisms/hero-banner/index.tsx
  libs/web/modules/src/landing/module.tsx
Labels: bug, improvement, FE

#581 Improvement : responsive form biodata
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/modules/src/dashboard/user/biodata/module.tsx
Labels: improvement, FE

#582 Fix bug : Sidebar button logout & validasi zod register
  libs/entities/src/schemas/auth-schemas/register/index.ts
  libs/web/components/src/atoms/button/index.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
Labels: bug, FE

#616 improvement: pendaftaran dashboard
  apps/web/pmb/user/app/testcomp/page.tsx
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/index.ts
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/store.ts
Labels: improvement, FE

#617 Improvement : page biodata
  libs/entities/src/types/biodata.ts
  libs/web/modules/src/dashboard/user/biodata/module.tsx
  libs/web/modules/src/dashboard/user/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/biodata/section/data-pendidikan/index.tsx
Labels: enhancement, improvement

#620 feature: Floating button WA & Cek Kelulusan
  apps/web/pmb/user/public/illustrations/Neo-Uninus.webp
  apps/web/pmb/user/public/illustrations/Slider-4.webp
  apps/web/pmb/user/public/illustrations/Slider-difabel.webp
  apps/web/pmb/user/public/illustrations/logOut.webp
  apps/web/pmb/user/public/illustrations/uninus.webp
  libs/web/components/src/atoms/button/index.tsx
  libs/web/components/src/atoms/illustrations/hybriduniversity/hybrid-university.png
  libs/web/components/src/atoms/illustrations/kampusmerdeka/kampus-merdeka-white.png
  libs/web/components/src/atoms/illustrations/nuwhite/nu-white.png
  libs/web/components/src/molecules/footer/index.tsx
  libs/web/components/src/molecules/index.ts
  libs/web/components/src/molecules/popup/index.tsx
  libs/web/components/src/molecules/popup/type.ts
  libs/web/components/src/organisms/hero-banner/index.tsx
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/landing/module.tsx
  libs/web/modules/src/scholarship/peduli/module.tsx
Labels: enhancement, FE

#622 feature: add endpoint year graduate
  libs/api/controllers/src/select/index.ts
  libs/api/models/src/prisma/migrations/20230804075422_/migration.sql
  libs/api/models/src/prisma/schema.prisma
  libs/api/services/src/select/index.ts
  libs/entities/src/types/select-field.ts
Labels: enhancement

#623 staging #1
  apps/web/pmb/user/app/auth/forgot-password/loading.tsx
  apps/web/pmb/user/app/auth/reset-password/loading.tsx
  apps/web/pmb/user/app/auth/verifikasi-forget/loading.tsx
  apps/web/pmb/user/app/auth/verifikasi-otp/loading.tsx
  apps/web/pmb/user/public/illustrations/Neo-Uninus.webp
  apps/web/pmb/user/public/illustrations/Slider-4.webp
  apps/web/pmb/user/public/illustrations/Slider-difabel.webp
  apps/web/pmb/user/public/illustrations/logOut.webp
  apps/web/pmb/user/public/illustrations/uninus.webp
  libs/api/controllers/src/select/index.ts
  libs/api/models/src/prisma/migrations/20230804075422_/migration.sql
  libs/api/models/src/prisma/schema.prisma
  libs/api/services/src/select/index.ts
  libs/entities/src/types/select-field.ts
  libs/web/components/src/atoms/button/index.tsx
  libs/web/components/src/atoms/illustrations/hybriduniversity/hybrid-university.png
  libs/web/components/src/atoms/illustrations/kampusmerdeka/kampus-merdeka-white.png
  libs/web/components/src/atoms/illustrations/nuwhite/nu-white.png
  libs/web/components/src/molecules/footer/index.tsx
  libs/web/components/src/molecules/index.ts
  libs/web/components/src/molecules/popup/index.tsx
  libs/web/components/src/molecules/popup/type.ts
  libs/web/components/src/organisms/hero-banner/index.tsx
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/landing/module.tsx
  libs/web/modules/src/scholarship/peduli/module.tsx
Labels: staging

#626 feature: pmb admin login
  apps/web/pmb/admin/.env.example
  apps/web/pmb/admin/app/page.tsx
  apps/web/pmb/admin/middleware.ts
  apps/web/pmb/user/app/auth/login/page.tsx
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/auth/login/next-auth.ts
Labels: FE

#628 Improvement : Radio Button
  apps/web/pmb/user/app/beasiswa/beasiswamitra/page.tsx
  apps/web/pmb/user/app/beasiswa/beasiswapeduli/page.tsx
  apps/web/pmb/user/app/beasiswa/beasiswaprestasi/page.tsx
  apps/web/pmb/user/app/beasiswa/beasiswaunggul/page.tsx
  apps/web/pmb/user/app/beasiswa/page.tsx
  apps/web/pmb/user/app/biaya-kuliah/page.tsx
  apps/web/pmb/user/app/dashboard/biodata/page.tsx
  apps/web/pmb/user/app/dashboard/dokumen/page.tsx
  apps/web/pmb/user/app/dashboard/pendaftaran/page.tsx
  libs/web/components/src/molecules/inputs/radio/index.tsx
  libs/web/components/src/molecules/inputs/radio/types.ts
  libs/web/modules/src/dashboard/user/biodata/section/data-diri/index.tsx
Labels: global, improvement, FE

#629 improvement: input data sekolah ke DB
  apps/api/src/main.ts
  libs/api/controllers/src/select/index.ts
  libs/api/models/src/prisma/migrations/20230804182611_education_history/migration.sql
  libs/api/models/src/prisma/schema.prisma
  libs/api/services/src/select/index.ts
  libs/entities/src/types/select-field.ts
  package.json
  yarn.lock
Labels: improvement, BE

#639 feature: add endpoint scholarship
  libs/api/controllers/src/select/index.ts
  libs/api/models/src/prisma/migrations/20230805065255_/migration.sql
  libs/api/models/src/prisma/schema.prisma
  libs/api/services/src/auth/index.ts
  libs/api/services/src/select/index.ts
  libs/entities/src/types/select-field.ts
Labels: enhancement

#638 bugfix: register fe
  libs/entities/src/schemas/auth-schemas/register/index.ts
  libs/web/modules/src/auth/register/module.tsx
Labels: bug, FE

#641 Improvement/update request country
  libs/api/controllers/src/select/index.ts
  libs/api/services/src/select/index.ts
  libs/entities/src/types/select-field.ts
Labels: enhancement, BE

#646 feature: add modal cek kelulusan
  apps/web/pmb/user/app/layout.tsx
  apps/web/pmb/user/app/testcomp/page.tsx
  apps/web/pmb/user/tailwind.config.js
  libs/entities/src/schemas/user-schemas/index.ts
  libs/entities/src/schemas/user-schemas/nopeserta-user/index.ts
  libs/web/components/src/atoms/button/index.spec.tsx
  libs/web/components/src/atoms/button/index.tsx
  libs/web/components/src/atoms/button/interface.ts
  libs/web/components/src/atoms/illustrations/arrowline/index.tsx
  libs/web/components/src/molecules/footer/index.tsx
  libs/web/components/src/molecules/inputs/text/index.tsx
  libs/web/components/src/molecules/inputs/text/types.ts
  libs/web/components/src/organisms/modal/index.tsx
  libs/web/components/src/organisms/modal/interface.ts
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/landing/modal-floatingbutton/index.ts
  libs/web/modules/src/landing/modal-floatingbutton/section.tsx
  libs/web/modules/src/landing/modal-floatingbutton/type.ts
  libs/web/modules/src/landing/module.tsx
Labels: enhancement, FE

#652 feature: add new navbar and bugfix slider sliding
  apps/web/pmb/user/app/layout.tsx
  libs/web/components/src/organisms/hero-banner/index.tsx
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/components/src/organisms/navbar/type.ts
Labels: bug, enhancement, FE

#656 feature:add endpoint to check graduate status
  libs/api/controllers/src/student/index.ts
  libs/api/models/src/prisma/migrations/20230807034414_/migration.sql
  libs/api/models/src/prisma/schema.prisma
  libs/api/services/src/student/index.ts
  libs/api/services/src/swagger/student-swagger/graduation-status/index.ts
  libs/api/services/src/swagger/student-swagger/index.ts
  libs/entities/src/types/student.ts
Labels: enhancement

#658 feature:program-page
  apps/web/pmb/user/app/program-studi/page.tsx
  apps/web/pmb/user/public/illustrations/agama.webp
  apps/web/pmb/user/public/illustrations/ekonomi.webp
  apps/web/pmb/user/public/illustrations/hukum.webp
  apps/web/pmb/user/public/illustrations/ilkom.webp
  apps/web/pmb/user/public/illustrations/pendidikan.webp
  apps/web/pmb/user/public/illustrations/pertanian.webp
  apps/web/pmb/user/public/illustrations/program-study.webp
  apps/web/pmb/user/public/illustrations/teknik.webp
  libs/web/modules/src/index.ts
  libs/web/modules/src/program-studi/index.ts
  libs/web/modules/src/program-studi/module.tsx
  libs/web/modules/src/program-studi/store.ts
  libs/web/modules/src/program-studi/type.ts
Labels: enhancement, FE

#665 Improvement : sidebar and form regiistrasi
  apps/web/pmb/admin/app/dashboard/layout.tsx
  apps/web/pmb/user/app/dashboard/layout.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/dashboard/user/biodata/module.tsx
  libs/web/modules/src/dashboard/user/biodata/section/berkas-khusus/indes.tsx
  libs/web/modules/src/dashboard/user/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/biodata/section/data-pendidikan/index.tsx
Labels: enhancement, FE

#671 bugfix: poster beasiswa yang terlalu besar
  libs/web/components/src/atoms/button/index.spec.tsx
  libs/web/components/src/atoms/button/index.tsx
  libs/web/components/src/organisms/hero-banner/index.tsx
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/modules/src/landing/modal-floatingbutton/section.tsx
  libs/web/modules/src/scholarship/module.tsx
Labels: bug, FE

#670 Feature/add endpoint check graduate status
  libs/api/controllers/src/student/index.ts
  libs/entities/src/schemas/student-schemas/check-graduation-student/index.ts
  libs/entities/src/schemas/student-schemas/index.ts
Labels: BE

#673 Bugfix/landing page biaya kuliah
  apps/web/pmb/user/app/auth/login/loading.tsx
  libs/web/components/src/molecules/inputs/radio/enum.ts
  libs/web/components/src/molecules/inputs/radio/index.spec.tsx
  libs/web/components/src/molecules/inputs/radio/index.tsx
  libs/web/components/src/molecules/inputs/radio/types.ts
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/modules/src/landing/modal-floatingbutton/section.tsx
  libs/web/modules/src/tuition-fee/module.tsx
Labels: bug, FE

#681 feature: pembayaran
  apps/web/pmb/user/public/illustrations/pdfIllustrations/ring-bottom.png
  apps/web/pmb/user/public/illustrations/pdfIllustrations/ring.png
  apps/web/pmb/user/public/illustrations/pdfIllustrations/uninus.png
  apps/web/pmb/user/tailwind.config.js
  libs/web/components/src/atoms/index.ts
  libs/web/components/src/atoms/pdf/fonts.ts
  libs/web/components/src/atoms/pdf/index.ts
  libs/web/components/src/atoms/pdf/pendaftaran/index.tsx
  libs/web/components/src/atoms/pdf/pendaftaran/viewer/index.tsx
  libs/web/modules/src/dashboard/user/biodata/module.tsx
  libs/web/modules/src/dashboard/user/biodata/section/pembayaran/index.tsx
  libs/web/modules/src/dashboard/user/index.ts
  package.json
  yarn.lock
Labels: enhancement, FE

#685 Improvement : page formulir regitasi
  libs/entities/src/types/select-field.ts
  libs/web/components/src/molecules/inputs/upload-field/index.tsx
  libs/web/components/src/molecules/inputs/upload-field/types.ts
  libs/web/modules/src/dashboard/user/biodata/module.tsx
  libs/web/modules/src/dashboard/user/biodata/section/berkas-khusus/indes.tsx
  libs/web/modules/src/dashboard/user/biodata/section/berkas-khusus/index.tsx
  libs/web/modules/src/dashboard/user/biodata/section/data-diri/api.ts
  libs/web/modules/src/dashboard/user/biodata/section/data-diri/hooks.ts
  libs/web/modules/src/dashboard/user/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/biodata/section/data-ortu/api.ts
  libs/web/modules/src/dashboard/user/biodata/section/data-ortu/hooks.ts
  libs/web/modules/src/dashboard/user/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/services/src/location/api.ts
Labels: enhancement, FE

#692 improvement: add unit test react pdf, delete unused file pdfViewer
  libs/web/components/src/atoms/pdf/pendaftaran/index.spec.tsx
  libs/web/components/src/atoms/pdf/pendaftaran/viewer/index.tsx
Labels: enhancement, FE

#693 feature: add unit test pada beberapa component
  apps/web/pmb/user/public/illustrations/uninus-logo.webp
  libs/web/components/src/atoms/reveal/index.spec.tsx
  libs/web/components/src/atoms/reveal/index.tsx
  libs/web/components/src/molecules/popup/index.spec.tsx
  libs/web/components/src/molecules/popup/index.tsx
  libs/web/components/src/molecules/sidebar/index.spec.tsx
  libs/web/components/src/molecules/sidebar/index.tsx
  libs/web/components/src/organisms/accordion/index.spec.tsx
  libs/web/components/src/organisms/accordion/index.tsx
  libs/web/components/src/organisms/card/index.spec.tsx
  libs/web/components/src/organisms/card/index.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/landing/modal-floatingbutton/section.tsx
  package.json
  yarn.lock
Labels: enhancement, FE

#688 feature: add endpoint school types
  libs/api/controllers/src/select/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/api/services/src/select/index.ts
  libs/entities/src/types/select-field.ts
Labels: enhancement, BE

#705 improvement: change library from bcrypt to argon2
  libs/api/utilities/src/password/index.ts
  package.json
  yarn.lock
Labels: improvement, BE

#697 Feature/unit test search select
  libs/web/components/src/molecules/inputs/search/ic-search.tsx
  libs/web/components/src/molecules/inputs/search/index.spec.tsx
  libs/web/components/src/molecules/inputs/search/index.tsx
  libs/web/components/src/molecules/inputs/select/enum.ts
  libs/web/components/src/molecules/inputs/select/index.spec.tsx
  libs/web/components/src/molecules/inputs/select/index.tsx
  libs/web/components/src/molecules/inputs/select/types.ts
Labels: enhancement, FE

#703 Improvement : integrasi other select option
  libs/entities/src/types/select-field.ts
  libs/web/components/src/molecules/inputs/radio/index.tsx
  libs/web/components/src/molecules/inputs/radio/types.ts
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/modules/src/dashboard/user/biodata/section/data-diri/api.ts
  libs/web/modules/src/dashboard/user/biodata/section/data-diri/hooks.ts
  libs/web/modules/src/dashboard/user/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/biodata/section/data-ortu/api.ts
  libs/web/modules/src/dashboard/user/biodata/section/data-ortu/hooks.ts
  libs/web/modules/src/dashboard/user/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/biodata/section/data-pendidikan/api.ts
  libs/web/modules/src/dashboard/user/biodata/section/data-pendidikan/hooks.ts
  libs/web/modules/src/dashboard/user/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/biodata/section/pembayaran/index.tsx
Labels: bug, enhancement, FE

#708 Feature/add crud test seleksi
  libs/api/controllers/src/select/index.ts
  libs/api/models/src/prisma/schema.prisma
  libs/api/services/src/select/index.ts
  libs/entities/src/types/index.ts
  libs/entities/src/types/questions.ts
Labels: enhancement, BE

#709 improve: modal cek kelulusan & slider
  apps/web/pmb/user/.env.example
  apps/web/pmb/user/public/illustrations/Slider-difabel.webp
  apps/web/pmb/user/public/illustrations/slider-1.webp
  apps/web/pmb/user/public/illustrations/slider-2.webp
  apps/web/pmb/user/public/illustrations/slider-3.webp
  apps/web/pmb/user/public/illustrations/slider-4.webp
  libs/web/components/src/organisms/hero-banner/index.tsx
  libs/web/components/src/organisms/modal/index.tsx
  libs/web/modules/src/landing/modal-floatingbutton/section.tsx
  libs/web/modules/src/scholarship/peduli/module.tsx
Labels: improvement, FE

#714 Feature : Slicing page Test Seleksi
  apps/web/pmb/user/app/dashboard/layout.tsx
  apps/web/pmb/user/app/dashboard/selection/endtest/page.tsx
  apps/web/pmb/user/app/dashboard/selection/intruction/page.tsx
  apps/web/pmb/user/app/dashboard/selection/loading.tsx
  apps/web/pmb/user/app/dashboard/selection/page.tsx
  apps/web/pmb/user/app/dashboard/selection/quiz/page.tsx
  apps/web/pmb/user/app/layout.tsx
  apps/web/pmb/user/public/illustrations/endTestImage.webp
  apps/web/pmb/user/public/illustrations/testseleksi.webp
  libs/web/modules/src/dashboard/user/index.ts
  libs/web/modules/src/dashboard/user/selection/endtest/index.ts
  libs/web/modules/src/dashboard/user/selection/endtest/module.tsx
  libs/web/modules/src/dashboard/user/selection/index.ts
  libs/web/modules/src/dashboard/user/selection/intruction/index.ts
  libs/web/modules/src/dashboard/user/selection/intruction/module.tsx
  libs/web/modules/src/dashboard/user/selection/module.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/index.ts
  libs/web/modules/src/dashboard/user/selection/quiz/module.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/store.ts
  libs/web/modules/src/dashboard/user/selection/quiz/type.ts
  libs/web/modules/src/dashboard/user/selection/store/index.tsx
  libs/web/modules/src/dashboard/user/selection/store/type.ts
Labels: enhancement, FE

#724 bugfix: error pdf download in production
  apps/web/pmb/user/public/fonts/Montserrat-Bold.ttf
  apps/web/pmb/user/public/fonts/Montserrat.ttf
  libs/web/components/src/atoms/pdf/fonts.ts
  libs/web/components/src/atoms/pdf/index.ts
  libs/web/components/src/atoms/pdf/pendaftaran/index.spec.tsx
  libs/web/components/src/atoms/pdf/pendaftaran/index.tsx
  package.json
Labels: bug, FE

#725 improve: navbar menu program trigger when hover to it
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/components/src/organisms/navbar/type.ts
Labels: improvement, FE

#726 Improvement : menambah component breadcrumb dan implemet pada page
  apps/web/pmb/admin/app/dashboard/layout.tsx
  apps/web/pmb/user/app/dashboard/layout.tsx
  apps/web/pmb/user/app/dashboard/registrasi/biodata/loading.tsx
  apps/web/pmb/user/app/dashboard/registrasi/biodata/page.tsx
  apps/web/pmb/user/app/dashboard/registrasi/biodata/type.ts
  apps/web/pmb/user/app/dashboard/registrasi/pembayaran/page.tsx
  libs/web/components/src/atoms/bread-crumb/index.tsx
  libs/web/components/src/atoms/bread-crumb/types.ts
  libs/web/components/src/atoms/index.ts
  libs/web/modules/src/dashboard/user/biodata/section/pembayaran/index.tsx
  libs/web/modules/src/dashboard/user/index.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/index.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/berkas-khusus/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/store.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/type.ts
  libs/web/modules/src/dashboard/user/registrasi/index.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/index.tsx
Labels: enhancement, FE

#727 Improvement : integrasi get select option pendaftaran
  libs/entities/src/types/select-field.ts
  libs/web/modules/src/dashboard/user/pendaftaran/api.ts
  libs/web/modules/src/dashboard/user/pendaftaran/hooks.ts
  libs/web/modules/src/dashboard/user/pendaftaran/index.ts
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/store.ts
  nx.json
  package.json
  yarn.lock
Labels: improvement, FE

#728 improvement: update beasiswa page from UI UX
  apps/web/pmb/user/public/illustrations/beasiswaIllustrations/nusantara-berprestasi.webp
  apps/web/pmb/user/public/illustrations/beasiswaIllustrations/nusantara-mitra.webp
  apps/web/pmb/user/public/illustrations/beasiswaIllustrations/nusantara-peduli.webp
  apps/web/pmb/user/public/illustrations/beasiswaIllustrations/nusantara-unggul.webp
  libs/web/modules/src/scholarship/mitra/module.tsx
  libs/web/modules/src/scholarship/module.tsx
  libs/web/modules/src/scholarship/peduli/module.tsx
  libs/web/modules/src/scholarship/prestasi/module.tsx
  libs/web/modules/src/scholarship/unggul/module.tsx
Labels: improvement, FE

#740 Feature : Add Timer On page Seleksi Dashboard
  libs/web/modules/src/dashboard/user/selection/quiz/module.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/store.ts
  libs/web/modules/src/dashboard/user/selection/quiz/type.ts
Labels: enhancement, FE

#748 feature: slicing new navbar & sidebar
  libs/web/components/src/atoms/button/index.spec.tsx
  libs/web/components/src/atoms/button/index.tsx
  libs/web/components/src/molecules/sidebar/index.spec.tsx
  libs/web/components/src/molecules/sidebar/index.tsx
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/components/src/organisms/navbar/type.ts
Labels: enhancement, FE

#753 improvement: move pdf to module
  libs/web/components/src/atoms/index.ts
  libs/web/components/src/atoms/pdf/index.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/index.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/pdf/index.spec.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/pdf/index.tsx
Labels: bug, FE

#754 Bugfix/sidebar landing button
  libs/web/components/src/atoms/button/index.spec.tsx
  libs/web/components/src/atoms/button/index.tsx
  libs/web/components/src/atoms/button/interface.ts
  libs/web/components/src/molecules/sidebar/index.tsx
  libs/web/components/src/organisms/hero-banner/index.tsx
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/modules/src/scholarship/mitra/module.tsx
  libs/web/modules/src/scholarship/peduli/module.tsx
  libs/web/modules/src/scholarship/prestasi/module.tsx
  libs/web/modules/src/scholarship/unggul/module.tsx
Labels: bug, improvement, FE

#756 feature: add unit test pada beberapa components
  libs/web/components/src/molecules/sidebar/index.spec.tsx
  libs/web/components/src/organisms/hero-banner/index.spec.tsx
  libs/web/components/src/organisms/hero-banner/index.tsx
  libs/web/components/src/organisms/hero-banner/type.ts
  libs/web/components/src/organisms/modal/index.spec.tsx
  libs/web/components/src/organisms/modal/index.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/landing/hero/section.tsx
  libs/web/modules/src/program-studi/module.tsx
  libs/web/modules/src/scholarship/module.tsx
  libs/web/modules/src/tuition-fee/module.tsx
Labels: enhancement, FE

#758 Fix Bug :Timer Page Test Seleksi
  apps/web/pmb/user/app/auth/forgot-password/page.tsx
  apps/web/pmb/user/app/auth/layout.tsx
  apps/web/pmb/user/app/auth/login/page.tsx
  apps/web/pmb/user/app/auth/register/page.tsx
  apps/web/pmb/user/app/auth/reset-password/page.tsx
  apps/web/pmb/user/app/auth/verifikasi-forget/page.tsx
  apps/web/pmb/user/app/auth/verifikasi-otp/page.tsx
  apps/web/pmb/user/app/beasiswa/beasiswamitra/page.tsx
  apps/web/pmb/user/app/beasiswa/beasiswapeduli/page.tsx
  apps/web/pmb/user/app/beasiswa/beasiswaprestasi/page.tsx
  apps/web/pmb/user/app/beasiswa/beasiswaunggul/page.tsx
  apps/web/pmb/user/app/beasiswa/page.tsx
  apps/web/pmb/user/app/biaya-kuliah/page.tsx
  apps/web/pmb/user/app/dashboard/dokumen/page.tsx
  apps/web/pmb/user/app/dashboard/layout.tsx
  apps/web/pmb/user/app/dashboard/page.tsx
  apps/web/pmb/user/app/dashboard/pendaftaran/page.tsx
  apps/web/pmb/user/app/dashboard/registrasi/biodata/page.tsx
  apps/web/pmb/user/app/dashboard/registrasi/pembayaran/page.tsx
  apps/web/pmb/user/app/dashboard/selection/endtest/page.tsx
  apps/web/pmb/user/app/dashboard/selection/intruction/page.tsx
  apps/web/pmb/user/app/dashboard/selection/page.tsx
  apps/web/pmb/user/app/dashboard/selection/quiz/page.tsx
  apps/web/pmb/user/app/layout.tsx
  apps/web/pmb/user/app/page.tsx
  apps/web/pmb/user/app/program-studi/page.tsx
  libs/web/modules/src/auth/verifikasi-otp/module.tsx
  libs/web/modules/src/dashboard/user/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/module.tsx
  libs/web/modules/src/dashboard/user/selection/endtest/module.tsx
  libs/web/modules/src/dashboard/user/selection/intruction/module.tsx
  libs/web/modules/src/dashboard/user/selection/module.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/module.tsx
  libs/web/modules/src/dashboard/user/selection/store/index.tsx
  libs/web/modules/src/dashboard/user/selection/store/type.ts
  libs/web/modules/src/landing/module.tsx
  libs/web/modules/src/program-studi/module.tsx
  libs/web/modules/src/scholarship/mitra/module.tsx
  libs/web/modules/src/scholarship/module.tsx
  libs/web/modules/src/scholarship/peduli/module.tsx
  libs/web/modules/src/scholarship/prestasi/module.tsx
  libs/web/modules/src/scholarship/unggul/module.tsx
  libs/web/modules/src/tuition-fee/module.tsx
Labels: bug, improvement, FE

#759 feature:add-unit-test-component
  apps/web/pmb/user/public/illustrations/FAI.webp
  apps/web/pmb/user/public/illustrations/FHUM.webp
  apps/web/pmb/user/public/illustrations/FIKOM.webp
  apps/web/pmb/user/public/illustrations/FKIP.webp
  apps/web/pmb/user/public/illustrations/FKON.webp
  apps/web/pmb/user/public/illustrations/FTAN.webp
  apps/web/pmb/user/public/illustrations/FTEK.webp
  apps/web/pmb/user/public/illustrations/PASCA.webp
  apps/web/pmb/user/public/illustrations/fai.webp
  apps/web/pmb/user/public/illustrations/fhum.webp
  apps/web/pmb/user/public/illustrations/fikom.webp
  apps/web/pmb/user/public/illustrations/fkip.webp
  apps/web/pmb/user/public/illustrations/fkon.webp
  apps/web/pmb/user/public/illustrations/ftan.webp
  apps/web/pmb/user/public/illustrations/ftek.webp
  apps/web/pmb/user/public/illustrations/pasca.webp
  libs/web/components/src/atoms/bread-crumb/index.spec.tsx
  libs/web/components/src/atoms/bread-crumb/index.tsx
  libs/web/components/src/organisms/navbar/index.spec.tsx
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/components/src/organisms/tab/index.spec.tsx
  libs/web/components/src/organisms/tab/index.tsx
Labels: FE

#760 improvement: update image jalur seleksi
  apps/web/pmb/user/public/illustrations/talent2.svg
  libs/web/components/src/organisms/hero-banner/index.tsx
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/components/src/organisms/tab/index.spec.tsx
  libs/web/components/src/organisms/tab/index.tsx
  libs/web/modules/src/landing/benefit/section.tsx
  libs/web/modules/src/landing/selection/section.tsx
Labels: improvement, FE

#769 Improvement : responsive dashboard user
  apps/api/auth/tsconfig.app.json
  apps/api/auth/tsconfig.spec.json
  apps/api/email/tsconfig.app.json
  apps/api/email/tsconfig.spec.json
  apps/api/file/tsconfig.app.json
  apps/api/file/tsconfig.spec.json
  apps/api/location/tsconfig.app.json
  apps/api/location/tsconfig.spec.json
  apps/api/pmb/tsconfig.app.json
  apps/api/pmb/tsconfig.spec.json
  apps/api/tsconfig.app.json
  apps/api/tsconfig.spec.json
  apps/web/pmb/user/app/dashboard/registrasi/biodata/loading.tsx
  libs/web/modules/src/dashboard/user/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  migrations.json
  package.json
  tsconfig.base.json
  yarn.lock
Labels: bug, improvement, FE

#772 improvement : slicing design detail payment
  apps/web/pmb/user/app/dashboard/registrasi/pembayaran/detail/page.tsx
  apps/web/pmb/user/app/dashboard/registrasi/pembayaran/status/page.tsx
  apps/web/pmb/user/public/illustrations/payment/bca.webp
  apps/web/pmb/user/public/illustrations/payment/btn.webp
  apps/web/pmb/user/public/illustrations/payment/mandiri.webp
  apps/web/pmb/user/public/illustrations/payment/shopee.webp
  apps/web/pmb/user/public/illustrations/payment/tokopedia.webp
  libs/web/components/src/molecules/inputs/checkbox/index.tsx
  libs/web/components/src/molecules/inputs/checkbox/type.ts
  libs/web/components/src/molecules/inputs/radio/index.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/index.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/module.tsx
  libs/web/modules/src/dashboard/user/selection/intruction/module.tsx
Labels: improvement, FE

#778 Impovement : slicing dashboard scholarship and integration get scholarship
  apps/web/pmb/user/app/dashboard/layout.tsx
  apps/web/pmb/user/app/dashboard/registrasi/beasiswa/page.tsx
  apps/web/pmb/user/public/illustrations/beasiswa.webp
  libs/entities/src/types/select-field.ts
  libs/web/components/src/atoms/bread-crumb/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/api.ts
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/index.ts
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/index.ts
Labels: improvement, FE

#779 Improvement : Add validation disabled on button submit scholarship and add toastify
  libs/web/components/src/molecules/inputs/radio/index.tsx
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/berkas-khusus/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
Labels: improvement, FE

#787 Improvement : Status pembayaran Succes | Pending | Failed
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/alertStatus/index.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/alertStatus/section.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/alertStatus/type.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/module.tsx
Labels: improvement, FE

#793 bugfix: dropdown navbar
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/modules/src/landing/selection/section.tsx
Labels: bug, FE

#795 Fix : link registration sidebard dashboard
  apps/web/pmb/user/app/dashboard/layout.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/selection/intruction/module.tsx
Labels: bug, FE

#800 improvement:status-sidebar-getData-register
  apps/api/.env.example
  apps/web/pmb/user/.env.example
  libs/web/components/src/organisms/sidebar/api.ts
  libs/web/components/src/organisms/sidebar/hooks.ts
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/index.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
Labels: improvement, FE

#804 Fix : bug wording and style from qa
  apps/web/pmb/user/app/testcomp/page.tsx
  libs/web/components/src/atoms/bread-crumb/index.tsx
  libs/web/components/src/molecules/inputs/search/index.spec.tsx
  libs/web/components/src/molecules/inputs/search/index.tsx
  libs/web/components/src/organisms/accordion/index.tsx
  libs/web/components/src/organisms/accordion/type.ts
  libs/web/components/src/organisms/hero-banner/index.spec.tsx
  libs/web/components/src/organisms/hero-banner/index.tsx
  libs/web/components/src/organisms/navbar/index.spec.tsx
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/components/src/organisms/tab/index.spec.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/berkas-khusus/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/landing/banner-welcome/section.tsx
  libs/web/modules/src/landing/modal-floatingbutton/section.tsx
  libs/web/modules/src/program-studi/module.tsx
Labels: improvement, FE

#810 improvement: integrasi put biodata pada section data diri & navbar diperkecil
  apps/web/pmb/user/tailwind.config.js
  libs/entities/src/index.ts
  libs/entities/src/interfaces/biodata.ts
  libs/entities/src/interfaces/index.ts
  libs/entities/src/types/biodata.ts
  libs/entities/src/types/index.ts
  libs/entities/src/types/student.ts
  libs/web/components/src/molecules/inputs/radio/index.tsx
  libs/web/components/src/molecules/inputs/radio/types.ts
  libs/web/components/src/molecules/inputs/text/index.tsx
  libs/web/components/src/organisms/sidebar/api.ts
  libs/web/components/src/organisms/sidebar/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/store.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/type.ts
  libs/web/modules/src/landing/modal-floatingbutton/section.tsx
  libs/web/modules/src/scholarship/mitra/module.tsx
  libs/web/modules/src/scholarship/peduli/module.tsx
  libs/web/modules/src/scholarship/prestasi/module.tsx
  libs/web/modules/src/scholarship/unggul/module.tsx
Labels: improvement, FE

#811 feature: integrasi pendaftaran dashboard
  apps/web/pmb/user/tailwind.config.js
  libs/web/modules/src/dashboard/user/pendaftaran/api.ts
  libs/web/modules/src/dashboard/user/pendaftaran/hooks.ts
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/type.ts
Labels: enhancement, FE

#812 feature:pdf-bukti-kelulusan
  apps/web/pmb/user/.env.example
  apps/web/pmb/user/public/illustrations/pdfIllustrations/pdf-test.jpeg
  libs/web/modules/src/landing/modal-floatingbutton/pdf/index.tsx
  libs/web/modules/src/landing/modal-floatingbutton/section.tsx
Labels: enhancement, FE

#814 Improvement : Add variant on Global Component Upload File
  apps/web/pmb/user/app/testcomp/page.tsx
  libs/web/components/src/molecules/inputs/upload-field/index.tsx
  libs/web/components/src/molecules/inputs/upload-field/types.ts
  libs/web/modules/src/auth/forgot/module.tsx
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/alertStatus/section.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/alertStatus/type.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/module.tsx
Labels: improvement, FE

#821 Improvement : Add field Rata-rata pada page Data Nilai
  libs/web/components/src/molecules/inputs/upload-field/index.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
Labels: improvement, FE

#822 bugfix: location fe select option
  apps/api/location/src/app/app.service.ts
  libs/entities/src/types/select-field.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/store.ts
  libs/web/services/src/location/api.ts
  libs/web/services/src/location/hooks.ts
Labels: bug, FE

#828 fix : bug choice payment method and responsive
  libs/web/components/src/molecules/inputs/radio/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
Labels: bug, FE

#835 feature: integrasi data pendidikan & bugfix sidebar
  apps/api/pmb/src/general/general.service.ts
  libs/entities/src/schemas/student-schemas/update-student/index.ts
  libs/entities/src/types/select-field.ts
  libs/entities/src/types/student.ts
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/components/src/molecules/inputs/select-option/types.ts
  libs/web/components/src/molecules/inputs/text/index.tsx
  libs/web/components/src/molecules/inputs/text/types.ts
  libs/web/components/src/molecules/sidebar/index.tsx
  libs/web/components/src/organisms/navbar/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
Labels: bug, enhancement, FE

#836 Bugfixing : form registrasi and sidebar
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/components/src/molecules/inputs/select-option/types.ts
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
Labels: bug, FE

#837 bugfix: zod validation data diri & data pendidikan
  libs/entities/src/schemas/student-schemas/update-student/index.ts
  libs/web/components/src/molecules/inputs/text/types.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
Labels: bug, FE

#846 improvement: conditional rendering upload berkas
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
Labels: improvement, FE

#847 Fix : Bug Responsive tes seleksi and form biodata
  apps/web/pmb/user/app/auth/login/loading.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/selection/endtest/module.tsx
  libs/web/modules/src/dashboard/user/selection/module.tsx
Labels: bug, FE

#852 Improvement : Conditional Upload File base Scholarship option
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/berkas-khusus/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
Labels: improvement, FE

#853 feature: integrasi data ortu
  libs/entities/src/schemas/student-schemas/update-student/index.ts
  libs/entities/src/types/select-field.ts
  libs/entities/src/types/student.ts
  libs/web/components/src/molecules/inputs/checkbox/index.tsx
  libs/web/components/src/molecules/inputs/checkbox/type.ts
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/type.ts
Labels: enhancement, FE

#855 Improvement/conditional rendering biodata
  libs/entities/src/schemas/student-schemas/update-student/index.ts
  libs/entities/src/types/student.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/store.ts
Labels: enhancement, FE

#868 feature: add conditional rendering sidebar user & add recoil store to service
  apps/web/pmb/user/app/dashboard/layout.tsx
  libs/entities/src/schemas/student-schemas/update-student/index.ts
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/components/src/organisms/sidebar/type.ts
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/api.ts
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/index.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/services/src/index.ts
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/index.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: enhancement, improvement, FE

#869 improvemet: conditional rendering tes teleksi dashboard user
  apps/web/pmb/user/app/dashboard/layout.tsx
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
Labels: improvement, FE

#870 Improvement : Conditional button download pdf on payment
  libs/web/components/src/molecules/inputs/upload-field/index.tsx
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/alertStatus/type.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/module.tsx
Labels: bug, improvement, FE

#873 Improvement/dashboard/nilai rapor
  libs/entities/src/types/student.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/hook.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/type.ts
Labels: improvement, FE

#871 Improvement/conditional button pembayaran
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
Labels: improvement, FE

#882 bugfix: select disable pendaftaran dashboard
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
Labels: bug, FE

#883 bugfix: put registrasi data diri
  apps/web/pmb/user/app/dashboard/layout.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/store.ts
Labels: bug, FE

#885 Improvement/conditional button pembayaran
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
Labels: improvement, FE

#890 improvement: change http method put -> patch
  libs/web/modules/src/dashboard/user/pendaftaran/api.ts
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/api.ts
Labels: improvement, FE

#891 bugfix:disable-provinsi-wna-render-biodata-s2-s3
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
Labels: bug, FE

#897 bugfix: sidebar dashboard mobile
  apps/web/pmb/user/app/dashboard/layout.tsx
  libs/entities/src/schemas/student-schemas/update-student/index.ts
  libs/web/components/src/organisms/sidebar/index.tsx
Labels: bug, FE

#898 improvement: biodata dashboard patch data
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/store.ts
Labels: bug, improvement, FE

#900 bugfix: background card pembayaran
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
Labels: bug, FE

#902 Improvement/select pendaftaran dashboard s3
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
Labels: improvement, FE

#905 Improvement : Add Variant upload profile picture
  libs/web/components/src/molecules/inputs/upload-field/index.tsx
  libs/web/components/src/molecules/inputs/upload-field/types.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
Labels: improvement, FE

#906 improvement:bukti-pendaftaran
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/pdf/index.tsx
Labels: improvement, FE

#908 Feature/verifikasi berhasil page
  apps/web/pmb/user/app/auth/verifikasi-berhasil/loading.tsx
  apps/web/pmb/user/app/auth/verifikasi-berhasil/page.tsx
  libs/web/modules/src/auth/index.ts
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/auth/verifikasi-berhasil/index.ts
  libs/web/modules/src/auth/verifikasi-berhasil/module.tsx
  libs/web/modules/src/auth/verifikasi-otp/module.tsx
Labels: enhancement, FE

#911 Bugfix/disable button after input formulir dashboard
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
Labels: bug, FE

#912 bugfix: disable state button & select option / S3 program selection path
  libs/entities/src/types/select-field.ts
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
Labels: bug, FE

#913 bugfix: toastify register & otp time refresh
  libs/web/modules/src/auth/register/module.tsx
  libs/web/modules/src/auth/verifikasi-otp/module.tsx
Labels: bug, FE

#914 improvement: show degree program on detail payment
  libs/web/modules/src/dashboard/user/pendaftaran/index.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
Labels: improvement, FE

#916 Improvement/jabatan dashboard data ortu
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/type.ts
Labels: improvement, FE

#918 improvement: status payment
  .vscode/settings.json
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/module.tsx
Labels: improvement, FE

#917 Bugfix/error submit beasiswa
  .vscode/settings.json
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/api.ts
Labels: FE, BE

#919 fix : bug validation npsn and add zod text field parent
  libs/web/components/src/molecules/inputs/radio/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/schema.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/schema.ts
Labels: bug, FE

#920 Bugfix/error submit beasiswa
  apps/web/pmb/user/app/dashboard/registrasi/biodata/page.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
Labels: improvement, FE

#923 improve: make apps full isr
  apps/web/pmb/user/app/beasiswa/detail/template.tsx
  apps/web/pmb/user/app/layout.tsx
Labels: enhancement, dependencies, FE

#939 Imporvement/select data ortu profecy status
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
Labels: FE

#954 Improvement : add design procedure payment
  apps/web/pmb/user/app/dashboard/template.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/module.tsx
Labels: improvement, FE

#955 Improvement : Add 3 new field on upload nilai utbk
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
Labels: improvement, FE

#953 Improvemen/kuis seleksi
  .gitignore
  .vscode/settings.json
  libs/web/components/src/organisms/modal/index.spec.tsx
  libs/web/components/src/organisms/modal/index.tsx
  libs/web/components/src/organisms/modal/interface.ts
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/module.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/store.ts
  libs/web/modules/src/dashboard/user/selection/quiz/type.ts
  libs/web/modules/src/landing/modal-floatingbutton/section.tsx
  libs/web/modules/src/program-studi/module.tsx
Labels: improvement

#967 improvement select option
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/schema.ts
  libs/web/providers/src/query/index.tsx
Labels: improvement, FE

#961 Improvement/tambah data sekolah
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
Labels: FE

#971 improvement: zod validation pendaftaran & biodata page
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/schema.ts
  libs/web/modules/src/dashboard/user/pendaftaran/store.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/schema.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/schema.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/store.ts
Labels: improvement, FE

#974 Improvement/data pendidikan smk
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
Labels: improvement, FE

#977 improvement: update api refresh token, forget password, register
  apps/api/auth/src/app/app.controller.ts
  apps/api/auth/src/app/app.service.ts
  libs/api/controllers/src/auth/index.ts
  libs/api/services/src/auth/index.ts
Labels: improvement, BE

#980 improvement: handle update utbk score
  apps/api/pmb/src/student/student.service.ts
  libs/api/models/src/prisma/schema.prisma
  libs/api/services/src/swagger/student-swagger/update-student/index.ts
  libs/entities/src/schemas/student-schemas/update-student/index.ts
  libs/entities/src/types/student.ts
Labels: improvement, BE
