Repository uninus-opensource/uninus-superapp, pull requests merged in 2023-06, with the labels that each got.

#32 feature: button variant
  apps/pmb/app/page.tsx
  libs/components/src/atoms/button/enums.ts
  libs/components/src/atoms/button/index.tsx
  libs/components/src/atoms/button/interface.ts
  libs/components/src/atoms/icons/index.ts
  libs/components/src/atoms/index.ts
  libs/components/src/atoms/loadings/index.ts
  libs/components/src/atoms/loadings/spinner/index.tsx
  libs/components/src/index.ts
  libs/components/src/lib/components.spec.tsx
  libs/components/src/lib/components.tsx
  libs/components/src/lib/hello-server.tsx
  libs/components/src/molecules/index.ts
  libs/components/src/organisms/index.ts
  libs/components/src/server.ts
  package.json
  yarn.lock
Labels: global

#34 improve/global component/button
  libs/components/src/atoms/button/index.tsx
  libs/components/src/atoms/button/interface.ts
Labels: enhancement, global

#35 Add global components | textfield
  apps/pmb/app/page.tsx
  libs/components/src/atoms/icons/eye/EyeOpen.tsx
  libs/components/src/atoms/icons/eye/EyeSlash.tsx
  libs/components/src/atoms/icons/eye/index.ts
  libs/components/src/atoms/icons/index.ts
  libs/components/src/molecules/index.ts
  libs/components/src/molecules/inputs/index.ts
  libs/components/src/molecules/inputs/text/index.tsx
  libs/components/src/molecules/inputs/text/types.ts
  package.json
  yarn.lock
Labels: global

#39 feature: add inputs checkbox
  apps/pmb/app/page.tsx
  libs/components/src/atoms/index.ts
  libs/components/src/molecules/inputs/checkbox/enum.ts
  libs/components/src/molecules/inputs/checkbox/index.tsx
  libs/components/src/molecules/inputs/checkbox/type.ts
  libs/components/src/molecules/inputs/index.ts
Labels: global

#41 improvement: add global component select
  apps/pmb/app/page.tsx
  libs/components/src/molecules/inputs/index.ts
  libs/components/src/molecules/inputs/select/index.tsx
  libs/components/src/molecules/inputs/select/types.ts
Labels: global

#45 bugfix: component checkbox & button
  apps/pmb/app/page.tsx
  libs/components/src/atoms/button/index.tsx
  libs/components/src/atoms/button/interface.ts
  libs/components/src/molecules/inputs/checkbox/index.tsx
  libs/components/src/molecules/inputs/checkbox/type.ts
Labels: bug, global

#46 Bugfix/global component/button
  apps/pmb/app/page.tsx
  libs/components/src/atoms/button/index.tsx
Labels: bug, global

#49 Feature/global component/navbar
  apps/pmb/app/layout.tsx
  apps/pmb/app/page.tsx
  libs/components/src/atoms/button/enums.ts
  libs/components/src/atoms/button/index.tsx
  libs/components/src/atoms/icons/hamburger/index.tsx
  libs/components/src/atoms/icons/hamburger/type.ts
  libs/components/src/atoms/icons/index.ts
  libs/components/src/atoms/illustrations/neouninus/Neo-Uninus.png
  libs/components/src/molecules/inputs/text/index.tsx
  libs/components/src/organisms/index.ts
  libs/components/src/organisms/navbar/index.tsx
  libs/components/src/organisms/navbar/type.ts
  package.json
  yarn.lock
Labels: global

#55 improvement: CRUD user
  apps/auth-api/src/main.ts
  apps/pmb-api/src/main.ts
  libs/controllers/src/user/index.ts
  libs/entities/src/index.ts
  libs/entities/src/user-dto/create-user.dto.ts
  libs/entities/src/user-dto/index.ts
  libs/entities/src/user-dto/update-user.dto.ts
  libs/modules/src/index.ts
  libs/modules/src/pmb/index.ts
  libs/services/src/user/index.ts
  package.json
  yarn.lock
Labels: enhancement

#57 improvement: auth api register
  libs/controllers/src/auth/index.ts
  libs/entities/src/index.ts
  libs/entities/src/lib/auth-dto/register.dto.ts
  libs/entities/src/register.ts
  libs/entities/tsconfig.lib.json
  libs/models/src/prisma/migrations/20230627174039_tambah_kolom_photo/migration.sql
  libs/models/src/prisma/migrations/20230628135943_update/migration.sql
  libs/models/src/prisma/migrations/20230628140530_add_default_role_id_1/migration.sql
  libs/models/src/prisma/schema.prisma
  libs/services/src/auth/index.ts
  libs/services/src/index.ts
  package.json
  yarn.lock
Labels: bug, documentation, enhancement

#54 Feature : Add Global Component Modal
  apps/pmb/app/layout.tsx
  apps/pmb/app/page.tsx
  libs/components/src/organisms/index.ts
  libs/components/src/organisms/modal/index.tsx
  libs/components/src/organisms/modal/interface.ts
Labels: enhancement, global

#73 feature: add global component footer | already responsive
  apps/pmb/app/page.tsx
  apps/pmb/tailwind.config.js
  libs/components/src/atoms/icons/email/index.tsx
  libs/components/src/atoms/icons/index.ts
  libs/components/src/atoms/icons/navigate/index.tsx
  libs/components/src/atoms/icons/phone/index.tsx
  libs/components/src/atoms/illustrations/hybriduniversity/Hybrid-University-1536x558.png
  libs/components/src/molecules/footer/index.tsx
  libs/components/src/molecules/footer/type.ts
  libs/components/src/molecules/index.ts
  libs/components/src/organisms/navbar/index.tsx
Labels: global

#90 feature: add global component sidebar & improvement others components
  apps/pmb/app/page.tsx
  libs/components/src/atoms/button/enums.ts
  libs/components/src/atoms/button/index.tsx
  libs/components/src/atoms/icons/index.ts
  libs/components/src/atoms/icons/x/index.tsx
  libs/components/src/molecules/footer/index.tsx
  libs/components/src/molecules/index.ts
  libs/components/src/molecules/sidebar/index.tsx
  libs/components/src/molecules/sidebar/type.ts
  libs/components/src/organisms/navbar/index.tsx
Labels: global

#97 Feature/page/about page
  apps/pmb/app/about/page.tsx
  apps/pmb/public/uninus-logo.png
  libs/components/src/atoms/index.ts
  libs/components/src/atoms/reveal/index.tsx
  libs/components/src/atoms/reveal/type.ts
Labels: enhancement, global
