Repository uninus-opensource/uninus-superapp, pull requests merged in 2023-11, with the labels that each got.

#1491 feature:slicing-dashboard-tracer-alumni
  apps/web/tracer-alumni/.env.example
  apps/web/tracer-alumni/app/dashboard/page.tsx
  apps/web/tracer-alumni/app/dashboard/template.tsx
  apps/web/tracer-alumni/middleware.ts
  apps/web/tracer-alumni/tailwind.config.js
  libs/web/modules/src/dashboard/index.ts
  libs/web/modules/src/dashboard/tracer-alumni/homepage/bar-chart.tsx
  libs/web/modules/src/dashboard/tracer-alumni/homepage/card.tsx
  libs/web/modules/src/dashboard/tracer-alumni/homepage/doughnut-chart.tsx
  libs/web/modules/src/dashboard/tracer-alumni/homepage/horizontal-bar.tsx
  libs/web/modules/src/dashboard/tracer-alumni/homepage/index.tsx
  libs/web/modules/src/dashboard/tracer-alumni/homepage/type.ts
  libs/web/modules/src/dashboard/tracer-alumni/index.ts
Labels: enhancement

#1492 improvement: handle error payment
  apps/api/finance/src/app/app.service.ts
  apps/api/src/main.ts
  libs/api/controllers/src/finance/index.ts
  libs/api/dto/src/finance-dto/index.ts
  libs/api/master/.eslintrc.json
  libs/api/master/README.md
  libs/api/master/jest.config.ts
  libs/api/master/project.json
  libs/api/master/src/index.ts
  libs/api/master/tsconfig.json
  libs/api/master/tsconfig.lib.json
  libs/api/master/tsconfig.spec.json
  libs/api/modules/src/auth/index.ts
  libs/api/modules/src/employee/index.ts
  libs/api/modules/src/finance/index.ts
  libs/api/modules/src/index.ts
  libs/api/modules/src/master/index.ts
  libs/api/modules/src/student/index.ts
  libs/api/modules/src/user/index.ts
  libs/entities/src/types/finance/index.ts
  package.json
  tsconfig.base.json
  yarn.lock
Labels: improvement, BE

#1496 feature: slicing dropdown profile
  apps/web/siakad/app/dashboard/template.tsx
  apps/web/siakad/tailwind.config.js
  libs/web/components/src/molecules/dropdowns/index.ts
  libs/web/components/src/molecules/dropdowns/notification/index.tsx
  libs/web/components/src/molecules/dropdowns/profile/index.tsx
  libs/web/components/src/molecules/dropdowns/profile/types.ts
  libs/web/components/src/molecules/index.ts
  libs/web/components/src/organisms/navbar-siakad/index.tsx
  libs/web/components/src/organisms/sidebar-v2/index.tsx
Labels: enhancement, FE

#1494 improvement: slicing krs siakad
  apps/web/siakad/app/dashboard/krs/page.tsx
  apps/web/siakad/app/dashboard/page.tsx
  apps/web/siakad/app/dashboard/template.tsx
  apps/web/siakad/tailwind.config.js
  libs/web/modules/src/dashboard/index.ts
  libs/web/modules/src/dashboard/siakad/index.ts
  libs/web/modules/src/dashboard/siakad/krs/index.ts
  libs/web/modules/src/dashboard/siakad/krs/module.tsx
  libs/web/modules/src/dashboard/siakad/krs/store.ts
  libs/web/modules/src/dashboard/siakad/krs/table.tsx
  libs/web/modules/src/dashboard/siakad/krs/type.ts
  libs/web/modules/src/dashboard/siakad/module.tsx
Labels: improvement, FE

#1495 Feature/add api contract manajemen pegawai
  libs/api/contracts/employee/manajemen.pegawai.api.contract.json
Labels: BE

#1503 feature: slicing notification dropdown siakad
  apps/web/siakad/tailwind.config.js
  libs/web/components/src/atoms/index.ts
  libs/web/components/src/atoms/notif/index.tsx
  libs/web/components/src/atoms/notif/type.ts
  libs/web/components/src/molecules/dropdowns/notification/index.tsx
  libs/web/components/src/molecules/dropdowns/notification/types.ts
  libs/web/components/src/molecules/dropdowns/profile/index.tsx
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/components/src/molecules/inputs/select-option/types.ts
  libs/web/components/src/organisms/navbar-siakad/index.tsx
  libs/web/modules/src/dashboard/siakad/krs/module.tsx
Labels: enhancement, FE

#1504 Feature : slicing Modul dashboard sisfo keuangan
  apps/web/sisfo/keuangan/app/dashboard/loading.tsx
  apps/web/sisfo/keuangan/app/dashboard/page.tsx
  apps/web/sisfo/keuangan/app/dashboard/template.tsx
  apps/web/sisfo/keuangan/public/illustrations/bg-auth.webp
  apps/web/sisfo/keuangan/public/illustrations/shapeBG.svg
  apps/web/sisfo/keuangan/tailwind.config.js
  libs/api/contracts/finance/bendahara.penerimaan.api.contract.json
  libs/web/modules/src/auth/login/module.tsx
  libs/web/modules/src/dashboard/finance/index.ts
  libs/web/modules/src/dashboard/finance/module/Table.tsx
  libs/web/modules/src/dashboard/finance/module/api.ts
  libs/web/modules/src/dashboard/finance/module/card-section.tsx
  libs/web/modules/src/dashboard/finance/module/chart-line.tsx
  libs/web/modules/src/dashboard/finance/module/hook.ts
  libs/web/modules/src/dashboard/finance/module/index.tsx
  libs/web/modules/src/dashboard/finance/module/store.ts
  libs/web/modules/src/dashboard/finance/module/type.ts
  libs/web/modules/src/dashboard/index.ts
  libs/web/services/src/axios/index.ts
Labels: enhancement, FE

#1505 bugfix: rewrite signature generator
  apps/api/finance/src/app/app.service.ts
  libs/api/dto/src/finance-dto/index.ts
  libs/api/utilities/src/signature/index.ts
  package.json
  yarn.lock
Labels: bug, BE

#1513 bugfix: remove scrolling modal
  apps/web/pmb/user/app/layout.tsx
  libs/web/components/src/organisms/modal/index.tsx
  yarn.lock
Labels: bug, FE

#1514 feature:siakad-dashboard
  apps/web/siakad/app/dashboard/page.tsx
  apps/web/siakad/app/dashboard/template.tsx
  apps/web/siakad/tailwind.config.js
  libs/web/modules/src/dashboard/siakad/homepage/bar-chart.tsx
  libs/web/modules/src/dashboard/siakad/homepage/cards.tsx
  libs/web/modules/src/dashboard/siakad/homepage/grades.tsx
  libs/web/modules/src/dashboard/siakad/homepage/index.tsx
  libs/web/modules/src/dashboard/siakad/homepage/store.ts
  libs/web/modules/src/dashboard/siakad/homepage/type.ts
  libs/web/modules/src/dashboard/siakad/index.ts
Labels: enhancement, FE

#1515 Feature : Slicing Dashboard Evaluasi Dosen
  apps/web/evaluasi/app/dashboard/loading.tsx
  apps/web/evaluasi/app/dashboard/page.tsx
  apps/web/evaluasi/app/dashboard/template.tsx
  apps/web/evaluasi/tailwind.config.js
  libs/web/modules/src/dashboard/evaluasi/dashboard/card-data.tsx
  libs/web/modules/src/dashboard/evaluasi/dashboard/chart-percen.tsx
  libs/web/modules/src/dashboard/evaluasi/dashboard/chart-score.tsx
  libs/web/modules/src/dashboard/evaluasi/dashboard/index.tsx
  libs/web/modules/src/dashboard/evaluasi/index.ts
  libs/web/modules/src/dashboard/index.ts
Labels: FE

#1523 improvement: tes integrasi react pdf
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/status/module.tsx
Labels: improvement, FE

#1524 Improvement/order id payment
  .dockerfiles/Dockerfile.api-auth
  .dockerfiles/Dockerfile.api-email
  .dockerfiles/Dockerfile.api-employee
  .dockerfiles/Dockerfile.api-file
  .dockerfiles/Dockerfile.api-finance
  .dockerfiles/Dockerfile.api-general
  .dockerfiles/Dockerfile.api-master
  .dockerfiles/Dockerfile.api-student
  .dockerfiles/Dockerfile.api-user
  .dockerfiles/Dockerfile.web-akreditasi
  .dockerfiles/Dockerfile.web-evaluasi
  .dockerfiles/Dockerfile.web-lms
  .dockerfiles/Dockerfile.web-neo-feeder
  .dockerfiles/Dockerfile.web-pegawai
  .dockerfiles/Dockerfile.web-pmb-admin
  .dockerfiles/Dockerfile.web-pmb-user
  .dockerfiles/Dockerfile.web-siakad
  .dockerfiles/Dockerfile.web-sisfo-akuntansi
  .dockerfiles/Dockerfile.web-sisfo-aset
  .dockerfiles/Dockerfile.web-sisfo-bendahara
  .dockerfiles/Dockerfile.web-sisfo-keuangan
  .dockerfiles/Dockerfile.web-smart-dashboard
  .dockerfiles/Dockerfile.web-tata-usaha
  .dockerfiles/Dockerfile.web-tracer-alumni
  .dockerfiles/docker-compose.yml
  apps/api/student/src/app/app.service.ts
  libs/api/models/src/prisma/schema.prisma
Labels: improvement, BE

#1530 feature: integrasi payment pmb user
  apps/web/pmb/user/app/dashboard/template.tsx
  apps/web/pmb/user/tailwind.config.js
  apps/web/siakad/app/global.css
  libs/entities/src/types/finance/index.ts
  libs/entities/src/types/student/index.ts
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/api.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/api.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/hooks.ts
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
Labels: enhancement, FE

#1533 bugfix from QA
  libs/web/modules/src/dashboard/user/registrasi/biodata/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
Labels: bug, FE

#1540 Improvement : Slicing all page Module Edom
  apps/web/evaluasi/app/dashboard/data-dosen/page.tsx
  apps/web/evaluasi/app/dashboard/hasil-evaluasi/page.tsx
  apps/web/evaluasi/app/dashboard/kelola-pertanyaan/page.tsx
  apps/web/evaluasi/app/dashboard/template.tsx
  apps/web/evaluasi/app/layout.tsx
  apps/web/evaluasi/public/illustrations/maul.png
  libs/web/modules/src/dashboard/evaluasi/dashboard/chart-bar.tsx
  libs/web/modules/src/dashboard/evaluasi/dashboard/chart-percen.tsx
  libs/web/modules/src/dashboard/evaluasi/dashboard/chart-score.tsx
  libs/web/modules/src/dashboard/evaluasi/dashboard/index.tsx
  libs/web/modules/src/dashboard/evaluasi/data-dosen/card-dosen.tsx
  libs/web/modules/src/dashboard/evaluasi/data-dosen/index.tsx
  libs/web/modules/src/dashboard/evaluasi/data-dosen/store.ts
  libs/web/modules/src/dashboard/evaluasi/data-dosen/types.ts
  libs/web/modules/src/dashboard/evaluasi/hasil-evaluasi/index.tsx
  libs/web/modules/src/dashboard/evaluasi/hasil-evaluasi/store.ts
  libs/web/modules/src/dashboard/evaluasi/hasil-evaluasi/table-hasil.tsx
  libs/web/modules/src/dashboard/evaluasi/hasil-evaluasi/types.ts
  libs/web/modules/src/dashboard/evaluasi/index.ts
  libs/web/modules/src/dashboard/evaluasi/kelola-pertanyaan/index.tsx
  libs/web/modules/src/dashboard/evaluasi/kelola-pertanyaan/store.ts
  libs/web/modules/src/dashboard/evaluasi/kelola-pertanyaan/table-kuesioner.tsx
  libs/web/modules/src/dashboard/evaluasi/kelola-pertanyaan/types.ts
Labels: FE

#1534 improvement: create finance callback
  apps/api/finance/src/app/app.service.ts
  apps/api/src/main.ts
  libs/api/controllers/src/auth/index.ts
  libs/api/controllers/src/finance/index.ts
  libs/api/controllers/src/student/index.ts
  libs/api/controllers/src/user/index.ts
  libs/api/decorators/.eslintrc.json
  libs/api/decorators/README.md
  libs/api/decorators/jest.config.ts
  libs/api/decorators/project.json
  libs/api/decorators/src/header/index.ts
  libs/api/decorators/src/index.ts
  libs/api/decorators/tsconfig.json
  libs/api/decorators/tsconfig.lib.json
  libs/api/decorators/tsconfig.spec.json
  libs/entities/src/schemas/auth-schemas/header/index.ts
  libs/entities/src/schemas/auth-schemas/index.ts
  libs/entities/src/schemas/finance/header/index.ts
  libs/entities/src/schemas/finance/index.ts
  libs/entities/src/schemas/index.ts
  package.json
  tsconfig.base.json
Labels: improvement, BE

#1547 feature: responsif dropdowns siakad & add notifications count
  apps/web/siakad/app/dashboard/template.tsx
  libs/web/components/src/atoms/index.ts
  libs/web/components/src/atoms/notif-button/index.tsx
  libs/web/components/src/atoms/notif-button/types.ts
  libs/web/components/src/molecules/dropdowns/notification/index.tsx
  libs/web/components/src/molecules/dropdowns/profile/index.tsx
  libs/web/components/src/molecules/dropdowns/profile/types.ts
  libs/web/components/src/organisms/navbar-siakad/index.tsx
  libs/web/components/tsconfig.spec.json
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: enhancement, FE

#1553 Feature/siakad biaya kuliah
  apps/web/siakad/app/dashboard/biaya-kuliah/page.tsx
  apps/web/siakad/app/dashboard/template.tsx
  apps/web/siakad/tailwind.config.js
  libs/web/modules/src/dashboard/siakad/biaya-kuliah/index.ts
  libs/web/modules/src/dashboard/siakad/biaya-kuliah/module.tsx
  libs/web/modules/src/dashboard/siakad/biaya-kuliah/store.ts
  libs/web/modules/src/dashboard/siakad/biaya-kuliah/table.tsx
  libs/web/modules/src/dashboard/siakad/biaya-kuliah/type.ts
  libs/web/modules/src/dashboard/siakad/index.ts
  libs/web/modules/src/dashboard/siakad/module.tsx
Labels: enhancement, FE

#1561 bugfix: QA issues PMB USER
  apps/web/pmb/user/app/dashboard/template.tsx
  libs/web/components/src/molecules/inputs/text/index.tsx
  libs/web/components/src/organisms/sidebar/hooks.ts
  libs/web/components/src/organisms/sidebar/index.tsx
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/upload-berkas/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-nilai/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-ortu/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/store.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/type.ts
  libs/web/services/src/recoil-store/hooks.ts
  libs/web/services/src/recoil-store/store.ts
  libs/web/services/src/recoil-store/type.ts
Labels: enhancement, FE

#1562 improvement: page payment
  apps/web/pegawai/app/global.css
  libs/web/components/src/molecules/inputs/select-option/index.tsx
  libs/web/components/src/molecules/inputs/select-option/types.ts
  libs/web/components/src/organisms/modal/index.tsx
  libs/web/modules/src/dashboard/pegawai/data-dosen-pensiun/table.tsx
  libs/web/modules/src/dashboard/pegawai/data-dosen/detail-dosen.tsx
  libs/web/modules/src/dashboard/pegawai/data-dosen/store.ts
  libs/web/modules/src/dashboard/pegawai/data-dosen/table.tsx
  libs/web/modules/src/dashboard/pegawai/data-dosen/types.ts
  libs/web/modules/src/dashboard/pegawai/data-pelamar-dosen/table.tsx
  libs/web/modules/src/dashboard/pegawai/data-pelamar-tendik/table.tsx
  libs/web/modules/src/dashboard/pegawai/data-tendik-pensiun/table.tsx
  libs/web/modules/src/dashboard/pegawai/data-tendik/store.ts
  libs/web/modules/src/dashboard/pegawai/data-tendik/table.tsx
  libs/web/modules/src/dashboard/pegawai/data-tendik/types.ts
  libs/web/modules/src/dashboard/user/pembayaran/module.tsx
  libs/web/modules/src/dashboard/user/pembayaran/store.ts
  libs/web/modules/src/dashboard/user/pembayaran/type.ts
Labels: improvement, FE

#1563 bugfix: wrong timestamp on header
  apps/api/finance/src/app/app.service.ts
  libs/entities/src/types/finance/index.ts
Labels: bug, BE

#1564 bugfix:disabilities
  libs/web/components/src/molecules/inputs/select-option/types.ts
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/schema.ts
Labels: bug

#1565 bugfix: payment flow
  libs/web/modules/src/dashboard/user/dokumen/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
  libs/web/modules/src/dashboard/user/selection/endtest/module.tsx
  libs/web/modules/src/dashboard/user/selection/intruction/module.tsx
  libs/web/modules/src/dashboard/user/selection/module.tsx
  libs/web/modules/src/dashboard/user/selection/quiz/module.tsx
Labels: bug, FE

#1571 bugfix: data pendidikan
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-pendidikan/index.tsx
Labels: bug, FE

#1572 improvement: redirect otto & bugfix: redirect beasiswa
  libs/web/modules/src/dashboard/user/pendaftaran/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/module.tsx
  libs/web/modules/src/dashboard/user/registrasi/beasiswa/upload-berkas/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/biodata/section/data-diri/index.tsx
  libs/web/modules/src/dashboard/user/registrasi/pembayaran/detail/module.tsx
Labels: bug, improvement, FE

#1573 improvement: slicing tabel data mahasiswa dan dosen modul tata usaha
  apps/web/tata-usaha/app/dashboard/data-dosen/page.tsx
  apps/web/tata-usaha/app/dashboard/data-mahasiswa/page.tsx
  apps/web/tata-usaha/app/dashboard/template.tsx
  apps/web/tata-usaha/app/layout.tsx
  apps/web/tata-usaha/tailwind.config.js
  libs/web/modules/src/dashboard/tata-usaha/data-dosen/index.tsx
  libs/web/modules/src/dashboard/tata-usaha/data-dosen/store.ts
  libs/web/modules/src/dashboard/tata-usaha/data-dosen/style.ts
  libs/web/modules/src/dashboard/tata-usaha/data-dosen/table.tsx
  libs/web/modules/src/dashboard/tata-usaha/data-dosen/type.ts
  libs/web/modules/src/dashboard/tata-usaha/data-mahasiswa/index.tsx
  libs/web/modules/src/dashboard/tata-usaha/data-mahasiswa/store.ts
  libs/web/modules/src/dashboard/tata-usaha/data-mahasiswa/style.ts
  libs/web/modules/src/dashboard/tata-usaha/data-mahasiswa/tabel.tsx
  libs/web/modules/src/dashboard/tata-usaha/data-mahasiswa/type.ts
  libs/web/modules/src/dashboard/tata-usaha/homepage/index.tsx
  libs/web/modules/src/dashboard/tata-usaha/homepage/store.ts
  libs/web/modules/src/dashboard/tata-usaha/index.ts
Labels: improvement, FE
