Repository uninus-opensource/uninus-superapp, pull requests merged in 2024-02, with the labels that each got.

#1717 improvement: add permissions response user
  apps/api/auth/src/app/app.service.ts
  apps/api/user/src/app/app.service.ts
  libs/entities/src/types/user/user.type.ts
Labels: improvement, BE

#1718 improvement : evaluasi dosen authentication
  apps/web/evaluasi/app/(auth)/auth/(login)/_actions/index.ts
  apps/web/evaluasi/app/(auth)/auth/(login)/_modules/index.tsx
  apps/web/evaluasi/app/(auth)/auth/(login)/login/loading.tsx
  apps/web/evaluasi/app/(auth)/auth/(login)/login/page.tsx
  apps/web/evaluasi/app/(auth)/auth/error.tsx
  apps/web/evaluasi/app/(dashboard)/dashboard/data-dosen/page.tsx
  apps/web/evaluasi/app/(dashboard)/dashboard/hasil-evaluasi/page.tsx
  apps/web/evaluasi/app/(dashboard)/dashboard/kelola-pertanyaan/page.tsx
  apps/web/evaluasi/app/(dashboard)/dashboard/loading.tsx
  apps/web/evaluasi/app/(dashboard)/dashboard/page.tsx
  apps/web/evaluasi/app/(dashboard)/dashboard/template.tsx
  apps/web/evaluasi/app/api/auth/[...nextauth]/route.ts
  apps/web/evaluasi/next.config.js
  apps/web/evaluasi/tsconfig.json
Labels: improvement, FE

#1720 feature: oauth google
  apps/api/.env.example
  apps/api/auth/src/app/app.controller.ts
  apps/api/auth/src/app/app.service.ts
  apps/api/user/src/app/app.controller.ts
  apps/api/user/src/app/app.service.ts
  libs/api/controllers/src/auth/index.ts
  libs/api/guard/src/at.guard.ts
  libs/api/guard/src/auth/index.ts
  libs/api/guard/src/google.guard.ts
  libs/api/guard/src/index.ts
  libs/api/guard/src/permission.guard.ts
  libs/api/guard/src/rt.guard.ts
  libs/api/models/src/drizzle/schema/users/index.ts
  libs/api/modules/src/master/index.ts
  libs/api/services/src/auth/index.ts
  libs/api/strategies/src/at.strategy.ts
  libs/api/strategies/src/auth/index.ts
  libs/api/strategies/src/google.strategy.ts
  libs/api/strategies/src/index.ts
  libs/api/strategies/src/rt.strategy.ts
  libs/entities/src/types/auth/login.type.ts
  libs/entities/src/types/auth/token.type.ts
  package.json
Labels: enhancement, BE
